INSTALL.md
Jenkinsfile
cluster/charts/rook-ceph/templates/clusterrolebinding.yaml
pkg/daemon/ceph/agent/flexvolume/controller.go
pkg/daemon/ceph/agent/flexvolume/controller_test.go
pkg/daemon/ceph/osd/daemon.go
pkg/daemon/ceph/osd/volume.go
pkg/daemon/ceph/osd/volume_test.go
pkg/operator/ceph/cluster/controller.go
pkg/operator/ceph/cluster/mon/env.go
pkg/operator/ceph/cluster/mon/mon.go
pkg/operator/ceph/cluster/osd/osd.go
pkg/operator/ceph/cluster/osd/spec.go
pkg/operator/ceph/cluster/osd/spec_test.go
pkg/operator/ceph/cr_manager.go
pkg/operator/ceph/disruption/controllerconfig/context.go
pkg/operator/ceph/disruption/controllerconfig/toleration.go
pkg/operator/ceph/disruption/controllerconfig/toleration_test.go
pkg/operator/ceph/disruption/nodedrain/reconcile.go
pkg/operator/nfs/controller.go
tests/integration/ceph_mon_test.go

Resyncing on commit https://github.com/rook/rook/commit/798c941896796fd47c462c08759ee1a6be86758a.

Resync on 798c941

---

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml

(cherry picked from commit 99e961f72a90ac35e535b63221407d46b4732017)
**Checklist:**

Backport: Added OSD utilization alerts

---

cluster/examples/kubernetes/ceph/common.yaml
pkg/operator/ceph/disruption/nodedrain/reconcile.go

Bug 1815147 RBAC and drain-canary deletion.

---

cluster/olm/ceph/generate-rook-csv.sh
pkg/operator/ceph/object/admin.go
pkg/operator/ceph/object/bucket/provisioner.go
pkg/operator/ceph/object/user.go

Release 1.3

---

pkg/operator/ceph/csi/csi-cephfsplugin-provisioner.yaml
pkg/operator/ceph/csi/spec.go

Enable the CSI driver if highter major k8s version than v1
**Checklist:**

Enable the CSI driver if highter major k8s version than v1

---

pkg/operator/ceph/object/bucket/s3-handlers.go

Bug 1872671: ceph: fix rebasing error

---

pkg/operator/ceph/object/bucket/provisionner_test.go

Fix unit test to comply with the new endpoint format.

Bug 1872589: ceph: fix unit test

---

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py

(cherry picked from commit 3de87ccd3534f5b9fe0f1a3958b071cf8adb839a)
Resolves #
**Checklist:**

Bug 1878853: ceph: fix to support TLS enabled rgw-endpoint

---

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py

(cherry picked from commit 3de87ccd3534f5b9fe0f1a3958b071cf8adb839a)
Resolves #
**Checklist:**

Bug 1876852: ceph: fix to support TLS enabled rgw-endpoint

---

pkg/operator/ceph/cluster/osd/spec.go

During the initialization encrypted OSD initialization sequence, we check
for the presence of the encrypted container. If it exists we don't try
to open it again since this will result in an error.
However, there is another case we need to handle, when the underlying
device is gone. For instance, if the pod/PV couple was drained and move
back, living the orphan dm. Once the pod comes back, the dm is still
present and perfectly matches. Unfortunately, the underlying disk is
different and thus the dm must be removed and the disk re-opened.
(cherry picked from commit 95ac992e48ccfd6f0872292755d6b50ce19395d1)
Resolves #
**Checklist:**

Bug 1885175: ceph: check underlaying block status

---

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py

An '--upgrade' option is added to the option list, which upgrades the
user permissions (caps) to match newer version. Will try to detect
'rgw-pool-prefix' or user can provide it through the argument.
Segregated the command line arguments into three groups - common, output
and upgrade
Resolves #
**Checklist:**

Bug 1881071: ceph: adding '--upgrade' option to the script

---

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py

Bug 1888593: Release 4.6 monitoring endpoint checks

---

Documentation/ceph-cluster-crd.md
cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
pkg/apis/rook.io/v1/types.go
pkg/operator/ceph/cluster/osd/config.go
pkg/operator/ceph/cluster/osd/deviceSet.go
pkg/operator/ceph/cluster/osd/osd.go
pkg/operator/ceph/cluster/osd/spec.go
pkg/operator/ceph/cluster/osd/spec_test.go

Bug 1925004: [release-4.6] Rook changes for tuneFastDeviceClass

---

pkg/operator/ceph/cluster/crash/reconcile.go

If Ceph pods were evicted onto other nodes, there is no reason for the
crash collector to remain on those nodes. So let's remove it.
(cherry picked from commit b9e91b600dcc3f518da6be93faf7aba45ea1d999)
(cherry picked from commit 778bf669764d551420d0af06c4e831e19aaca32c)

Bug 1898808: ceph: remove crash collector if ceph pod moved

---

pkg/operator/ceph/cluster/osd/spec.go

When the blkdevmapper init container initializes we must override any
existing special block. This will prevent re-using a different disk on
the OSD on PVC scenario.
Adding "--remove-destination" to the cp line will remove each existing
destination file before attempting to open it.
We **MUST** do this otherwise in environment where PVCs are dynamic, restarting the deployment will cause conflicts
When restarting the OSD, the PVC block might end up with a different Kernel disk allocation
For instance, prior to restart the block was mapped to 8:32 and when re-attached it was on 8:16
The previous "block" is still 8:32 so if we don't override it we will try to initialize on a disk that is not an OSD or worse another OSD
This is mainly because in …

Bug 1925055: ceph: always override existing block for blkdevmapper

---

pkg/operator/ceph/cluster/osd/spec.go

Bug 1926617: better expose vault API error messages

---

pkg/daemon/ceph/osd/kms/vault.go
pkg/operator/ceph/cluster/osd/osd.go

Bug 1926617: ceph: do not override existing keys

---

pkg/operator/ceph/cluster/cephstatus.go
pkg/operator/ceph/cluster/cephstatus_test.go
pkg/operator/ceph/cluster/mon/health.go
pkg/operator/ceph/cluster/mon/health_test.go
pkg/operator/ceph/cluster/mon/mon.go
pkg/operator/ceph/cluster/osd/health.go
pkg/operator/ceph/cluster/osd/health_test.go

Bug 1861021: ceph: removed individual force delete pod code for mons and osds #7266

---

pkg/operator/ceph/config/defaults.go
pkg/operator/ceph/version/version.go
pkg/operator/ceph/version/version_test.go

Bug 1934990: ceph: enable pg auto repair

---

pkg/daemon/ceph/osd/kms/envs.go
pkg/daemon/ceph/osd/kms/envs_test.go
pkg/operator/ceph/cluster/osd/spec.go

Bug 1941647: ceph: set default backend for vault and remove temp key

---

build/makelib/common.mk

Needed for https://github.com/openshift/release/pull/17923

build: try sha256sum if shasum is not present

---

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py

If there is no rgw endpoint provided, let's not try to create the user.
(cherry picked from commit 7439c08b314660115ecf7805368bc0be280a152d)
Resolves #
**Checklist:**

Bug 1974443: ceph: only require rgw-admin-ops user when an endpoint is provided

---

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml

This reverts commit 08bbdc7ccefe4572fa512c93d79d9f33d5c1ff93.
Signed-off-by: Mudit Agarwal <muagarwa@redhat.com>

Bug 1966139: revert the slow ops alert fix

---

pkg/operator/ceph/cluster/mgr/mgr.go
pkg/operator/ceph/cluster/mgr/mgr_test.go

The server_addr was previously set to the pod IP, but now the prometheus binding is expected to use the default binding to localhost. In new installs, the binding will be to localhost, but upgrades were retaining the setting to binding to the pod IP. Since the pod IP can change when the pod is restarted, the binding will fail. Thus, we unset the server_addr binding so the default localhost will be used.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1977379
**Checklist:**

Bug 1977379: Unset the prometheus server_addr before updating mgr

---

pkg/operator/ceph/controller/object_operations.go
pkg/operator/ceph/object/bucket/rgw-handlers.go
pkg/operator/ceph/object/health.go
pkg/operator/ceph/object/user/controller.go

Bug 1979293: ceph: always rehydrate the access and secret key

---

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules-external.yaml
cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml

Bug 2006323: [release 4.8] add namespace to ceph node down query

---

Documentation/ceph-cluster-crd.md
cluster/charts/rook-ceph/templates/resources.yaml
cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml
cluster/examples/kubernetes/ceph/cluster.yaml
cluster/examples/kubernetes/ceph/crds.yaml
pkg/apis/rook.io/v1/placement.go
pkg/apis/rook.io/v1/placement_test.go
pkg/apis/rook.io/v1/types.go
pkg/operator/ceph/cluster/osd/osd_test.go
pkg/operator/ceph/cluster/osd/provision_spec.go
pkg/operator/ceph/cluster/osd/spec.go
pkg/operator/ceph/cluster/osd/spec_test.go

look at individual commit.
Resolves #
**Checklist:**

Bug 1999158: option to merge placement and merge tolerations for OSDs/prepareOSD pods

---

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml

(cherry picked from commit 8950e78a4f9a15669fee50699647cc6249068322)
Resolves #
**Checklist:**

Bug 2005290: [release-4.9] add namespace to ceph queries

---

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml

(cherry picked from commit 8950e78a4f9a15669fee50699647cc6249068322)
Resolves #
**Checklist:**

Bug 2006323: [release-4.8] adding 'namespace' field to the needed ceph queries

---

pkg/operator/ceph/cluster/mgr/spec.go

The mgr init containers run a ceph command that may get stuck if the mon quorum is down. The liveness probe is not in effect during the init containers, thus the mgr pod may stay hung indefinitely when this happens. To ensure the mgr does not hang, we add a bash timeout to the ceph command so it will restart and try again in case mon quorum is restored.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2005515
**Checklist:**

Bug 2005515: Add timeout in mgr init container

---

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml

Bug 2006865: [release-4.9] All alert interval changes

---

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>
(cherry picked from commit 4b76eb89936051273b9705067844fda16ab29318)
Resolves #
**Checklist:**

Bug 1970354: ceph: handle empty ceph_version in ceph_mon_metadata

---

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml

(cherry picked from commit 5c34393eca1192f6a48d2818d9e19581465f290c)
Resolves #
**Checklist:**

Bug 1944513: [release-4.9] adding CephMonQuorumLost critical alert

---

OWNERS

The downstream bot requires the OWNERS file to control who can add lgtm or approve comments so the PR can be merged.
**Checklist:**

build: Add owners file for downstream integration

---

pkg/daemon/ceph/client/info.go
pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/cluster/cluster_external.go
pkg/operator/ceph/cluster/mon/config.go

Bug 2055715: various external mode enhancements

---

OWNERS

The downstream merges are streamlined with the OWNERS file for approvals and merges.
**Checklist:**

build: Add OWNERS file for downstream merges

---

pkg/apis/ceph.rook.io/v1/security.go
pkg/daemon/ceph/client/command.go
pkg/daemon/ceph/client/command_test.go
pkg/daemon/ceph/client/info.go
pkg/daemon/ceph/osd/daemon.go
pkg/daemon/ceph/osd/encryption.go
pkg/daemon/ceph/osd/encryption_test.go
pkg/daemon/ceph/osd/kms/envs.go
pkg/daemon/ceph/osd/kms/vault.go
pkg/daemon/ceph/osd/kms/volumes.go
pkg/daemon/ceph/osd/volume.go
pkg/operator/ceph/cluster/cluster.go
pkg/operator/ceph/cluster/mgr/spec.go
pkg/operator/ceph/cluster/mgr/spec_test.go
pkg/operator/ceph/cluster/osd/spec.go
pkg/operator/ceph/cluster/osd/spec_test.go
pkg/operator/ceph/object/admin.go
tests/manifests/test-cluster-on-pvc-encrypted.yaml
tests/scripts/validate_cluster.sh

Bug 2069722: ceph: add ceph cluster fsid to LUKS header

---

.github/workflows/canary-integration-test.yml
cluster/examples/kubernetes/ceph/create-external-cluster-resources.py

Currently if we run external-script and user already exit,
it fails to create/run same user again if the caps are upgraded,
so we need to check first if user is already present.
And for upgrading user we can do upgrade after this
PR: https://github.com/rook/rook/pull/9609 will get merged.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2048458
(cherry picked from commit 4f43f2d93e3da4b1e8a6d1dcb6318f64288b8bd2)
Resolves #
**Checklist:**

Bug 2052608: csi: make create and get process separate for csi users [4.8]

---

.github/workflows/canary-integration-test.yml
cluster/examples/kubernetes/ceph/create-external-cluster-resources.py

Currently if we run external-script and user already exit,
it fails to create/run same user again if the caps are upgraded,
so we need to check first if user is already present.
And for upgrading user we can do upgrade after this
PR: https://github.com/rook/rook/pull/9609 will get merged.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2048458
(cherry picked from commit 4f43f2d93e3da4b1e8a6d1dcb6318f64288b8bd2)
Resolves #
**Checklist:**

Bug 2052607: csi: make create and get process separate for csi users [4.9]

---

deploy/examples/create-external-cluster-resources.py

external-script: remove signature import
remove signature import as it is not required.
external-script: clean import section
import all the libraries at top
Resolves #
**Checklist:**

Bug 2089137: external-script: remove signature import 

---

deploy/examples/create-external-cluster-resources-tests.py
deploy/examples/create-external-cluster-resources.py

`black` is python formatter tool which
automatically formats python files without
manual changing. just run `black <python-file>`
and done.
(cherry picked from commit 00f21c08666d18cbb6e3210be39f4ef49e71ea67)
(cherry picked from commit 5ebc27c0a0f88a8ab5755211fbf4927219d82f07)
Resolves #
**Checklist:**

Bug 2095155: core: format python files using tool black

---

deploy/charts/rook-ceph/templates/clusterrole.yaml
deploy/examples/common.yaml

This rbac is required to fetch serviceaccount
token for vault tenant sa encryption type on k8s 1.24+.
refer: https://github.com/ceph/ceph-csi/pull/3174
(cherry picked from commit 623c5159d50c54d5fa1b52fe7c84a9198d3a3a1a)
(cherry picked from commit 54bf464c56a77e734a92c0db0574568cd6f5aeac)
Resolves #
**Checklist:**

Bug 2098536: csi: add token create rbac for rbd csi clusterrole

---

pkg/daemon/ceph/osd/daemon.go
pkg/operator/ceph/cluster/osd/spec.go

Bug 2097740: osd: add lvm flag for lvm osd activate 

---

OWNERS

Add downstream owners file for merges
**Checklist:**

ci: Add downstream owners file for merges

---

pkg/operator/ceph/csi/predicate.go
pkg/operator/ceph/csi/predicate_test.go

findCSIChange will work only for single line values/configuration in the configmap. If the value is multiline, the regex will not
be able to indentify the change because of this one, no configurations will be applied to the csi driver. Removing this check so that if there is any update on the configmap, we will reconcile the csi driver.
Note:- This might look heavy, but updating the config map is not a frequent event.
(cherry picked from commit 5b843a17a1704f771ed3ab3a4e19328a555c7029)
Resolves #
**Checklist:**

BUG 2122215: csi: remove findCSIChange from predicate

---

pkg/operator/ceph/csi/predicate.go
pkg/operator/ceph/csi/predicate_test.go

findCSIChange will work only for single line values/configuration in the configmap; If the value is multiline, the regex will not
be able to indentify the change because of this one no configurations will be applied to the csi driver. Removing this check so that if there is any update on the configmap, we will reconcile the csi driver.
Note: This might look heavy, but updating config map is not a frequent event.
(cherry picked from commit 5b843a17a1704f771ed3ab3a4e19328a555c7029)
Resolves #
**Checklist:**

BUG 2125148: csi: remove findCSIChange from predicate

---

.github/workflows/canary-integration-test.yml
pkg/daemon/ceph/client/command.go
pkg/daemon/ceph/client/command_test.go
pkg/operator/ceph/nfs/controller_test.go
pkg/operator/ceph/nfs/nfs.go
tests/scripts/github-action-helper.sh

Backport:
- https://github.com/rook/rook/pull/11041
- https://github.com/rook/rook/pull/11116
Resolves #
**Checklist:**

Bug 2133550: fix NFS when multus is enabled

---

pkg/daemon/ceph/osd/remove.go

Currently, osdSafeToDestroy check is done before marking osd out which prevents ceph from rebalancing. With this changes, we are moving check for osdSafeToDestroy after osd is marked out.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2128966
**Checklist:**

Bug 2128966: osd: osdSafeToDestroy check should be after osd out

---

deploy/charts/rook-ceph/templates/resources.yaml
deploy/examples/crds.yaml
pkg/apis/ceph.rook.io/v1/types.go

Signed-off-by: Nitin Goyal <nigoyal@redhat.com>
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2141947
**Checklist:**

Bug 2141947: object: mark endpoint as a optional field

---

deploy/examples/operator-openshift.yaml
pkg/operator/ceph/controller.go
pkg/operator/ceph/webhook-config.go
pkg/operator/ceph/webhook.go

Bug 2152839: disable webhook

---

Makefile
go.mod
go.sum
pkg/operator/ceph/cluster/mgr/mgr.go
pkg/operator/ceph/cluster/mgr/mgr_test.go
pkg/operator/k8sutil/deployment.go
pkg/operator/k8sutil/pod.go

Sync from release-1.11 to downstream 4.13
**Checklist:**

Sync from release-1.11 to downstream 4.13

---

pkg/operator/ceph/cluster/nodedaemon/exporter.go
pkg/operator/ceph/cluster/nodedaemon/exporter_test.go

Signed-off-by: Avan Thakkar athakkar@redhat.com
Resolves #
**Checklist:**

Bug 2173934: Disable exporter for downstream 4.13

---

OWNERS

Add owners file for merge bot for release-4.13 branch
**Checklist:**

ci: Add owners file for merge bot for release-4.13 branch

---

deploy/examples/create-external-cluster-resources.py

(cherry picked from commit def9fd9056013be53dedd4c38ead34706aa49521) (cherry picked from commit ed30d06203bcdc41e9dca498e7ee91eaf49b27e2)
Resolves #
**Checklist:**

Bug 2089137: rgw: dont do rgw validation if python version < 3

---

.github/workflows/canary-integration-test.yml
.github/workflows/integration-test-helm-suite.yaml
.github/workflows/integration-test-mgr-suite.yaml
.github/workflows/integration-test-multi-cluster-suite.yaml
.github/workflows/integration-test-object-suite.yaml
.github/workflows/integration-test-smoke-suite.yaml
.github/workflows/integration-test-upgrade-suite.yaml
.github/workflows/integration-tests-on-release.yaml

ci: stop running ci concurrently when pr is fresh

---

.github/workflows/build.yml
.github/workflows/canary-integration-test.yml
.github/workflows/codegen.yml
.github/workflows/codespell.yaml
.github/workflows/commitlint.yml
.github/workflows/crds-gen.yml
.github/workflows/create-tag.yaml
.github/workflows/daily-nightly-jobs.yml
.github/workflows/golangci-lint.yaml
.github/workflows/integration-test-helm-suite.yaml
.github/workflows/integration-test-mgr-suite.yaml
.github/workflows/integration-test-multi-cluster-suite.yaml
.github/workflows/integration-test-object-suite.yaml
.github/workflows/integration-test-smoke-suite.yaml
.github/workflows/integration-test-upgrade-suite.yaml
.github/workflows/integration-tests-on-release.yaml
.github/workflows/mod-check.yml
.github/workflows/push-build.yaml
.github/workflows/rbac-gen.yaml
.github/workflows/stale.yaml
.github/workflows/unit-test.yml
pkg/daemon/ceph/client/config.go
pkg/daemon/ceph/osd/kms/vault.go
pkg/daemon/ceph/util/util.go
pkg/operator/ceph/cluster/osd/envs_test.go
pkg/operator/ceph/object/controller_test.go
pkg/operator/discover/discover.go
pkg/operator/test/client.go
pkg/util/file.go
tests/scripts/create-bluestore-partitions.sh

(cherry picked from commit aec9ac30601490a9a621228d0b7d5fe387aff469) (cherry picked from commit a8b58879baa7833542497073025d1b89d6f2663c)
Resolves #
**Checklist:**

ci: ubuntu 18.04 is deprecated upgrade to ubuntu 22.04

---

.docs/macros/includes/main.py
pkg/operator/ceph/cluster/crash/crash.go
pkg/operator/ceph/cluster/crash/crash_test.go
pkg/operator/ceph/controller/spec.go

Bug 2180728: security: run the crash collector as ceph user

---

.github/workflows/canary-integration-test.yml
Documentation/CRDs/Cluster/external-cluster.md
deploy/examples/create-external-cluster-resources.py

1) The function is used for rbd so it should be name to validate_rbd_metadata_ec_pool_name
2) Add support for realm, zone and zonegroup
Resolves #
**Checklist:**

Bug 2167516: external: add support for multisite in external cluster script

---

.github/workflows/canary-integration-test.yml
Documentation/CRDs/Cluster/external-cluster.md
deploy/examples/create-external-cluster-resources.py

Bug 2188379: Backport 4.12 multisite support

---

pkg/operator/ceph/cluster/nodedaemon/exporter.go
pkg/operator/ceph/cluster/nodedaemon/exporter_test.go
pkg/operator/ceph/cluster/nodedaemon/reconcile.go

Signed-off-by: avanthakkar <avanjohn@gmail.com>
Create the exporter service only if exporter pods are created.
Resolves #
**Checklist:**

 Bug 2187952: Disable exporter service for downstream 4.13

---

pkg/operator/ceph/config/monstore.go

if the configuration is already set in the ceph database, using `ceph config assimilate-conf` will add the key and value if its missing but it wont update the value if the key is already present, To fix this problem we can remove the key and add all the configurations once again.
(cherry picked from commit 1139cefc94fa7a646f14fbbcf9f43468cdb1693b)
Resolves #
**Checklist:**

BUG 2192088: unset all the encryption configuration before setting

---

OWNERS

The OWNERS file is needed to work with the bot used by the downstream integration for approvals and lgtm.
**Checklist:**

ci: Add owners file to work with bot

---

Documentation/CRDs/Cluster/ceph-cluster-crd.md
Documentation/Upgrade/rook-upgrade.md

PR containing the latest commits from release-1.13 branch

Syncing latest changes from release-1.13 for rook

---

pkg/operator/ceph/controller/predicate.go

The exporter pod is ephemeral and frequently being deleted and re-created when ceph daemons are created. Therefore, we need to skip reconciling based on the deletion
of the exporter deployment.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2260279
**Checklist:**

Bug 2260279: exporter: Skip reconcile on exporter deletion

---

deploy/examples/create-external-cluster-resources.py
pkg/operator/ceph/object/objectstore.go
tests/scripts/pythonwebserver/server.py

there was a bug in the code which doesn't
sets realm if we try to get the zonegoup
so because of that 1.12 this backport pr
for original change was not working
(cherry picked from commit a9c77280c6cde03cf129afc988711ad7135fe98c)
Resolves #
**Checklist:**

Bug 2262052: object: fix the default multisite zonegroup creation

---

build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
deploy/examples/operator-openshift.yaml

Update csiadons/k8s-sidecar image to 0.8.0 in csv
**Checklist:**

csi: update csiaddons/k8s-sidecar image

---

pkg/daemon/ceph/client/mirror.go
pkg/daemon/ceph/client/mirror_test.go
pkg/daemon/ceph/client/pool.go
pkg/operator/ceph/object/controller_test.go
pkg/operator/ceph/pool/controller.go
pkg/operator/ceph/pool/controller_test.go

PR containing the latest commits from upstream master branch

Syncing latest changes from upstream master for rook

---

build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
deploy/examples/operator-openshift.yaml

Update csi holder pod key to `CSI_DISABLE_HOLDER_PODS`
**Checklist:**

csi: update holder pod key

---

pkg/operator/ceph/cluster/mon/spec.go
pkg/operator/ceph/cluster/mon/spec_test.go

The mon was listening on both v1 and v2 ports inside the daemon even though the service endpoint would not redirect any traffic to the v1 port. When msgr2 is required, disable the mon from listening on the v1 port for reduced security footprint.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2262134
**Checklist:**

Bug 2262134: mon: Disable v1 port if msgr2 is required

---

pkg/operator/ceph/csi/spec.go

the templateParam need to be updated
with the right values before we are
rendering the template.
(cherry picked from commit cb87c3a845f042378351dcc486a86801876ee398)
**Checklist:**

csi: fix template render in logRotation

---

build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
deploy/olm/assemble/metadata-common.yaml

update csv capabilities from `Basic Install` to `Seamless Upgrade`
**Checklist:**

csv: update capabilities to seamless upgrade

---

build/csv/ceph/ceph.rook.io_cephblockpoolradosnamespaces.yaml
build/csv/ceph/ceph.rook.io_cephblockpools.yaml
build/csv/ceph/ceph.rook.io_cephbucketnotifications.yaml
build/csv/ceph/ceph.rook.io_cephbuckettopics.yaml
build/csv/ceph/ceph.rook.io_cephclients.yaml
build/csv/ceph/ceph.rook.io_cephclusters.yaml
build/csv/ceph/ceph.rook.io_cephcosidrivers.yaml
build/csv/ceph/ceph.rook.io_cephfilesystemmirrors.yaml
build/csv/ceph/ceph.rook.io_cephfilesystems.yaml
build/csv/ceph/ceph.rook.io_cephfilesystemsubvolumegroups.yaml
build/csv/ceph/ceph.rook.io_cephnfses.yaml
build/csv/ceph/ceph.rook.io_cephobjectrealms.yaml
build/csv/ceph/ceph.rook.io_cephobjectstores.yaml
build/csv/ceph/ceph.rook.io_cephobjectstoreusers.yaml
build/csv/ceph/ceph.rook.io_cephobjectzonegroups.yaml
build/csv/ceph/ceph.rook.io_cephobjectzones.yaml
build/csv/ceph/ceph.rook.io_cephrbdmirrors.yaml
build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml

due to some merge conflict during manual
sync raising this pr to add the csv.
**Checklist:**

csv: update the csv in release-4.17 branch

---

pkg/operator/ceph/csi/controller.go
pkg/operator/ceph/csi/operator_config.go
pkg/operator/ceph/csi/spec.go

to keep it simple we'll not delete the csi-operator resources we'll only document this for users who want to switch to csi-drivers. Anyways by next release we'll only support csi-operator only.
(cherry picked from commit a16ad75c929cce19ab29cda2fabea80fd61eb40f) (cherry picked from commit 3eaf33b0777cffb9dc140338fca0faa45a155760)
**Checklist:**

Bug 2308304: csi: stop deleting csi-operator resources

---

Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
Documentation/Troubleshooting/ceph-csi-common-issues.md
pkg/operator/ceph/cluster/watcher.go

Disabling the RBD and CephFS fencing
in Rook for now as its having bugs where
Rook is blocklisting wrong IP address
due to timing issues.
(cherry picked from commit 1d1ed5e9629b3c7acccfd63627aaa839b1b2fefa) (cherry picked from commit 34f81ec820e1b6794d664bddf628754e1c99ccce) (cherry picked from commit fc94e11155569d4aa4f721320c8cfb965fe7a9ad)
**Checklist:**

DFBUGS-979: csi: disable fencing in Rook

---

Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
Documentation/Troubleshooting/ceph-csi-common-issues.md
pkg/operator/ceph/cluster/watcher.go

Disabling the RBD and CephFS fencing
in Rook for now as its having bugs where
Rook is blocklisting wrong IP address
due to timing issues.
(cherry picked from commit 1d1ed5e9629b3c7acccfd63627aaa839b1b2fefa) (cherry picked from commit 34f81ec820e1b6794d664bddf628754e1c99ccce) (cherry picked from commit fc94e11155569d4aa4f721320c8cfb965fe7a9ad)
**Checklist:**

DFBUGS-980: csi: disable fencing in Rook

---

Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
Documentation/Troubleshooting/ceph-csi-common-issues.md
pkg/operator/ceph/cluster/watcher.go

This reverts commit 4e761bd53c25e86690088a8bfb41910b5624e4da.
**Checklist:**

DFBUGS-979: Revert "csi: disable fencing in Rook"

---

Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
Documentation/Troubleshooting/ceph-csi-common-issues.md
pkg/operator/ceph/cluster/watcher.go

This reverts commit d4f86a0881c6bc32cadeeb8f31d6cb11001e48ac.
**Checklist:**

DFBUGS-980: Revert "csi: disable fencing in Rook"

---

Documentation/Helm-Charts/operator-chart.md
Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
deploy/charts/rook-ceph/values.yaml
deploy/examples/images.txt
deploy/examples/operator-openshift.yaml
deploy/examples/operator.yaml
pkg/operator/ceph/csi/csi.go
pkg/operator/ceph/csi/spec.go
tests/framework/utils/snapshot.go

This is backport of https://github.com/rook/rook/pull/15196 to 4.18 
Signed-off-by: Steven Kreitzer <skre@skre.me>
(cherry picked from commit 463d9fb420d224bf5a305adf3313e9db76e51d34)
**Checklist:**

DFBUGS-1028: csi-snapshotter flag typo; upgrade csi-snapshotter

---

Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
Documentation/Troubleshooting/ceph-csi-common-issues.md
pkg/operator/ceph/cluster/watcher.go

This reverts commit 4d38c60a1f7e44ec3706c917d1317db0a7d8d6f1.
**Checklist:**

DFBUGS-978: Revert "csi: disable fencing in Rook"

---

Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
Documentation/Troubleshooting/ceph-csi-common-issues.md
pkg/operator/ceph/cluster/watcher.go

This reverts commit 19f81bf1f0062f6f17acb303bea9f726c3361699.
**Checklist:**

DFBUGS-978: Reapply "csi: disable fencing in Rook"

---

Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
Documentation/Troubleshooting/ceph-csi-common-issues.md
pkg/operator/ceph/cluster/watcher.go

This reverts commit 9ac92c302e507597c50fa5a574e1bc677c38ec3e.
**Checklist:**

DFBUGS-979: Reapply "csi: disable fencing in Rook"

---

Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
Documentation/Troubleshooting/ceph-csi-common-issues.md
pkg/operator/ceph/cluster/watcher.go

This reverts commit a355503de422eede2b6ee8c30820b0030ed58393.
**Checklist:**

DFBUGS-980: Reapply "csi: disable fencing in Rook"

---

go.mod
go.sum

jwt-go allows excessive memory allocation during header parsing
https://bugzilla.redhat.com/show_bug.cgi?id=2354195
golang-jwt is a Go implementation of JSON Web Tokens. Prior to
5.2.2 and 4.5.2, the function parse.ParseUnverified splits (via a call to strings.Split) its argument (which is untrusted data) on periods. As a result, in the face of a malicious request whose Authorization header consists of Bearer followed by many period characters, a call to that function incurs allocations to the tune of O bytes (where n stands for the length of the function's argument), with a constant factor of about 16. This issue is fixed in 5.2.2 and 4.5.2.
(cherry picked from commit ef88e12f457d0d0af31d0bf6027bcb5a0451be71)
**Checklist:**

DFBUGS-1911: [release 4.17] core: CVE-2025-30204: rook-ceph-operator-container: jwt-go allows excessive memory allocation during header parsing 

---

go.mod
go.sum
pkg/apis/go.mod
pkg/apis/go.sum

this commit update oauth2 to latest version 0.29
to include some CVE fixes.
**Checklist:**

DFBUGS-2015: build: update oauth2 pkg to latest version

---

pkg/operator/ceph/file/subvolumegroup/controller.go
pkg/operator/ceph/pool/radosnamespace/controller.go

DFBUGS-2309: Remove duplicate svg rns cr

---

pkg/operator/ceph/object/user/controller.go

If rgw-admin-ops-user access key becomes invalid, then delete the admin user and restart the rook operator. This is a temporary solution for the InvalidAccessKeyID error. Undo this change once https://bugzilla.redhat.com/show_bug.cgi?id=2373031 is fixed.
**Testing**: 
To test this, I made some code changes to simulate invalid key for a particular user `my-store-2`.  (see log snippet below). Was able to catch the `InvalidAccessKeyId` error and then restart the operator `opcontroller.ReloadManager()` . This works. 
```
2025-07-03 15:55:30.099819 I | ceph-object-store-user-controller: -----testing-----
2025-07-03 16:41:17.413560 I | ceph-object-store-user-controller: access key  - "WU0X8Z808YGGFQVCVCAX"
2025-07-03 16:41:17.413735 I | ceph-object-store-user-controller: secret key  - …
```

DFBUGS-2929:  core: delete rgw admin user with invalid key
