Documentation/ceph-upgrade.md, cluster/charts/rook-ceph/templates/clusterrole.yaml, cluster/charts/rook-ceph/values.yaml, cluster/examples/kubernetes/ceph/common.yaml, cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml, cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml, cluster/examples/kubernetes/ceph/operator.yaml, pkg/operator/ceph/csi/spec.go, tests/framework/installer/ceph_manifests.go
This will be helpful to list the CSI drivers
deployed in the kubernetes cluster. if we have
N number of CSI drivers deployed in the cluster,
the user can query kubectl get csidriver and get
the list of registered CSI drivers and it requires
kube 1.14+
This removes the deployment of Attacher sidecar container,
as we are setting the attacher required to false during
the CSIDriver object creation.
(cherry picked from commit 9b368ef15c421c96bc54cc4a53300afac7ddb104)
Resolves #
**Checklist:**
=> CSI: Create CSIDriver Object

Documentation/ceph-upgrade.md, cluster/charts/rook-ceph/values.yaml, cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml, cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml, cluster/examples/kubernetes/ceph/operator.yaml, pkg/operator/ceph/csi/spec.go
A recent PR #4172 added the ability for rook to create
the CSIDriver object on a kubernetes cluster. The change also
made it so that attachRequired value in the ceph CSI drivers
were set to false.
This leads to the entire attach skipping the AD controller
that deals with RWO attachment enforcement. Thus, if a
CephFS volume is marked RWO, 2 pods on different hosts can
end up mounting the same and consuming it at the same time.
Further for RBD, currently the image watchers are the only ones
that prevent a double mount of an image, other than the AD controller
enforcement of single attach for RWO RBD PVs. This has proven
not to be reliable in the face of MON failures, as the watcher
information is lost, and a second mount is allowed.
Thus, we need to bring back the attach requirement to …
=> CSI: Make attach mandatory in ceph CSIDriver object

Documentation/helm-operator.md, cluster/charts/rook-ceph/templates/deployment.yaml, cluster/charts/rook-ceph/values.yaml, cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml, cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-sts.yaml, cluster/examples/kubernetes/ceph/operator-openshift.yaml, cluster/examples/kubernetes/ceph/operator.yaml, pkg/operator/ceph/csi/spec.go
we need to set a ENV `CSI_RBD_ENABLE_SNAPSHOTTER`
variable to "false" in operator template to disable
deployment of snapshotter sidecar in ceph-csi rbd
provisioner.
Fixes: #4401
(cherry picked from commit cc418bce3b41a9be95d3f4961b695c4a5fd90faf)
Resolves #
**Checklist:**
=> CSI: Ability to disable snapshotter from ceph-csi rbd

pkg/operator/ceph/cluster/mgr/mgr.go, pkg/operator/ceph/cluster/osd/osd.go
During an orchestration if there were failures to update any OSD deployment,
the orchestration would fail and continue trying again. If the OSD(s)
continued failing, the operator would be stuck in a loop and never
respond to other CR updates.
Now the operator will log the OSD errors, if any, and complete the
orchestration. We will rely on K8s to continue to attempt to start
the OSD pods instead of the operator being stuck in the loop.
(cherry picked from commit add3129c12f1c558fda587e75b57e4172c26875d)
(cherry picked from commit 9d237d5f564c7e0e7dec29771c56ead088603058)
**Checklist:**
=> ceph: continue orchestration on osd update errors

pkg/operator/ceph/object/spec.go
to the RGWs swift objectstorage healthcheck api url [1]
which resolves an OCS false-positive CLBO of the RGW pod.
[1] https://docs.openstack.org/swift/latest/middleware.html#healthcheck
Signed-off-by: Mark Kogan <mkogan@redhat.com>
(cherry picked from commit 3c807688fe6a5fe5ce342221a77aac9a955bfe98)
For https://bugzilla.redhat.com/show_bug.cgi?id=1768874
=> ceph: rgw change the liveness probe url

pkg/operator/ceph/cluster/cluster.go, pkg/operator/ceph/cluster/cluster_test.go, pkg/operator/ceph/cluster/controller.go
The isUpgrade flag was being set every time the operator
was started. This caused the upgrade checks to be run every
time the operator restarted. Thus, if any mons were down,
you likely would get stuck on the upgrade checks since another
mon could not be stopped. We need to rely on the upgrade being
detected either by a different image name from the cluster CR
update, or from different versions of the daemons running
in case the operator was restarted in the middle of an upgrade.
(cherry picked from commit b79c223986cd94899be273cb7a66de1a5e7518a2)
Resolves #
**Checklist:**
=> ceph: only set isUpgrade when the image changes

Documentation/ceph-cluster-crd.md, cluster/charts/rook-ceph/templates/resources.yaml, cluster/examples/kubernetes/ceph/cluster-on-pvc.yaml, cluster/examples/kubernetes/ceph/cluster-test.yaml, cluster/examples/kubernetes/ceph/cluster.yaml, cluster/examples/kubernetes/ceph/common.yaml, pkg/apis/ceph.rook.io/v1/types.go, pkg/operator/ceph/cluster/cluster.go, pkg/operator/ceph/cluster/mgr/mgr.go, pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/cluster/mon/spec.go, pkg/operator/ceph/cluster/osd/osd.go, pkg/operator/ceph/cluster/osd/osd_test.go, pkg/operator/ceph/cluster/osd/spec_test.go, pkg/operator/ceph/cluster/osd/status_test.go, pkg/operator/ceph/cluster/rbd/mirror.go, pkg/operator/ceph/file/mds/mds.go, pkg/operator/ceph/nfs/nfs.go, pkg/operator/ceph/object/rgw.go, pkg/operator/k8sutil/deployment.go, pkg/operator/k8sutil/test/deployment.go
A new CRD option `continueUpgradeAfterChecksEvenIfNotHealthy` is added.
When upgrading, Rook goes OSD by OSD and then waits for PGs to be clean
before proceeding to the next OSD. Currently, Rook waits for 5 hours but
there might be circumstances where PGs need more time to settle.
Thus setting `continueUpgradeAfterChecksEvenIfNotHealthy` to true will
pursue the upgrade process, even if PGs are not 100% active+clean.
For OCS 4.2 we will force the setting to true for continuing
the upgrade even if the cluster is unhealthy after the
health checks timeout.
https://bugzilla.redhat.com/show_bug.cgi?id=1786029
**Checklist:**
=> Continue with ceph upgrades even if the cluster is unhealthy

cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml, cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-sts.yaml, cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin.yaml, cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml, cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-sts.yaml, cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin.yaml
Backport the CSI driver fix to support upgrading from OCP 4.2 to OCP 4.3.
Marking as DNM until it's approved for downstream.
https://bugzilla.redhat.com/show_bug.cgi?id=1788930
**Checklist:**
=> CSI driver fix to support upgrades from OCP 4.2 to 4.3

cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml, cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml, pkg/operator/ceph/csi/spec.go
Downstream we want to enable the Ceph-CSI 2.0 driver by default. This PR reverts the commits that had made this not be the default upstream in the release-1.2 branch. This is done to simplify keeping the `release-1.2` and `ocs-4.3` branches in sync.
**Checklist:**
=> Enable Ceph-CSI 2.0 by default

pkg/apis/rook.io/v1alpha2/placement.go, pkg/apis/rook.io/v1alpha2/placement_test.go
The default pod anti-affinity for the mons that rook adds
automatically intended to be appended to any anti-affinity that
is specified in the cluster CR.
There is a bug in the ApplyToPodSpec() method that has long existed.
The issue is that when antiaffinity is appended, it will append not only
to the pod spec, but will modify the original placement spec. Thus, each
mon that is started will have one more antiaffinity clause than the previous mon.
This condition is rarely hit or noticed because it commonly is only hit
in the canary pods. Since these pods are immediately deleted,
there are no side effects of the duplicate affinity clauses. The place
where it becomes an issue is when the mons are backed by a PVC. In this case,
the mons do not have node …
=> Avoid duplication of mon anti-affinity and unnecessary mon restarts

images/ceph/toolbox.sh
The toolbox script is used for configuring the toolbox. If the mons are to fail over while the toolbox is running, the new list of mons needs to be updated. However, if run temporarily as a one-time job, the script only needs to initialize the ceph.conf and then exit.
Related to BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1821219
**Checklist:**
=> Bug: 1821219 Allow toolbox script to skip watching mons

pkg/operator/ceph/cluster/controller.go, pkg/operator/ceph/cluster/osd/health.go, pkg/operator/ceph/cluster/osd/health_test.go
If the OSD pod is portable and is on a failed node, the node will be stuck indefinitely in the terminating state. The pod can be force deleted in this scenario in order to allow the underlying volume to be detached and then mounted on another node.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1830015
**Checklist:**
=> 1830015: Restart portable osd pod if stuck

pkg/daemon/ceph/osd/daemon.go
If we fail to release an LVM device, we should not fail the deployment.
We just print the error and let the backend handle the rest. Some
CSI backend will force detach the device anyway.
This prevents the deployment to get stuck in terminating.
(cherry picked from commit d36a2a7ba70a2436d82708490fcf34cf8030bf5d)
Resolves #
**Checklist:**
=> ceph: do not fail on deactivate

pkg/operator/ceph/cluster/osd/osd.go, pkg/operator/ceph/cluster/osd/osd_test.go, pkg/operator/ceph/cluster/osd/spec.go, pkg/operator/k8sutil/deployment.go
An OSD on a PVC when portable=false is assigned to a node with a node selector. The same node assignment is expected for the lifetime of the cluster. On subsequent reconciles, the operator was looking up the node assignment from the nodeName on the pod spec, which is not set if the pod is down. The operator needs to retrieve the assignment from the deployment spec node selector.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1833082
**Checklist:**
=> Bug 1833082: OSD on PVC node selector needs to be the deployment node selector

pkg/operator/ceph/cluster/osd/health.go, pkg/operator/ceph/cluster/osd/health_test.go
When an OSD pod is stuck in terminating state, there is no need to check if the OSD is marked as out before force deleting. As long as the osd is down we will force delete the pod.
(cherry picked from commit 3c6bae56b70df9ef440936dde253f379f9ae2ea5)
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1830015
**Checklist:**
=> Bug 1830015: delete terminating osd pods even if not out

pkg/daemon/ceph/osd/daemon.go
The activation of the lvs for OSDs had an invalid argument to vgchange. The invalid argument is now reverted to enable the OSDs in this scenario again.
(cherry picked from commit af54349a5ef245bdf54bb85dd818be12a4faf426)
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1833038
**Checklist:**
=> Bug 1833038: Remove invalid verbose params from lv activate

pkg/daemon/ceph/osd/daemon.go
The verbose args recently added are causing the lv release to fail and then causing the OSD to intermittently fail starting.
(cherry picked from commit 9e78faaa2cccbd68b3c46669534a3b7258b49bf4)
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1838787
**Checklist:**
=> Bug 1838787: Revert verbose args for the LV release

pkg/operator/ceph/cluster/controller.go, pkg/operator/ceph/cluster/mon/health.go, pkg/operator/ceph/cluster/mon/health_test.go, pkg/operator/ceph/cluster/osd/health.go, pkg/operator/ceph/cluster/osd/health_test.go, pkg/operator/k8sutil/pod.go
Backport changes to release-4.4 (backport of https://github.com/rook/rook/pull/5569) to improve the node failure handling.
- The monitoring goroutines that check for mon and osd health, the ceph cluster status, and the bucket provisioner should be started immediately with the first reconcile after an operator restart instead of waiting until the first reconcile is completed. This way the cluster health will be monitored even during the first reconcile.
- During the mon health check, if the mon is stuck terminating on a bad node, force delete the mon pod to allow it to start on another node if possible
- Reduce the OSD health check interval from 300s to 60s for faster response time in the event of node failure
**Which issue is resolved by this Pull …
=> Bug 1848184: Handle node failure more gracefully (bp to release-4.4)

pkg/daemon/ceph/client/command.go, pkg/daemon/ceph/client/pool.go, pkg/daemon/ceph/client/pool_test.go, pkg/operator/ceph/config/monstore.go, pkg/operator/ceph/object/objectstore.go
The object store was not getting created because of the PG limit. The rook operator log shows:
2020-06-26 10:30:39.906986 I | exec: Running command: ceph osd pool create ocs-storagecluster-cephobjectstore.rgw.buckets.index 0 replicated ocs-storagecluster-cephobjectstore.rgw.buckets.index --connect-timeout=15 --cluster=openshift-storage --conf=/var/lib/rook/openshift-storage/openshift-storage.config --keyring=/var/lib/rook/openshift-storage/client.admin.keyring --format json --out-file /tmp/875991478
2020-06-26 10:30:40.952434 I | exec: Error ERANGE:  pg_num 32 size 3 would mean 768 total pgs, which exceeds max 750 (mon_max_pg_per_osd 250 * num_in_osds 3)
2020-06-26 10:30:40.952568 E | op-object: failed to create or update object store …
=> Bug 1851311: Set the minimum rgw PGs for the metadata pools to the smaller default

pkg/operator/ceph/cluster/controller.go, pkg/operator/ceph/cluster/mon/mon.go
Two changes related to improving 1848184:
1. Force delete stuck mons in every reconcile: The stuck mons were only being force deleted in the mon health checker. After an operator restart, the health check may not be executed for 20 minutes until after the timeout during the main reconcile which is holding onto a lock for mon reconcile. Now the stuck mon will be deleted during the reconcile as well.
1. Delay watching for CRDs until first reconcile completes: The CRs cannot be reconciled until the operator first generates the ceph config, which doesn't happen until after the ceph image version is detected. This was causing the CR watches to fail since they were starting too soon. Now the CR watches will not start until after the first reconcile completes. …
=> Bug 1848184: Force delete mons in every reconcile and delay watching CRDs for first reconcile

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Backport PR of https://github.com/rook/rook/pull/5685 -> https://github.com/rook/rook/pull/5700
Added warning and critical alerts for all the PVC's created by rook-ceph provisioners. This is required to notify an admin timely to check on PVC utilization and take a required action to prevent workloads from failing.
Closes: BZ1849723
(cherry picked from commit 624ca40817026b26c274069ea78aae1a16589fcf)
Resolves #
**Checklist:**
[skip ci]
=> Bug 1849723: ceph: added PVC utilization alerts

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
This reverts commit 019cb74d79a31bf786a63fcc5d8a8d765d4964c5.
Reverts PR #76. 
This patch was only approved for 4.4.2.
Have to revet for a 4.4.1 respin.
Signed-off-by: Michael Adam <obnox@redhat.com>
=> Bug 1849723: Revert "ceph: added PVC utilization alerts"

pkg/operator/ceph/cluster/osd/spec.go, pkg/operator/ceph/config/defaults.go, pkg/operator/ceph/controller/spec.go
The OSD daemon has been missing critical flags for logging to stderr where k8s can capture the logs. Without the --log-to-stderr=true, all the OSD logging was essentially lost until now.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1852852
**Checklist:**
=> Bug 1852852: Capture logging from the osd daemon

pkg/daemon/ceph/client/upgrade.go
The wait to continue after an OSD daemon upgrade is currently 10 minutes for the PGs to be healthy. This change reduced that retry timeout to one minute.
This is a minimal fix for OCS 4.5. A more completely configurable wait time will come in 4.6 with https://github.com/rook/rook/issues/5790.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1840729
**Checklist:**
=> Bug 1840729: Reduce osd upgrade timeout from 10 minutes to one minute

pkg/operator/ceph/object/user/controller.go
The object user controller was intending to wait for rgw pods to be running before creating a user, however, after querying for the pods it didn't check if any pods were actually running. Creating the user before the object store was running causes the default rgw pools to potentially be created by ceph instead of allowing Rook to create the pools with the expected settings in the CR. Now we wait properly for the rgw to start before creating the object users.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1852983
**Checklist:**
=> Bug 1852983: Require rgw pods to be running to create object users

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
If there is a typo in the rgw endpoint, then the user will be notified
that the gateway is not accessible or does not return the 200 HTTP code.
(cherry picked from commit 83e1ff102db55818ad4f07bad0c6e9650906812f)
=> Bug 1850704: ceph: add http dial to verify external endpoint

pkg/operator/ceph/object/user/controller.go
This reverts commit 6f257d8a8f367735d28e67ff08440b670e5ca686.
This was merged too early.
Branch is still locked down for 4.4.2
Will have to re-add after opening for 4.4.3.
Signed-off-by: Michael Adam <obnox@redhat.com>
Revert PR #81
=> Bug 1852983: Revert "ceph: require rgw pods to be running to create object users"

pkg/daemon/ceph/client/status.go, pkg/operator/ceph/cluster/cephstatus.go
If the healthcheck goroutine cannot check for the ceph status/times out
(if the mons are not in quorum) this should still be reflected in the
CRD status field.
Example:
```
status:
ceph:
details:
error:
message: 'failed to get status. . timed out: exit status 1'
severity: Urgent
health: HEALTH_ERR
lastChanged: "2020-07-20T14:11:05Z"
lastChecked: "2020-07-20T14:11:05Z"
previousHealth: HEALTH_WARN
```
=> Bug 1856414: ceph: report error on timeout

pkg/operator/ceph/cluster/mon/health.go
At startup there is a race condition between the goroutine checking
for mon health and the first reconcile of the mons. There is a lock
that ensures only one of them will check the mon health at a time.
The issue is that if the wrong one gets there first, it will not
have the desired mon count initialized from the cluster CR as expected
and the healther checker will use a desired mon count of 0.
The desired count of 0 leads the health checker to remove
a mon since there are extra mons. Only one mon is allowed
to be removed at a time, and adjusting to fewer than two mons is
disallowed once there are at least two mons.
After the health checker is completed, the main reconcile of the mons
will proceed with the correct desired mon count of 3 and attempt
to …
=> Bug 1859691: Skip first mon health check at startup if not initialized

pkg/operator/ceph/cluster/mon/health.go
At startup there is a race condition between the goroutine checking
for mon health and the first reconcile of the mons. There is a lock
that ensures only one of them will check the mon health at a time.
The issue is that if the wrong one gets there first, it will not
have the desired mon count initialized from the cluster CR as expected
and the healther checker will use a desired mon count of 0.
The desired count of 0 leads the health checker to remove
a mon since there are extra mons. Only one mon is allowed
to be removed at a time, and adjusting to fewer than two mons is
disallowed once there are at least two mons.
After the health checker is completed, the main reconcile of the mons
will proceed with the correct desired mon count of 3 and attempt
to …
=> Bug 1859033: skip first mon health check at startup

pkg/operator/ceph/cluster/cephstatus.go, pkg/operator/ceph/cluster/cephstatus_test.go, pkg/operator/ceph/cluster/controller.go
Instead of setting the Phase of the CR once the reconcile is done, let's
actually set in from the healthcheck so it is more accurate.
Closes: https://github.com/rook/rook/issues/5249
(cherry picked from commit 65ddb49898ca19a683af349b196813134f4e44c7)
=> Bug 1851009: ceph: let the healthcheck set the status phase

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Some clusters do not have rgws deployed so let's make it optional.
(cherry picked from commit faad0a45acaed4679d96fcd30e39de21a7624f27)
=> Bug 1857304: ceph: make rgw option on external script

pkg/operator/ceph/csi/csi.go, pkg/operator/ceph/csi/spec.go
If the AllowUnsupported flag is set to true we should
not check the csi version as it will be kind of no-op
as even incase of failure we continue. if we disable
the version check in this case,the deployment will
be little faster as we dont wait for version check
to complete to start CSI pods.
(cherry picked from commit 51d3a52c8078f8c621edaf11e7d0558f0903f4f4)
=> Bug 1859730: ceph: skip csi version detect if allowunsupported is set

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
As 'rgw_endpoint' argument itself is optional, making it's check / validation also optional
(cherry picked from commit 59a3be6d7543af926a85e2082c287096b702cd41)
=> Bug 1857304: ceph: make 'rgw_endpoint' check/validation also optional

pkg/operator/ceph/csi/spec.go, pkg/operator/ceph/csi/util.go, pkg/operator/k8sutil/deployment.go, pkg/operator/k8sutil/statefulset.go
sometimes the kube schedular will schedule the provisioner pod on the same node. it doesn't make sense to have both provisioner pod running on the same node, we need to set the pod anti-affinity to make sure that no provisioner pods runnings on the same node.
Resolves #
**Checklist:**
=> BUG 1867092: ceph: set pod anti affinity to provisioner pod

pkg/operator/ceph/cluster/mon/health.go, pkg/operator/ceph/cluster/mon/health_test.go
For external cluster, it is not an issue to have a mon count set to 0
since Rook is not deploying/managing the monitors.
(cherry picked from commit f66473a8f8ac65f4f0dbb04ee8cc7b3570f487bf)
Resolves #
**Checklist:**
=> Bug 1867130: ceph: fix healtcheck for external cluster

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
This pool is not present when this is no bucket yet. So we don't need to
validate its presence.
(cherry picked from commit 0c8d20ffb48fdb8649207468f105d6941d23e015)
(cherry picked from commit 46b0b95d4c6d3e39a3d20762de17d86dd24081cd)
Resolves #
**Checklist:**
=> Bug 1867998: ceph: do not validate default.rgw.buckets.index

pkg/operator/ceph/cluster/crash/reconcile.go
If a node is gone, we try to remove crash collector deployments so they
don't stay stale or pending. We must ensure the node is gone and not
just return an error even if we successfully deployment the orphan
deployment.
(cherry picked from commit acc5ba1a6b69ec6ec3c8f691dccd79d901256a2b)
(cherry picked from commit e4f1e4c3a4d568f0bbaf8abf93b7e538bb129818)
Resolves #
**Checklist:**
=> Bug 1866812: ceph: check for gone node on crash collector

images/ceph/toolbox.sh
When hostname has hypen and/or numbers, the mon_endpoints is incorrectly
split and can point to invalid monitor names inside toolbox, Add fix to
split the hostname/ip that can include hypen, underscore or numbers.
Signed-off-by: Vasu Kulkarni <vasu@redhat.com>
Fixes
Signed-off-by: Vasu Kulkarni <vasu@redhat.com>
(cherry picked from commit 33bd58e07247c105a14accf9b922b0ea67dbbf4c)
Resolves #
**Checklist:**
=> Bug 1872680: ceph: fix mon endpoints split when using external ceph hosts

pkg/operator/ceph/cluster/osd/osd.go
OCS 4.6 will run on RHCS 4.1z2 which has the encryption code but will
print 14.2.8 so let's change the min version.
=> ceph: change min encryption version for ocs

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Reverts openshift/rook#120
I thought the build was locked downstream, but it might not be the case, so reverting this.
=> Revert "Bug 1876852: ceph: fix to support TLS enabled rgw-endpoint"

pkg/operator/ceph/cluster/cluster_external.go
We only need to read the ceph cluster version if the cluster external
has external monitoring enabled.
This avoids any issue during upgrades from 1.3 to 1.4 when monitoring is
enabled and ceph caps have not been updated.
(cherry picked from commit 6f894a6de87c497fa5f1417439d23b8ce3d384ff)
Resolves #
**Checklist:**
=> Bug 1879919: ceph: only run version check for monitoring

build/makelib/golang.mk, pkg/operator/ceph/cluster/mon/health.go, pkg/operator/ceph/cluster/mon/health_test.go, pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/cluster/mon/node_test.go, pkg/operator/ceph/cluster/mon/service.go, pkg/operator/ceph/cluster/mon/spec.go
Backport the following fixes to 4.6 downstream:
- Mon PV cleanup when the mon failover failed
- New mon label that allows the PV cleanup
- Allow for upgrade from 4.5 with the new mon label
- Allow building on golang 1.15
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1873118
**Checklist:**
=> Bug 1873118: Backport mon pv cleanup

pkg/operator/ceph/cluster/osd/deviceSet.go, pkg/operator/ceph/cluster/osd/osd.go
The OSDs on PVCs were being reconciled inefficiently one by one with a label selector. This proves to be slow in large clusters. Instead, we now make this more efficient by querying for all existing PVCs and deployments and looking them up in memory with a map. This will save several minutes for the reconcile in a cluster with 100 OSDs.
This is just a small improvement to the clusters scaling up with many OSDs, but is expected to cut a few minutes off the reconcile time.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1871875
**Checklist:**
=> Bug 1871875: Detect OSDs on PVCs in batches instead of with label selectors individually

pkg/operator/ceph/cluster/osd/spec.go
On LUKS2 format, the resize operation requires the KEK to be passed. To
maintain a single simple init container for resize, we now open the
encrypted block with  "--disable-keyring" so that further operations
won't require the keyring.
(cherry picked from commit a7e78858ce99143cf27a8cba88f9645c04bab6d6)
**Checklist:**
=> Bug 1883927: ceph: disable keyring after opening encrypted block

pkg/operator/ceph/cluster/controller.go
Once we close the channel for the monitoring daemons, we update the
monitoring status so as to not call them again.
This is to prevent "close of closed channel" panic.
Co-authored-by: Travis Nielsen <tnielsen@redhat.com>
Signed-off-by: Nitin Goyal <nigoyal@redhat.com>
Signed-off-by: Raghavendra Talur <raghavendra.talur@gmail.com>
(cherry picked from commit 0c21abd535319ce4849d24a8b3a08d4555c69863)
Resolves #
**Checklist:**
=> Bug 1885428: ceph: prevent closing of channel more than once

pkg/operator/ceph/object/s3-handlers.go
When rgw is not responding the aws-sdk retries using exponential
backoff. Having 20 retries means we would wait for a while (hours) to
eventually fail. This is a problem as we cannot reflect the status of
the bucket properly.
Now we use 5 max retries which means around 8 seconds.
(cherry picked from commit d01a35cadda98dcfe62dee31ee01a10f804b81cb)
Resolves #
**Checklist:**
=> Bug 1885971: ceph: reduce s3 max retry

cluster/charts/rook-ceph/templates/clusterrole.yaml, cluster/examples/kubernetes/ceph/common.yaml, pkg/operator/ceph/csi/spec.go, tests/framework/installer/ceph_manifests.go
currently, we are setting the rook operator as owner
on the csidriver objects,  as csidriver is cluster
scoped object we should not set namespaced object as
owner on cluster scoped object
fixes #6162
(cherry picked from commit a1024ebc75f9c82a6874d6353c344a48f10e460e)
Resolves #
**Checklist:**
=> BUG 1882277: ceph: remove owner reference set by rook on csidriver

cluster/charts/rook-ceph/templates/clusterrole.yaml, cluster/examples/kubernetes/ceph/common.yaml, pkg/operator/ceph/csi/spec.go, tests/framework/installer/ceph_manifests.go
currently, we are setting the rook operator as owner
on the csidriver objects,  as csidriver is cluster
scoped object we should not set namespaced object as
owner on cluster scoped object
fixes #6162
(cherry picked from commit a1024ebc75f9c82a6874d6353c344a48f10e460e)
Resolves #
**Checklist:**
=> BUG 1888545: ceph: remove owner reference set by rook on csidriver

pkg/operator/ceph/disruption/clusterdisruption/mon.go, pkg/operator/ceph/disruption/clusterdisruption/mon_test.go, pkg/operator/ceph/disruption/clusterdisruption/static_pdb.go
updated mon pdb reconcile to delete mon pdb and create a new one when mon count changes in the cluster spec
(cherry picked from commit 28cd611eb4c417bb3e3e71b56190630d430dc588)
Resolves #
**Checklist:**
=> Bug 1888713: ceph: fix mon pdb reconcile

pkg/operator/ceph/cluster/mon/health.go, pkg/operator/ceph/cluster/mon/mon.go
The mon resources may be orphaned if there is a mon failover that was cancelled, for example a mon pvc may remain if the original mon comes up and the operator was restarted before the mon failover completed. The cleaning up of mon resources was only happening was each successful mon failover, now we perform the check with every reconcile since the resources were not being cleaned up predictably enough.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1889866
**Checklist:**
=> Bug 1889866: Check for orphaned mon resources with every reconcile

pkg/operator/ceph/disruption/clusterdisruption/mon.go, pkg/operator/ceph/disruption/clusterdisruption/mon_test.go, pkg/operator/ceph/disruption/clusterdisruption/static_pdb.go
updated mon pdb reconcile to delete mon pdb and create a new one when mon count changes in the cluster spec
(cherry picked from commit 28cd611eb4c417bb3e3e71b56190630d430dc588)
Resolves #
**Checklist:**
=> Bug 1891874: ceph: fix mon pdb reconcile

pkg/daemon/ceph/osd/remove.go
The osd purge job was not removing the osd prepare job or the osd pvc due to an invalid label query for the pvc. Now the prepare job and pvc will be removed as expected from the job.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1886348
**Checklist:**
=> Bug 1886348: Remove the osd pvc when purging the osd

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Currently, Rook does not support a prometheus exporter port different
than 9283 so let's fail and force the user to set it to the default.
(cherry picked from commit 1ed307cb0991dfd716bce471c8f88e6a11b7def0)
Resolves #
**Checklist:**
=> Bug 1890971: ceph: fail if mgr prometheus is not default

cluster/examples/kubernetes/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
cephfs csi driver still uses the ceph CLI for all the
ceph fs operations, when cephcsi gets a request from
the kubernetes it will internally starts threads for
each call. in cephcsi we are setting the pids
limit to max, to set this value the container has
to be running as the privileged one.
if we go with default pid limit we will face core dump
due to resource crunch.
without privileged access we will see Failed to set new
PID limit to -1: open /sys/fs/cgroup/pids/kubepods.slice/
kubepods-besteffort.slice/kubepods-besteffort-pod1029ed37_bebc_466d_9e53_79e7323a67ed.slice/crio-9ef6768d027916f414bf30b54ef13eebad8efd0aa4741d97618affa838d7b4c0.scope/pids.max: permission denied …
=> Bug 1892234: Add privileged securityContext to cephfs deployment

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Backport PR to support TLS encrypted rgw endpoint
(cherry picked from commit 3de87ccd3534f5b9fe0f1a3958b071cf8adb839a)
Resolves #
**Checklist:**
=> Bug 1876852: ceph: fix to support TLS enabled rgw-endpoint

pkg/operator/ceph/object/spec.go
If the selector changes on the rgw service, during upgrade the clients will briefly not be able to connect to the rgw pods. After all the pods are updated with any new labels, the connections would be restored, but we want to avoid that temporary outage.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1904171
**Checklist:**
=> Bug 1904171: RGW service selector should not change during upgrade to OCS 4.6

pkg/operator/ceph/cluster/cleanup.go
Before cleaning up the cluster, we wait for all the daemon pods to be cleaned up. This fails when
a daemon is in pending state and has no NodeName. This PR ignores daemon pods that are not scheduled on any node.
(cherry picked from commit 753bdb3526ab56e6c6ce51215a6b97099bda7df9)
Resolves #
**Checklist:**
=> Bug 1886859: ceph: ignore unscheduled ceph daemons while cleaning up

pkg/operator/ceph/cluster/osd/osd.go
Downstream Ceph version sticks with 14.2.8 and adds up on the build
revision so the 14.2.11 coming from upstream prevents downstream from
working.
Resolves: #bz-1910760
=> Bug 1910760: ceph: fix c-v encryption min version

cluster/charts/rook-ceph/templates/clusterrole.yaml, cluster/examples/kubernetes/ceph/common.yaml, cluster/examples/kubernetes/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml, tests/framework/installer/ceph_manifests.go
This PR adds a new cmd line argument for the csi-provisioner sidecar to pass the pvc and namespace name to the cephcsi driver. and cephcsi needs to access the configmaps created in different namespaces updated RBAC to provide same access.
Resolves #
**Checklist:**
=> BUG 1924792: RBD PVC creation fails with error "invalid encryption kms configuration: failed to parse kms configuration"

pkg/operator/ceph/cluster/osd/osd.go, pkg/operator/ceph/cluster/osd/status.go
completeOSDsForAllNodes() method waits for 20 minutes for all the OSDs to start on all the nodes. This PR checks if
cluster deletion request was sent while waiting for OSDs to start. If yes, then completeOSDsForAllNodes() method will returnwithout waiting for 20 minutes.
(cherry picked from commit f5808185e0b6f198ecffe89a39b871ea6234d46d)
Resolves #
**Checklist:**
=> Bug 1922064: ceph: check for orchestration cancellation while OSDs are pending

pkg/daemon/ceph/osd/volume.go, pkg/operator/ceph/cluster/osd/envs.go
With 5f57b6fd3abbab60b2992171e042598b3fdbf333, we introduced a
regression in the validation code.
If the OSD PV comes from another cluster, GetCephVolumeRawOSDs must
return an error.
The prepare job will crash loop but at least with a useful and
comprehensive message.
(cherry picked from commit 7c928f4196518399302b59cdba974dfd48d8f953)
Resolves #
**Checklist:**
=> Bug 1922954: ceph: return an error if PVC is not clean

pkg/operator/ceph/object/user/controller.go
Currently endpoint is filled from `Status.Info["endpoint"]` string map for cephobjectstore user's secret and
have two issues:
1.) endpoint is nil and only secureendpoint is available
2.) Chance of small race window in which endpoint is not filled before this ceph object user is handling.
Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>
Resolves #
**Checklist:**
=> Bug 1921864: fill up Endpoint properly for cephobjectstoreuser

pkg/daemon/ceph/osd/daemon.go, pkg/operator/ceph/cluster/osd/osd.go, pkg/operator/ceph/cluster/osd/osd_pvc_test.go, pkg/operator/ceph/cluster/osd/osd_test.go, pkg/operator/ceph/cluster/osd/status.go, pkg/operator/test/client.go
Add a new OSD provisioner status (reported by provisioner configmap)
that denotes that an OSD is preexisting and that OSD prepare does not
need to be run for the OSD. This only applies to OSDs on PVC currently
where existence of a deployment for the OSD indicates no further
provisioning needs to occur. New status is "preexisting".
Allow creating new OSDs on PVCs before updating existing ones by
allowing deferring OSDs during processing of OSD provisioning status
ConfigMaps. Deferral is identified by new "preexisting" status.
Add a unit test to ensure OSD on PVC provisioning occurs as expected
including deferring already-created OSDs to be updated after new PVCs
are created. …
=> Bug 1915005: ceph: create new osds on pvc before update existing 

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
This reverts commit 1ed307cb0991dfd716bce471c8f88e6a11b7def0. In
8aaff235bbdf2264949145fad6804dea3865d873 we have introduced the ability
to set a specific monitoring port so the block that fails if the port is
not the default 9283 is not needed anymore.
(cherry picked from commit e99c1220383e8d8494b4966dc169a4e36bf39b2b)
(cherry picked from commit 3384c3f61d86c70707143fea6a4525867495a0a7)
Resolves #
**Checklist:**
=> ceph: revert fail if mgr prometheus is not default

pkg/apis/ceph.rook.io/v1/placement.go, pkg/operator/ceph/cluster/cleanup.go, pkg/operator/ceph/cluster/cleanup_test.go
The cleanup job will need to run wherever the ceph daemons were running. The scheduling is done by rook on the specific nodes where the daemons were running, so there is no need for other placement such as node or pod affinity.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1927023
**Checklist:**
=> Bug 1927023: Add tolerations for all daemons to the cleanup job

pkg/daemon/ceph/client/crash.go, pkg/daemon/ceph/client/crash_test.go, pkg/daemon/ceph/osd/remove.go
Add ceph archive cmd in osd removal for
Silencing the warning when osd is removed.
Signed-off-by: crombus <pkundra@redhat.com>
(cherry picked from commit 76ed166e86de3da532b137a9cd051d69f9ec92b3)
(cherry picked from commit 5a5ff82ef8a836a452dba6b9b01999dcc930d444)
Resolves #
**Checklist:**
=> Bug 1896810: ceph: add ceph archive cmd in osd removal

pkg/operator/ceph/cluster/osd/spec.go, pkg/operator/ceph/cluster/osd/spec_test.go
The settings for tuneDeviceClass and tuneFastDeviceClass were stored as a map[string]string. When iterating over the map to append the args, the args were being appended in an unpredictable order. The order could change every reconcile, resulting in an unnecessary OSD restart potentially every reconcile. Now we iterate over a slice that will be ordered predictably and ensure OSDs will not be restarted when not needed.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1931601
**Checklist:**
=> Bug 1931601: Consistently order the osd args to avoid restarts

pkg/daemon/ceph/client/pool.go, pkg/daemon/ceph/client/pool_test.go, pkg/operator/ceph/pool/validate.go, pkg/operator/ceph/pool/validate_test.go
Both cannot be identical otherwise this will create placement issues.
(cherry picked from commit 0300111f73c68e9afb075a239a972016884ba87c)
Resolves #
**Checklist:**
=> Bug 1931810: ceph: fail if subfailure domains are identical

pkg/operator/ceph/cluster/osd/spec.go
The --silent option will remove the progress bar of the curl but also
silence any errors of stderr, so adding --show-error will display the
error even if --silent is used.
(cherry picked from commit 069ff22d53af8e102a05062fef1920f6877e86ed)
Resolves #
**Checklist:**
=> Bug 1931839: ceph: show error even in silent curl

pkg/operator/ceph/cluster/osd/spec.go
cURL's ca-cert and Golang TLS config for ca-certs have a different
meaning, it seems that the Golang implementation will always lookup the
local certs first and then proceeds with the specificed cert, if the
system's certs works it will never go to the specificied certificate.
cURL however, does the opposite by strictly checking the specified cert.
If the certificate is signed we don't need to force a specific
certificate, thus by using capath instead we let cURL determine what's
best to validate against.
(cherry picked from commit 4b8ec15b69f236652a208450a532b366dbd69cb8)
Resolves #
**Checklist:**
=> Bug 1931839: ceph: do not use curl ca-cert for signed certificates

pkg/operator/k8sutil/prometheus.go
Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>
Do not reconcile ServiceMonitor/PrometheusRule on label updates.
This allows users to add custom labels which can be used by
custom Prometheus instances for monitoring.
Resolves: Bug 1933609 
**Checklist:**
=> Bug 1933609: unmanage labels of monitoring resources

pkg/operator/ceph/cluster/osd/spec.go
If there is a warning coming from the Vault server we must catch it and
exit immediately to reflect it if no key was retrieved.
(cherry picked from commit 0534b5a1800e2debcd9dd24b88992c951780920b)
(cherry picked from commit 36b4966bb0921a3c9689803fd12425097d648a80)
Resolves #
**Checklist:**
=> Bug 1934000: ceph: expose vault warnings better

pkg/operator/ceph/cluster/osd/deviceSet.go, pkg/operator/ceph/cluster/osd/deviceset_test.go
OSDs on PVCs previously were always replaced with PVCs of a given name. For on-prem scenarios where the OSDs might need to be removed instead of replaced, the operator now allows holes to exist in the PVC index names as long as there are a sufficient number of PVCs to meet the criteria for the deviceSet.count.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1927922
**Checklist:**
=> Bug 1927922: ceph: Allow removal of arbitrary osds on pvcs and simplify pvc names

pkg/operator/ceph/object/admin.go, pkg/operator/ceph/object/admin_test.go, pkg/operator/ceph/object/bucket.go, pkg/operator/ceph/object/controller.go, pkg/operator/ceph/object/objectstore.go, pkg/operator/ceph/object/objectstore_test.go, pkg/operator/ceph/object/realm/controller.go, pkg/operator/ceph/object/realm/controller_test.go, pkg/operator/ceph/object/user.go, pkg/operator/ceph/object/zone/controller.go, pkg/operator/ceph/object/zone/controller_test.go, pkg/operator/ceph/object/zonegroup/controller.go, pkg/operator/ceph/object/zonegroup/zonegroup.go
Sometimes `radosgw-admin` succeeds after showing logs to stderr. We should
skip non-json strings if parsing output as json.
Here is an example.
```
2021-02-26 04:10:44.190418 I | op-bucket-prov: creating Ceph user "ceph-user-aSzNqgE7"
E0226 04:11:37.901310       8 controller.go:199] error syncing 'logging/loki-bucket': error provisioning bucket: Provision: can't create ceph user: error creating ceph user "ceph-user-aSzNqgE7": failed to unmarshal json. 2021-02-26T04:11:21.425+0000 7f6714be4980  1 robust_notify: If at first you don't succeed: (110) Connection timed out
2021-02-26T04:11:21.426+0000 7f6714be4980  0 ERROR: failed to distribute cache for ceph-hdd-object-store.rgw.meta:users.uid:ceph-user-aSzNqgE7
2021-02-26T04:11:32.168+0000 7f6714be4980  1 …
```
=> Bug 1935125: ceph: Fix improper json parsing in radosgw-admin

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
(cherry picked from commit 1532070a3e6167de2f7860203ae13a75134fceed)
This PR adds an alert that notifies the users if an OSD restarts
for 5 times under 5 minutes. Each restart corresponds to 2 changes
in the value of ceph_osd_up metric.
Resolves #
**Checklist:**
=> Bug 1935342: ceph: add osd flapping alert

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
(cherry picked from commit 136231a)
Ceph_daemon label includes references to a replaced OSD that cause a prometheus
ruleset to fail due many-to-many match error. The changes to this PR filters the
extra matching ceph_daemon time-series.
Resolves #
**Checklist:**
=> Bug 1904302: ceph: fixed prometheus query to avoid many-to-many match error

pkg/operator/k8sutil/prometheus.go
Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>
Do not reconcile ServiceMonitor/PrometheusRule on label updates.
This allows users to add custom labels which can be used by
custom Prometheus instances for monitoring.
Backport of #7323
**Checklist:**
=> Bug 1936406: ceph: unmanage labels of monitoring resources

pkg/daemon/ceph/client/pool.go
Downstream nautilus has the code for rbd mirroring snapshots schedule so
we need to enable it.
=> Bug 1938367: ceph: enable snap schedule for downstream nautilus

pkg/operator/ceph/cluster/controller.go
deletion of cluster is stuck when cluster is not configured. The PR skips the cleanup and removes the finalizers if the cluster was not configured, that is, if clusterInfo could not be loaded.
(cherry picked from commit 7bd05d0d7ca26caf3fcfefd4b4a514664559db33)
Resolves #
**Checklist:**
=> Bug 1937070: ceph: skip cleanup if cluster is not configured correctly

pkg/operator/ceph/cluster/mon/health.go
As per, https://bugzilla.redhat.com/show_bug.cgi?id=1939617 mons
failover is failing on stretched clusters. The upstream Ceph fix will
not make it into 4.2.z1 and thus will miss OCS 4.7. So we need to
disable the mon failover from the code directly.
Resolves #
**Checklist:**
=> Bug 1939617: ceph: disable mon failover on stretched cluster

pkg/operator/ceph/cluster/osd/spec.go, pkg/operator/ceph/cluster/osd/spec_test.go
When running encrypted OSDs on multipath the expand container was
failing to find the underlying device of the encrypted block. This was
because the underlying block was located in /dev/mapper and this path
wasn't mounted in the init container "expand-encrypted-bluefs".
This will manifest like so:
```
Underlying device for crypt device ocs-deviceset-block-dev-from-san-1-data-0-5qkmm-block-dmcrypt disappeared.
```
(cherry picked from commit 5762ca43b28bc9ff6d693452907a6f8535891dfb)
Resolves #
**Checklist:**
=> Bug 1941977: ceph: fix init container "expand-encrypted-bluefs" multipath

pkg/operator/ceph/cluster/osd/spec.go, pkg/operator/ceph/cluster/osd/spec_test.go
When running encrypted OSDs on multipath the expand container was
failing to find the underlying device of the encrypted block. This was
because the underlying block was located in /dev/mapper and this path
wasn't mounted in the init container "expand-encrypted-bluefs".
This will manifest like so:
```
Underlying device for crypt device ocs-deviceset-block-dev-from-san-1-data-0-5qkmm-block-dmcrypt disappeared.
```
(cherry picked from commit 5762ca43b28bc9ff6d693452907a6f8535891dfb)
Resolves #
**Checklist:**
=> Bug 1942515: ceph: fix init container "expand-encrypted-bluefs" multipath

pkg/operator/ceph/cluster/osd/spec.go
When no VAULT_BACKEND_PATH is specified we default to the API one which
is set to "secret/", we could use a different variable but we don't want
to break the library support. Bonus point this will also fix issue with
users passing a slash at the end of the path.
(cherry picked from commit d9646d09ce3f59084e713014d1567a6fc2c70ec0)
(cherry picked from commit 39fb635e427318e79da77607f62bce568eea915d)
Resolves #
**Checklist:**
=> Bug 1941647: ceph: remove extra slash in curl

pkg/daemon/ceph/osd/kms/envs.go, pkg/daemon/ceph/osd/kms/envs_test.go
When the cluster is growing, the operator always processes all OSDs and
re-generate their Deployment spec. The generated environment variables
for encryption are coming from a map, which by design is unordered. So
once generated the deployment will see their spec change since the
environment variable position will change.
See from the following diff:
```
env:							        env:
- name: KMS_SERVICE_NAME			      <
value: vault					      <
- name: VAULT_NAMESPACE				      <
value: ocsns					      <
- name: VAULT_TLS_SERVER_NAME			      <
- name: VAULT_BACKEND_PATH			      <
value: n_ocs					      <
- name: VAULT_ADDR					        - name: VAULT_ADDR
value: https://vault.qe.rh-ocs.com:8200		          value: https://vault.qe.rh-ocs.com:8200
>	        - name: VAULT_BACKEND_PATH
>	          value: …
```
=> Bug 1943275: ceph: avoid restarting all encrypted osd on cluster growth

pkg/operator/ceph/cluster/cephstatus.go, pkg/operator/ceph/cluster/cephstatus_test.go
Added the missing rgw app label to appLabels for deleting stuck rook pods
Signed-off-by: rohan47 <rohgupta@redhat.com>
(cherry picked from commit 06aa82620bef6d3cdad575b78ffdc9bb739bd9f9)
(cherry picked from commit 53d8d5bf46873b2b31da29acbc66c3693fd298b2)
Resolves #
**Checklist:**
=> Bug 1946592: ceph: added rgw app label to appLabels for deleting stuck rook pods

pkg/operator/k8sutil/prometheus_test.go, pkg/util/file.go, pkg/util/retry.go, pkg/util/set.go, pkg/util/set_test.go
Needed for https://github.com/openshift/release/pull/17923 since GOPATH is not set.
=> ceph: do not force go path in unit tests

pkg/operator/ceph/cluster/osd/osd.go, pkg/operator/ceph/cluster/osd/osd_test.go
The nodeAffinity for portable OSDs is needed to ensure the OSDs are tied to the same zone or other failure domain where the OSD was prepared and where it is expected to run. During upgrade the topology affinity was not being detected since the osd prepare job is skipped in that case. Now the topology will be detected from the running OSD daemon pod's node.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1953360
**Checklist:**
=> Bug 1953360: Detect the osd topology affinity during upgrade

pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/config/config.go, pkg/operator/ceph/config/defaults.go, pkg/operator/ceph/config/monstore.go
We don't need to set log_file to empty string since "log_to_file" is set
to False. This is probably an old leftover/hack we were doing in the
past when "log_to_file" and other related options were not there.
Because of this line
https://github.com/ceph/ceph/blob/master/src/perfglue/heap_profiler.cc#L99,
Ceph looks for the log_file conf option. In our case it was empty, so
the logging would default to the current directory which points to the
container runtime root when not set and we don't have permission to
write there.
We now force it to Ceph's default so that existing cluster will get the
fix after upgrading.
Just removing the option allows us to get dump in /var/log/ceph.
Phew, what a bug! …
=> Bug 1938049: ceph: allow heap dump generation when logCollector is not running

pkg/operator/ceph/cluster/mon/config.go, pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/cluster/mon/mon_test.go
After mon failover is initiated, there was a time window where if the operator
was restarted, the new mon is started and has joined quorum, but the operator
does not believe the mon should be in quorum after the operator restart.
The operator was mistakenly removing the extra mon prematurely, sometimes
causing quorum to be lost if another mon was also down at the same time.
If the mon does not come back online, steps to recover quroum would need
to be followed from the disaster guide. Now the expected list of mons
will be updated immediately during mon failover if the operator successfully
created the new mon deployment, thus removing the window where restarting
the operator can cause quorum loss.
Resolves …
=> Bug 1959983: ceph: Persist expected mon endpoints immediately during mon failover

pkg/operator/ceph/file/mds/spec.go, pkg/operator/ceph/file/mds/spec_test.go
add --public-addr=<podIP> args to ceph mds command when host network is not enabled.
(cherry picked from commit 5831c0f0d050b63e4b491b9aff3ddde3beb7fd17)
Resolves #
**Checklist:**
=> Bug 1949558: ceph: add --public-addr args to ceph mds command

design/ceph/mon-health.md, pkg/operator/ceph/cluster/mon/health.go, pkg/operator/k8sutil/pod.go, pkg/operator/k8sutil/pod_test.go
Events like node drain can take more than 10-15 minutes. If the node is not up before the default monTimeOut of 10 minutes, then rook will attempt to fail over the mon. This failover won't work as the node is still down.
This PR retries once before the mon failover if the mon pod is not scheduled
(cherry picked from commit f38829b57d0c14e28a203a8b7dd4325036d03eaf)
Resolves #
**Checklist:**
=> Bug 1959980: ceph: retry once before mon failover if mon pod is unscheduled

pkg/operator/ceph/file/mds/mds.go, pkg/operator/ceph/object/rgw.go
We now always set the config flags on reconcile. Previously we were
looking for non-existing rgw or mds which means that on upgrade we would
never set those flags. However, we want to set those flags on "old"
cluster that got upgraded.
(cherry picked from commit ca1cf6672e80cc1bab764d2d29751cdb4906e89d)
Resolves #
**Checklist:**
=> Bug 1951348: ceph: always apply config flags for mds and rgw

pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/cluster/mon/mon_test.go
After mon failover is initiated, there was a time window where if the operator
was restarted, the new mon is started and has joined quorum, but the operator
does not believe the mon should be in quorum after the operator restart.
The operator was mistakenly removing the extra mon prematurely, sometimes
causing quorum to be lost if another mon was also down at the same time.
If the mon does not come back online, steps to recover quroum would need
to be followed from the disaster guide. Now the expected list of mons
will be updated immediately during mon failover if the operator successfully
created the new mon deployment, thus removing the window where restarting
the operator can cause quorum loss.
(cherry …
=> Bug 1959985: ceph: Persist expected mon endpoints immediately during mon failover

pkg/operator/ceph/file/filesystem_test.go, pkg/operator/ceph/file/mds/mds.go, pkg/operator/ceph/object/rgw.go
We now always set the config flags on reconcile. Previously we were
looking for non-existing rgw or mds which means that on upgrade we would
never set those flags. However, we want to set those flags on "old"
cluster that got upgraded.
(cherry picked from commit ca1cf6672e80cc1bab764d2d29751cdb4906e89d)
Resolves #
**Checklist:**
=> Bug 1944148: ceph: always apply config flags for mds and rgw

cluster/charts/rook-ceph/templates/resources.yaml, cluster/examples/kubernetes/ceph/crds.yaml, go.mod, go.sum
added volume replication operator release-v0.1 branch to the go.mod as we are doing enhancements to the volume replication CRDS. Once we have a release will change this to release-v0.1 branch.
(cherry picked from commit 95d1bb9184979de715d2fe819b81fa5606d891a2)
(cherry picked from commit b14057821f7787134a016b8be7d3214b2d786242)
=> Bug 1962109: ceph: pin volume replication to release-v0.1 branch

cluster/charts/rook-ceph/templates/resources.yaml, cluster/examples/kubernetes/ceph/crds.yaml, pkg/apis/ceph.rook.io/v1/types.go
Both MonSpec.Count and CephVersionSpec.Image should be optional for the
external cluster. So marking them as so.
(cherry picked from commit d764af8d11cfbe82d1dfb32d97358362ece4d67a)
Resolves #
**Checklist:**
=> Bug 1964467: ceph: fix external cluster upgrade

pkg/daemon/ceph/client/mon.go, pkg/daemon/ceph/client/mon_test.go, pkg/operator/ceph/cluster/mon/health.go, pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/cluster/mon/spec.go
The mon daemon in a stretch cluster now can have its location set as a CLI param instead of setting it with a separate command. This enables mon failover to set the location of a mon immediately when it is joining quorum instead of having a delayed command to set the location.
This is merging before the upstream PR https://github.com/rook/rook/pull/7535 since upstream needs to wait for `ceph/ceph:v16.2.5`.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1949165
**Checklist:**
=> Bug 1949165: Set the location on the mon daemon for stretch clusters to reenable mon failover

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py, cluster/examples/kubernetes/ceph/create-external-cluster-resources.sh, cluster/examples/kubernetes/ceph/import-external-cluster.sh, go.mod, go.sum, pkg/operator/ceph/client/controller.go, pkg/operator/ceph/cluster/rbd/controller.go, pkg/operator/ceph/controller/controller_utils.go, pkg/operator/ceph/file/controller.go, pkg/operator/ceph/file/mirror/controller.go, pkg/operator/ceph/nfs/controller.go, pkg/operator/ceph/object/admin.go, pkg/operator/ceph/object/bucket.go, pkg/operator/ceph/object/bucket/provisioner.go, pkg/operator/ceph/object/bucket/provisioner_test.go, pkg/operator/ceph/object/bucket/rgw-handlers.go, pkg/operator/ceph/object/bucket/util.go, pkg/operator/ceph/object/controller.go, pkg/operator/ceph/object/controller_test.go, pkg/operator/ceph/object/health.go, pkg/operator/ceph/object/objectstore.go, pkg/operator/ceph/object/rgw.go, pkg/operator/ceph/object/rgw_test.go, pkg/operator/ceph/object/s3-handlers.go, pkg/operator/ceph/object/status.go, pkg/operator/ceph/object/user.go, pkg/operator/ceph/object/user/controller.go, pkg/operator/ceph/object/user/controller_test.go, pkg/operator/ceph/pool/controller.go
We have been having many issues with external mode with Ceph version
mismatching. The operator would have a Ceph version different than the
external cluster. The `radosgw-admin` was used to interact with S3
users, even a small version delta would cause the command to coredump.
After checking with the rgw core team it appears Rook was misusing the
CLI and the admin ops API should be used instead.
So this patch is the first introduction of go-ceph in Rook to consume
the rgw admin ops API instead of the `radosgw-admin` CLI, **only** for
user management in this initial commit.
Later we can do more such as bucket operation, zone management etc.
Closes: https://github.com/rook/rook/issues/7924 …
=> Bug 1955546: ceph: stop using radosgw-admin CLI for s3 user management

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
(cherry picked from commit 7445afb8748349445ac774e453f9b9cd31a10de1)
Resolves #
**Checklist:**
=> Bug 1925369: ceph: mons should enable v1 address type when enabling v2

pkg/operator/ceph/cluster/version_test.go, pkg/operator/ceph/version/version.go, pkg/operator/ceph/version/version_test.go
Currently we only check the Major, Minor, Extra and Build number in the ceph version to determine if all daemons should be upgraded or not. This PR also checks the commit hash for upgrading all the daemons.
This will be useful in cases where build number has not changed due to hotfix. For example:
existing ceph version - ceph version 14.2.11-139.el8cp (b8e1f91c99491fb2e5ede748a1c0738ed158d0f5) nautilus (stable)
new ceph version with hotfix - ceph version 14.2.11-139.0.hotfix.bz1959254.el8cp (5c0dc966af809fd1d429ec7bac48962a746af243) nautilus (stable)
(cherry picked from commit 49dc03e8ebbd114ca33e23c4f17e5dee93bbe390)
(cherry picked from commit 9a7e95741e0e626c95daeecfdb5f182a002b33c8)
**Which issue is …
=> Bug 1960784: ceph: compare ceph commit hash for upgrade check

pkg/daemon/ceph/client/config.go, pkg/daemon/ceph/client/mgr.go, pkg/operator/ceph/cluster/cephstatus.go, pkg/operator/ceph/cluster/cephstatus_test.go, pkg/operator/ceph/cluster/mgr/dashboard.go, pkg/operator/ceph/pool/controller.go, pkg/operator/ceph/pool/controller_test.go, tests/framework/installer/ceph_installer.go, tests/framework/installer/ceph_manifests.go, tests/integration/ceph_upgrade_test.go
In the latest Ceph releases starting with v16.2.1, all clients are recommended to be updated so they will have a security fix to connect with a secure global ID. A health warning will be raised if any insecure clients are connected and another health warning is raised if insecure clients are still allowed. Rook will now disable allowing the insecure clients if the health warning is not being raised to indicate that there are insecure clients still connected. This means that upgraded clusters will not have this disabled until all the daemons are updated.
If there are any clients connecting insecurely, they will be denied the next time they come online after the operator disables this setting. Therefore, perhaps we need to consider an option in the operator …
=> Bug 1970348: Disable insecure global id if no insecure clients

pkg/operator/ceph/csi/csi.go
This commit changes CSI_ENABLE_HOST_NETWORK default value to true since it was observed that cephfsvolume gets blocked when csi cephfs nodeplugin is restarted and nodeunpublish call also hangs when cephfs nodeplugin is using pod networking.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1970352
**Checklist:**
=> Bug 1970352: Set CSI_ENABLE_HOST_NETWORK default value to true

cluster/examples/kubernetes/ceph/monitoring/rbac.yaml
When there are two mgr daemons, a sidecar of the mgr will update the service monitor depending on the active mgr daemon. When there is only a single mgr, the operator will create the service monitor. Now, we add rbac for the mgr to create these resources.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1967880
**Checklist:**
=> Bug 1967880: Add rbac for mgr to create service monitor

pkg/daemon/ceph/client/pool.go
Downstream nautilus has the code for rbd mirroring snapshots schedule so we need to enable it.
The same downstream patch was done for 4.7 #194 as we are still using Nautilus in 4.8 enabling snapshot scheduling for the same reason.
=> Bug 1964025: ceph: enable snap schedule for downstream nautilus

pkg/operator/ceph/cluster/osd/spec.go
The API path when the KV enfine is used in version is different and must be adapted. We need to append a 'data' path, thus the path and response are changing.
v1 is https://vault.local.com:8200/v1/test-kv1/key
v2 is https://vault.local.com:8200/v1/test-kv2/data/key
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1970583
**Checklist:**
=> Bug 1970583: Fix vault when used with kv version 2

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
This PR adds an alert that notifies the users about OSD
requests taking too long to process.
Resolves # https://bugzilla.redhat.com/show_bug.cgi?id=1966139
**Checklist:**
=> Bug 1966139: ceph: add osd slow ops alert

pkg/operator/ceph/cluster/osd/spec.go
We have seen issues with fullchain.pem files containing one self-signed
certificate. At the same time, the failing configuration was not
providing any client certificates or keys.
The error from curl was `"self signed certificate in the chain"`.
The openssl binary is not available so we cannot even c_rehash the
certificate directory when using `--capath`, however this worked already
with a fully signed fullchain.pem along with a client certificate and
key. So we cannot only use `--cacert` which will break that use case.
This is becoming really obscur on why using `--cacert` solves this
problem. I just can't wait to use the `vault` binary, that's all I can
say...
(cherry picked from commit eb0c986196833a63ea98692bd7a3925c93179bf8)
**Description …
=> Bug 1970641: ceph: use cacert if no client cert/key are present

pkg/operator/ceph/cluster/osd/spec.go
We have seen issues with fullchain.pem files containing one self-signed
certificate. At the same time, the failing configuration was not
providing any client certificates or keys.
The error from curl was `"self signed certificate in the chain"`.
The openssl binary is not available so we cannot even c_rehash the
certificate directory when using `--capath`, however this worked already
with a fully signed fullchain.pem along with a client certificate and
key. So we cannot only use `--cacert` which will break that use case.
This is becoming really obscur on why using `--cacert` solves this
problem. I just can't wait to use the `vault` binary, that's all I can
say...
(cherry picked from commit eb0c986196833a63ea98692bd7a3925c93179bf8)
**Description …
=> Bug 1974399: ceph: use cacert if no client cert/key are present

pkg/operator/k8sutil/network.go, pkg/operator/k8sutil/network_test.go
In pkg/operator/k8sutil/network.go:ApplyMultus(), sort the string
annotations before applying them so that Rook will avoid the situation
where a Deployment or Pod will need updated repeatedly even when no
Multus network configuration has changed.
Resolves https://bugzilla.redhat.com/show_bug.cgi?id=1970503
**Checklist:**
=> Bug 1970503: sort multus annotation strings when applying

pkg/daemon/ceph/client/config.go, pkg/daemon/ceph/client/mgr.go, pkg/operator/ceph/cluster/cephstatus.go, pkg/operator/ceph/cluster/cephstatus_test.go, pkg/operator/ceph/cluster/mgr/dashboard.go, pkg/operator/ceph/cluster/mgr/spec.go, pkg/operator/ceph/pool/controller.go, pkg/operator/ceph/pool/controller_test.go
In the latest Ceph releases starting with v16.2.1, all clients are recommended to be updated so they will have a security fix to connect with a secure global ID. A health warning will be raised if any insecure clients are connected and another health warning is raised if insecure clients are still allowed. Rook will now disable allowing the insecure clients if the health warning is not being raised to indicate that there are insecure clients still connected. This means that upgraded clusters will not have this disabled until all the daemons are updated.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1974476
**Checklist:**
=> Bug 1974476: Disable insecure global id if no insecure clients

pkg/daemon/ceph/client/config.go, pkg/daemon/ceph/client/mgr.go, pkg/operator/ceph/cluster/cephstatus.go, pkg/operator/ceph/cluster/cephstatus_test.go, pkg/operator/ceph/cluster/mgr/dashboard.go, pkg/operator/ceph/cluster/mgr/spec.go, pkg/operator/ceph/pool/controller.go, pkg/operator/ceph/pool/controller_test.go
In the latest Ceph releases starting with v16.2.1, all clients are recommended to be updated so they will have a security fix to connect with a secure global ID. A health warning will be raised if any insecure clients are connected and another health warning is raised if insecure clients are still allowed. Rook will now disable allowing the insecure clients if the health warning is not being raised to indicate that there are insecure clients still connected. This means that upgraded clusters will not have this disabled until all the daemons are updated.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1974477
**Checklist:**
=> Bug 1974477: Disable insecure global id if no insecure clients

pkg/operator/ceph/cluster/osd/spec.go
When evaluating the potential "warning" key from the json output we were
not hiding stdout (1) from the output, so the key was leaked. Also the
warning check for the key was not perfect, it only checked for the
command to succeed, but we should introspect it since the "warning" key
is always present unlike the "error" one.
We now only print the warning or the error is present.
(cherry picked from commit bcd2511a7269ceb72c5c4a255fa760de85dea1e1)
Resolves #
**Checklist:**
=> Bug 1974745: ceph: do not leak key encryption key

pkg/operator/ceph/cluster/osd/spec.go
When evaluating the potential "warning" key from the json output we were
not hiding stdout (1) from the output, so the key was leaked. Also the
warning check for the key was not perfect, it only checked for the
command to succeed, but we should introspect it since the "warning" key
is always present unlike the "error" one.
We now only print the warning or the error is present.
(cherry picked from commit bcd2511a7269ceb72c5c4a255fa760de85dea1e1)
Resolves #
**Checklist:**
=> Bug 1974748: ceph: do not leak key encryption key

pkg/operator/ceph/object/bucket/provisioner.go, pkg/operator/ceph/object/config.go, pkg/operator/ceph/object/health.go, pkg/operator/ceph/object/s3-handlers.go, pkg/operator/ceph/object/user/controller.go
For the TLS communication for AdminOps Api, httpclient is required and filled with TLS certs, currently it is set to nil pointer in
`buckethealthchecker` and `cephobjectstoreuser`.
Resolves #
**Checklist:**
=> Bug 1974609: ceph: initialise httpclient for bucketchecker and objectstoreuser

pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/cluster/mon/mon_test.go
When the mons are using the dataDirHostPath and not a volumeClaimTemplate,
they need to be permanently assigned to a node. The node assignment
was missing in stretch clusters when the dataDirHostPath was being
used. This resulted in mons that were moving to other nodes for example
during a node drain, which would cause the mon to lose its backing store.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1949165
**Checklist:**
=> Bug 1949165: Mons in stretch cluster must be assigned to a node

pkg/operator/ceph/cluster/mon/health.go, pkg/operator/ceph/cluster/mon/health_test.go
In a production cluster we never should have two mons running on the same node. However, if two mons have ended up on the same node, whether from a bug or some other unintentional event, the operator will evict one of them and failover to a new mon. This only applies when allowMultiplePerNode is false.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1974204
**Checklist:**
=> Bug 1974204: Evict a mon if colocated with another mon

pkg/operator/ceph/cluster/predicate.go
If the CephCluster CR is updated let's cancel any on-going
orchestration. This will handle the situation where the spec is
misconfigured and OSD are crashlooping.
Prior to this patch, we would have to wait for the provisioning to
timeout, which will leave the cluster in a bad state for 10min or more.
Now the CR changes are picked up right away and the OSDs will deploy
normally.
(cherry picked from commit 40607c11169a5b8da5ee3c5ba48ade0253e57324)
Resolves #
**Checklist:**
=> Bug 1970583: ceph: cancel on-going orchestration on any CR update

cluster/charts/rook-ceph/templates/resources.yaml, cluster/examples/kubernetes/ceph/crds.yaml, pkg/apis/ceph.rook.io/v1/types.go
When the cluster is external we don't have any instances of rgw running
so let's not have this as a required field in the spec.
(cherry picked from commit e25e0e81039d00752b17c98d9a1e86d5f3956436)
Resolves #
**Checklist:**
=> Bug 1964467: ceph: do not require rgw 'instances' spec

pkg/operator/ceph/object/bucket/provisioner.go, pkg/operator/ceph/object/health.go, pkg/operator/ceph/object/user/controller.go
The debug for adminOps client can be enabled by setting `Debug` flag.
In this PR, it is enabled for OBC and cephobjectstore not healthchecker.
Also add similar changes while calling `NewS3Agent` in the bucket
provisioner code path.
Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>
(cherry picked from commit 560f44b07e154ad94af6d736ecc35501560fdaaa)
(cherry picked from commit 7149359ad87b3ec79b1d3f054f5b05a157d082df)
Resolves #
**Checklist:**
=> bug 1974344: ceph: enable debug for adminops client if the rook loglevel <= debug

cluster/charts/rook-ceph/templates/role.yaml, cluster/charts/rook-ceph/templates/rolebinding.yaml, cluster/examples/kubernetes/ceph/common.yaml, cmd/rook/rook/rook.go, go.sum, pkg/clusterd/context.go, pkg/daemon/ceph/client/command.go, pkg/daemon/ceph/client/command_test.go, pkg/operator/ceph/cluster/mgr/dashboard.go, pkg/operator/ceph/cluster/mgr/orchestrator.go, pkg/operator/ceph/cluster/mgr/spec.go, pkg/operator/ceph/cluster/mgr/spec_test.go, pkg/operator/ceph/object/admin.go, pkg/operator/ceph/object/controller.go, pkg/operator/ceph/object/health.go, pkg/operator/ceph/object/objectstore.go, pkg/util/exec/exec.go, pkg/util/exec/exec_pod.go, tests/framework/utils/k8s_helper.go, tests/integration/ceph_base_file_test.go
When the CephCluster is configured with Multus and multiple networks are
used to deploy Ceph some commands are failing to be executed from the
Operator. These commands, in particular, `radosgw-admin` ones need access
to the "ceph public network" to talk to OSDs. Unfortunately, the
Rook-Ceph Operator does not have the network annotations and thus
doesn't have the networks available and cannot reach OSDs. So the commands end
up hanging and eventually time out.
Applying the annotations to the Operator pod is possible but will result
in restarting the operator too and this should be avoided at all costs.
Also, applying the annotations beforehand is not possible since the
Multus declaration is in the CephCluster specification. So we would have
no idea what to do.
So the current approach runs a …
=> Bug 1978722: ceph: proxy ceph commands when multus is configured

pkg/operator/ceph/object/admin_test.go, pkg/operator/ceph/object/user/controller.go
The CephClusterSpec was missing from the object context, so the check
for the network provider in RunAdminCommandNoMultisite() was not
discovering the network property correctly.
(cherry picked from commit ad54ed8aacf6d6e7fc49657568ebc051a0f2ae76)
Resolves #
**Checklist:**
=> Bug 1978722: ceph: add missing spec to the object context

pkg/operator/ceph/object/bucket/provisioner.go, pkg/operator/ceph/object/bucket/util.go
The lib-bucket-provisioner was missing the cephCluster spec so the check
in RunAdminCommandNoMultisite would fail.
This is similar to ad54ed8aacf6d6e7fc49657568ebc051a0f2ae76 just a
different place.
(cherry picked from commit 1fd76a11685f950425bdfc1db43da37f5aeda58b)
(cherry picked from commit 641988b0dff5db2a1b84bd40b8d740819ac506bf)
Resolves #
**Checklist:**
=> Bug 1981849: ceph: add missing ceph cluster spec

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
This commit adds an alert that notifies the users about OSD
requests taking too long to process.
(cherry picked from commit f84cbb47fe40089dad29b7455e16a03453a854fb)
=> Bug 1966139: [release-4.7] ceph: add osd slow ops alert

cluster/examples/kubernetes/ceph/crds.yaml
With the targetSizeRatio missing from the v1 schema, the setting is
being ignored on the filesystem and object store CRs, thus preventing
the pg autoscaler from behaving as expected in OCS 4.7.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1977020
**Checklist:**
=> Bug 1977020: Add targetSizeRatio to the v1 schema

pkg/operator/ceph/csi/betav1csidriver.go, pkg/operator/ceph/csi/csidriver.go, pkg/operator/ceph/csi/spec.go
Update the CSIDriver object to v1 from betav1 as it will be
deprecated in v1.19+ and become unavailable in v1.22+
Signed-off-by: Yug <yuggupta27@gmail.com>
(cherry picked from commit d513dc4bc597ca8fc0e9b332e6c66e38bdd6a587)
Resolves #
**Checklist:**
=> Bug 1994588: ceph: update CSIDriver object from betav1 to v1

pkg/daemon/ceph/client/upgrade.go, pkg/daemon/ceph/client/upgrade_test.go
This handles the scenario where the OSDs have been created but not yet
started due to a wrong CR configuration.
For instance, when OSDs are encrypted and Vault is used to store
encryption keys, if the KV version is incorrect during the cluster
initialization the OSDs will fail to start and stay in CLBO until the
CR is updated again with the correct KV version so that it can start.
For this scenario, if the CRUSH map has no host registered yet it's fair
to assume the initialization broke and we need to fix it. So when don't
need to call ok-to-stop since it will always fail and eventually force
pass but let's not wait for nothing.
(cherry picked from commit 88048cc4e871ced8cb452245cbf034f4cbf9e666) …
=> Bug 1997125: ceph: do not check ok-to-stop when OSDs are in CLBO

pkg/util/exec/exec.go
In e8f9cfcb714685d93017be279d9ffdfc3847acca, the logging was replaced by
Debug which is probably a mistake given the intent of the commit to
enable debug logging on the prepare job.
However, this code is only triggered when running a ceph-osd with the
rook binary, so we must run Info and run Debug since Debug is not
activated.
(cherry picked from commit da56354aa3c18ff3b88848aaea9c1849c79f18d5)
Resolves #
**Checklist:**
=> Bug 1989988: ceph: run CLI output with Info logging

pkg/operator/ceph/cluster/mon/health.go
Stretch clusters in Ceph do not yet support failing over the arbiter mon, so we now disable the arbiter mon from failing over. Soon Ceph will support the arbiter mon failover and we will reenable this failover feature.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1989759
**Checklist:**
=> Bug 1989759: Refuse to failover the arbiter mon on stretch clusters

pkg/operator/ceph/csi/betav1csidriver.go, pkg/operator/ceph/csi/csidriver.go, pkg/operator/ceph/csi/spec.go
This PR fixes the below items
* fix panic in reCreateCSIDriverInfo
Initialize the client and the csidriver object before calling the reCreateCSIDriverInfo function.
* Reuse defined csiDriver object
reuse already defined csiDriver object instead of referring to the method receiver
* fix logging of csidriver
log the successful message about starting CSIDriver after creating the daemonset and deployment objects.
Signed-off-by: Madhu Rajanna madhupr007@gmail.com
Note: the issue was reported at slack https://rook-io.slack.com/archives/CK9CF5H2R/p1629776387282600
Resolves #
**Checklist:**
=> Bug 1994588: ceph: fix panic when recreating the csidriver object

cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Variable name `exec`, was raising an error with python2.
Renamed it to `execErr`.
Resolves #
**Checklist:**
=> Bug 1999605: ceph: making script backward compatible with python2

pkg/operator/ceph/cluster/mgr/spec.go
The mgr init containers run a ceph command that may get stuck if the mon quorum is down. The liveness probe is not in effect during the init containers, thus the mgr pod may stay hung indefinitely when this happens. To ensure the mgr does not hang, we add a bash timeout to the ceph command so it will restart and try again in case mon quorum is restored.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1990031
**Checklist:**
=> Bug 1990031: Add timeout in mgr init container

pkg/daemon/ceph/osd/kms/vault.go, pkg/daemon/ceph/osd/kms/vault_test.go
Prior, we were returning a nil map and thus the assignment for forced
deletion was not working since we were trying to assign on a nil map.
(cherry picked from commit 2e73baf4f590cad7626fb9763b46dfe8a541c6b2)
Resolves #
**Checklist:**
=> Bug 2008471: ceph: do not fail on keys deletion

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Instead of using 'absent' query, we are trying to use 'up' which should
provide us with the needed 'namespace' field in the resultant metrics
Signed-off-by: aruniiird <amohan@redhat.com>
(cherry picked from commit 854eb0113f2fb8749f2a73da56efba8e52166584)
Resolves #
**Checklist:**
=> Bug 2006323: [release 4.8] change ceph mgr is absent alert

pkg/daemon/ceph/osd/kms/kms.go, pkg/daemon/ceph/osd/kms/kms_test.go, pkg/daemon/ceph/osd/kms/vault.go, pkg/daemon/ceph/osd/kms/vault_api.go, pkg/daemon/ceph/osd/kms/vault_api_test.go, pkg/daemon/ceph/osd/kms/vault_test.go, tests/manifests/test-kms-vault-spec.yaml
When TLS is used and includes a caert, client key/cert, we need to copy
the content of the secret to a file in the operator's container
filesystem so that we can build the TLS config and thus the HTTP Client,
which reads those files.
Also, removing the files after each API call so they don't persist on
the filesystem forever.
(cherry picked from commit 61afadd97e62166f8ef9c18f7cbd66c17ceb96e8)
(cherry picked from commit 9b85ccb54e8d94140c34890db37969d8785c9a89)
Resolves #
**Checklist:**
=> Bug 1975272: ceph: fix kms auto-detection when full TLS

cluster/examples/kubernetes/ceph/monitoring/prometheus-ceph-v14-rules.yaml
Only the 'Running' mons with result value of '1' should be counted.
(cherry picked from commit af44e5c58470f3bf1d5e950dc19e07c70de693da)
Resolves #
**Checklist:**
=> Bug 1944513: [release 4.9] fix ceph mon quorum lost alert query

pkg/daemon/ceph/client/mirror.go
The monitor list was not sorted, so each time we were reconciling, the
peer secret token will see its content updated with randomized
monitors. This would enter our predicate and trigger a reconcile.
Potentially an endless one, if the randomized list is already different.
Closes: https://github.com/rook/rook/issues/9076
(cherry picked from commit 8cb6cdcea428e72e6b9021ff9cba548f5ab60626)
Resolves #
**Checklist:**
=> Bug 2019946: rbd-mirror: use a sorted list for peer token content

pkg/operator/ceph/object/spec.go
Add a startup probe to the RGW pod. Allow 180 seconds for the RGW to
start responding to its /swift/healthcheck endpoint. Usually the RGW
starts up in less than 30 seconds, but it has observed to start between
60-90 seconds into container start in some instances.
Resolves #
**Checklist:**
=> [BZ 2034359] ceph: rgw: add startup probe to RGW pod

pkg/apis/ceph.rook.io/v1/security.go, pkg/daemon/ceph/osd/daemon.go, pkg/daemon/ceph/osd/encryption.go, pkg/daemon/ceph/osd/encryption_test.go, pkg/daemon/ceph/osd/kms/envs.go, pkg/daemon/ceph/osd/kms/vault.go, pkg/daemon/ceph/osd/kms/volumes.go, pkg/daemon/ceph/osd/volume.go, pkg/operator/ceph/cluster/osd/spec.go, pkg/operator/ceph/cluster/osd/spec_test.go, tests/manifests/test-cluster-on-pvc-encrypted.yaml
When configuring encrypted on-pvc clusters we now set the cluster fsid
in the LUKS header. If needed we can then determine if the encrypted
block is part of our cluster or not. We also attach the pvc_name in case
it might become useful.
Resolves #
**Checklist:**
=> Bug 2030291: ceph: add ceph cluster fsid to LUKS header

pkg/operator/ceph/object/spec.go
Add a startup probe to the RGW pod. Allow 180 seconds for the RGW to
start responding to its /swift/healthcheck endpoint. Usually the RGW
starts up in less than 30 seconds, but it has observed to start between
60-90 seconds into container start in some instances.
Resolves #
**Checklist:**
=> [BZ 2034361] rgw: add startup probe to RGW pod

pkg/daemon/ceph/client/subvolumegroup.go, pkg/operator/ceph/file/subvolumegroup/controller.go, pkg/operator/ceph/file/subvolumegroup/controller_test.go
If the cluster is external, users might still want to take advantage of
the ceph-csi configmap configuration for ceph filesystem subvolume
group. This configuration is handled by the controller whenever a
cephFilesystemSubVolumeGroup CR is created or deleted.
If the present cluster CephCluster is external, the controller
(cephFilesystemSubVolumeGroup) won't handle creation nor deletion of sub volume groups.
It just assumes that the given name is correct and the controller goes ahead with the
ceph-csi configuration.
Closes: #9551
(cherry picked from commit 49f75c8ec3252dc9af4ed07461bd0006e8d151c6)
Resolves #
**Checklist:**
=> Bug 2049718: subvolumegroup: handle external mode

.github/workflows/canary-integration-test.yml, deploy/examples/create-external-cluster-resources.py
Currently if we run external-script and user already exit,
it fails to create/run same user again if the caps are upgraded,
so we need to check first if user is already present.
And for upgrading user we can do upgrade after this
PR: https://github.com/rook/rook/pull/9609 will get merged.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2048458
Resolves #
**Checklist:**
=> Bug 2048458: csi: make create and get process separate for csi users

pkg/daemon/ceph/osd/kms/vault_api.go
If the KMS connection details for Vault have a VAULT_NAMESPACE we must
use it when building the vault client to auto-detect the KV internal
version.
(cherry picked from commit 23832c8cc7961ba15efb52bbc9ac49651913469e)
(cherry picked from commit 1da2b827ecbce77af4ba22c58655cc3c5519820f)
Resolves #
**Checklist:**
=> Bug 2052937: osd: add namespace in vault client

pkg/operator/ceph/object/controller.go
The object child controller should not compare versions if the object
store is external. The current version comparison is using the
cmdreporter to check the ceph version of the image in the CephCluster spec.
In external mode, this image is not set so the cmdreporter fails.
Also, this check is only valid for converged mode, so external mode
should be skipped.
(cherry picked from commit 856b14e60a1a49f61f9f1bf0d63f4f70c13b326a)
(cherry picked from commit dfe060100590d32ab5dd347047a0b09ff7e68d0e)
Resolves #
**Checklist:**
=> Bug 2052996: object: do not check for upgrade on external mode

pkg/operator/ceph/object/controller.go, pkg/operator/ceph/object/controller_test.go
We need to explicitly assign the ceph version within each scope since
one function returns a pointer and one is not.
Previously, the `desiredCephVersion` was recreated in the scope of the
`else` and thus a new variable `desiredCephVersion` was initialized (see
the `:=`).
Now, each scope creates and assign to clusterInfo a `desiredCephVersion`
value.
(cherry picked from commit 7f32461b8fee0b41f362c10f6a30367c3370fbeb)
(cherry picked from commit d233fd2293b5a6f273b543601df219f38e02142e)
Resolves #
**Checklist:**
=> Bug 2052996: rgw: fix variable assignment

pkg/operator/ceph/csi/controller.go, pkg/operator/ceph/csi/csi.go, pkg/operator/ceph/csi/predicate.go, pkg/operator/ceph/csi/spec.go
This commit modifies ceph-csi controller to be able to cleanup
ceph-csi deployment,daemonset,services & csidriver objects
when no cephcluster exists.
It makes the following changes:
- redundant check for tp.DriverNamePrefix is removed.
- retry to start drivers within reconcile loop is removed,
controller will retry in case of error now.
- stopDrivers() will now return error in case of failure.
- predicate delete func will now respond to cephcluster deletion.
- CSI resources will be cleaned up when cephcluster does not exist.
Fixes: #9697
(cherry picked from commit 1e9920fb85f54b467a2c4f3e9d75a00daf20279b)
(cherry picked from commit 2027e7f8ef38d111b9ec97adccd7f6a81d381d16)
**Which issue is resolved by this Pull …
=> Bug 2049075: csi: cleanup csi driver resources when zero cephclusters exist

deploy/examples/monitoring/prometheus-ceph-v14-rules.yaml
(cherry picked from commit 054d009af6a345d65c882a6b352dba3054abf91e)
Resolves #
**Checklist:**
=> Bug 2028483: monitoring: making alert firing timeout and the doc timeout same

pkg/operator/ceph/file/controller.go, pkg/operator/ceph/object/controller.go, pkg/operator/ceph/pool/controller.go
Clean up the code used to stop health checkers for all controllers
(pool, file, object). Health checkers should now be stopped when
removing the finalizer for a forced deletion when the CephCluster does
not exist. This prevents leaking a running health checker for a resource
that is going to be imminently removed.
Also tidy the health checker stopping code so that it is similar for all
3 controllers. Of note, the object controller now uses namespace and
name for the object health checker, which would create a problem for
users who create a CephObjectStore with the same name in different
namespaces.
(cherry picked from commit 03ba7dec640dc3f1c944c57f28ff0852c5f19c5b) …
=> Bug 2029744: pool: file: object: clean up stop health checkers

pkg/daemon/ceph/osd/volume.go, pkg/daemon/ceph/osd/volume_test.go
The OSD prepare job was succeeding even if the OSDs failed to be listed by ceph-volume. These errors should be returned and fail the job, resulting in a retry to retrieve the OSDs. Otherwise, the failure is masked and the admin needs to dig through logs to find why the OSDs were not configured on that node.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2054898
**Checklist:**
=> Bug 2054898: osd: Return error if fail to list osds in prepare job

deploy/charts/library/templates/_cluster-role.tpl, deploy/examples/common-second-cluster.yaml, deploy/examples/common.yaml, pkg/daemon/ceph/osd/remove.go, pkg/daemon/ceph/osd/remove_test.go, pkg/operator/ceph/cluster/osd/deviceSet.go
The purge job is intended to clean up all the resources related to an OSD that is to be removed. An OSD with a metadata, wal, and data PVC was only cleaning up the data PVC. Now the metadata and wal PVCs will also be cleaned up.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=1947482
**Checklist:**
=> Bug 1947482: osd: Purge job will remove all pvcs for the osd

.github/workflows/canary-integration-test.yml, pkg/daemon/ceph/osd/remove.go
The osd destroy command leaves the osd id in use instead of fully purging the osd id. If the osd id is not also removed, it gives the impression that there is still something that needs to be cleaned up from the old osd.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2059027
**Checklist:**
=> Bug 2059027: osd: Remove osd with purge instead of destroy

pkg/operator/ceph/csi/util.go, pkg/operator/ceph/csi/util_test.go
This function was always using an empty string, instead of the extracted resources
Signed-off-by: Tom Hellier <me@tomhellier.com>
(cherry picked from commit 59b4c57406f7a3d80109b917cad36afcc87c4519)
=> BUG 2062559: core: fix empty string bug

pkg/daemon/ceph/osd/kms/vault_api.go
When kube authentication is used, let's clarify the error message and
hopefully lead to a better understanding on where to look for.
It could be misleading to print "token auth" when using kube auth,
although internally a token is used (the JWT from the Service
Account).
(cherry picked from commit 74081d90d307b961fdc2980d440ec507f73489a5)
(cherry picked from commit 3cf062243d388002e7dbea62b285c298bcc985da)
Resolves #
**Checklist:**
=> Bug 2061657: osd: clarify vault auth error message

pkg/operator/ceph/cluster/controller.go, pkg/operator/ceph/object/controller.go, pkg/operator/ceph/object/notification/controller.go, pkg/operator/ceph/object/notification/obc_label_controller.go, pkg/operator/ceph/reporting/reporting.go, pkg/operator/ceph/reporting/reporting_test.go
ReportReconcileResult should never be given an object that is nil. It is
impossible to force compile-time checking for this because the object's
type is an interface. We can't force this, but we can rework the
function definition to handle more cases where the object may not be
returned fully-complete, and we can rework callers to return structs
(not pointers-to-structs) so it is less likely a caller will pass nil
to the function.
(cherry picked from commit c92c6fbc36fbfd01f9f90aca08e4f392b0061f10)
(cherry picked from commit ae1eab91fc9990a72aa347ce0fa68b317a32a7da)
Resolves #
**Checklist:**
=> Bug 2061675: core: rework usage of ReportReconcileResult

deploy/examples/create-external-cluster-resources.py
core: fix incorrect join command
Fixing typo in join command
joing -> join
core: assign ACCESS_KEY and SECRET_KEY values only in case of actual run
When using dry-run option with external script, function create_rgw_admin_ops_user
is not returning expected values which leads to TypeError. This fix is to append
values to out_map dictionary only in case of actual run.
core: avoid creating json_out incase of dry-run
When using dry-run option with external script, out_map dictionary
doesn't contain keys ( ACCESS_KEY and SECRET_KEY ) which leads to KeyError.
This fix to avoid creating json_out incase of dry-run since we will not use
json_out for dry-run.
Resolves #
**Checklist:**
=> Bug 1996833: core: fix incorrect join command

pkg/operator/ceph/cluster/mon/mon.go
The canary pods are very short-lived pods and are not running ceph in any form. The startup probe was mistakenly enabled for the canary pod, which could cause the pod to fail unexpectedly if the startup probe was triggered after the delay timeout.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2063301
**Checklist:**
=> Bug 2063301: mon: Disable startup probe on canary pods

pkg/operator/ceph/cluster/cephstatus.go, pkg/operator/ceph/cluster/cluster.go, pkg/operator/ceph/cluster/controller.go, pkg/operator/ceph/cluster/mon/health.go, pkg/operator/ceph/cluster/monitoring.go, pkg/operator/ceph/cluster/osd/health.go, pkg/operator/ceph/cluster/osd/health_test.go, pkg/operator/ceph/controller/controller_utils.go, pkg/operator/ceph/object/controller.go, pkg/operator/ceph/object/health.go
Previously, the struct maintaining the list of cluster was still
initialized with a cluster item. Then the monitoring check will see that
the cluster is part of the struct already and thus won't run the
monitoring go routine again.
Now each time we cancel the context, we also remove the cluster item
from the map so that when the controller runs again, the monitoring
struct is re-populated and the go routine runs and statuses are updated.
Closes: https://github.com/rook/rook/issues/9911
(cherry picked from commit 05506e7a6836ab27d75552cc14174e6cea274cc8)
(cherry picked from commit fc9278c0402a72ece60d26eefef9b4583f4b0888)
Resolves #
**Checklist:**
=> Bug 2069795: core: reload go routine after CR is edited

pkg/daemon/ceph/osd/daemon.go, pkg/daemon/ceph/osd/encryption.go, pkg/daemon/ceph/osd/kms/envs.go
There is a corner case where an env variable populated with the prepare
job could influence and trigger some encryption code. We have an env
variable to discover whether the prepare job will encrypt a drive or not
so let's use that instead of running code as a noop and sometimes
trigger a corner case. In this scenario, the prepare job had an "IBM_"
env variable present in the OS image (IBM OS) so the setKEKinEnv()
function would get called for no reason.
(cherry picked from commit 6bc7827150da5249a56bf7c10bc32c20ef23ee45)
(cherry picked from commit 8b1b68c7842d6702ecba1fe5108b3c22f0a64a55)
Resolves #
**Checklist:**
=> Bug 2074558: osd: only set kek to env var on encryption scenario

pkg/operator/ceph/cluster/cluster_external.go, pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/csi/cluster_config.go, pkg/operator/ceph/csi/cluster_config_test.go, pkg/operator/ceph/file/subvolumegroup/controller.go
If a mon is added or removed in a ceph cluster all the CSI clusterID belongs to the ceph cluster should also get updated.
Added a new cluster identifier to the csi configmap, i.e ceph cluster namespace which helps to identify the clusterID belongs to that ceph cluster.
Note:- To support the upgraded clusters, we can ask users to update the mon IPs for the problamatic clusterID as it wont be updated by the operator.
(cherry picked from commit 8ab17e3b83e4b7c47bc540631d85ca5e9c715f53)
Resolves #
**Checklist:**
=> BUG 2078713: csi: add/remove mon IP from csi config

.github/workflows/setup-cluster-resources/action.yaml, pkg/apis/ceph.rook.io/v1/pool.go, pkg/apis/ceph.rook.io/v1/pool_test.go, pkg/operator/ceph/pool/controller.go, pkg/operator/ceph/pool/controller_test.go, pkg/operator/ceph/pool/validate.go
During deletion of a CephBlockPool CR, the underlying ceph pool was not being deleted. During the deletion sequence this is due to the spec being refreshed upon a call to check for dependents in ReportDeletionNotBlockedDueToDependents(). The pool name was then coming up blank during the deletion request and rook of course then wasn't finding the pool to delete.
Now Rook properly sets the pool name in the named spec every time it is converted internally from a CephBlockPool type to a NamedPoolSpec.
Also backporting the fixes to the CI for the canary test CNI.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2092143
**Checklist:**
=> Bug 2092143: Delete ceph pool when blockpool cr is deleted and fix canary tests

pkg/daemon/ceph/osd/kms/kms_test.go, pkg/daemon/ceph/osd/kms/vault.go, pkg/operator/ceph/object/spec_test.go
Return the error instead of hiding it, err could be non-nil for a lot of
reasons, eg: a canceled context or a non-existing object.
(cherry picked from commit 219e01756479964785ce4e1020f9bdb45ad52b05)
(cherry picked from commit fcf7943883481b1288a0f3076c52941428f2e849)
Resolves #
**Checklist:**
=> Bug 2089755: osd: do not hide the error

deploy/examples/create-external-cluster-resources.py
During the recent addtions of rgw validation
changes there are too many places where we use
rgwendpoint, so making fqdn to ip conversion globally
Resolves #
**Checklist:**
=> Bug 2088506: rgw: make fqdn rgw converted to ip everywhere

.github/workflows/canary-integration-test.yml, Documentation/CRDs/ceph-cluster-crd.md, deploy/examples/create-external-cluster-resources.py, deploy/examples/import-external-cluster.sh
For using restricted auth users we need to update the
restricted users in the Storage class, so updating
it in the json output for external cluster
Resolves #
**Checklist:**
=> Bug 2069314: csi: make storage class updated with csi-users in external cluster

pkg/operator/ceph/cluster/crash/crash.go, pkg/operator/ceph/cluster/crash/reconcile.go
earlier we're deleting v1beta1 always before creating
v1 job. Now, we delete only when k8s version is
latest(which supports v1  job) and v1 job is not created
which means this is the first time and this is the only time we'll
delete v1beta1.
(cherry picked from commit 196f5da6354eb9ef1626b6d85a0173fd5f1a8a7a)
Resolves #
**Checklist:**
=> Bug 2098621:  core: delete v1beta1 cronjob only when v1 not found

pkg/operator/ceph/cluster/cephstatus.go, pkg/operator/ceph/cluster/cephstatus_test.go, pkg/operator/ceph/cluster/mgr/mgr.go, pkg/operator/ceph/config/config.go, pkg/operator/ceph/config/config_test.go
In new deployments we always want to disable the insecure global id. If the mgr deployment is newly created, we know it's a new cluster and the mons are in quorum, so we can go ahead and disable the insecure global IDs.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2100946
**Checklist:**
=> Bug 2100946: mon: Disable insecure global ids for new deployments

cluster/examples/kubernetes/ceph/osd-purge.yaml, cmd/rook/ceph/osd.go, pkg/daemon/ceph/client/osd.go, pkg/daemon/ceph/osd/remove.go
If multiple removal jobs are fired in parallel, there is a risk of losing data since we will forcefully remove the OSD. It's also simply true if a single OSD is not safe to destroy, there is also a risk of data loss.
So now, we check if the OSD is safe-to-destroy first and then proceed. The code waits forever and retries every minute unless the --force-osd-removal flag is passed.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2106027
**Checklist:**
=> Bug 2106027: Require force flag to purge an OSD if data may be lost

cluster/examples/kubernetes/ceph/osd-purge.yaml, cmd/rook/ceph/osd.go, pkg/daemon/ceph/client/crash.go, pkg/daemon/ceph/client/osd.go, pkg/daemon/ceph/osd/remove.go
If multiple removal jobs are fired in parallel, there is a risk of losing data since we will forcefully remove the OSD. It's also simply true if a single OSD is not safe to destroy, there is also a risk of data loss.
So now, we check if the OSD is safe-to-destroy first and then proceed. The code waits forever and retries every minute unless the --force-osd-removal flag is passed.
Which issue is resolved by this Pull Request:
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2106026
**Checklist:**
=> Bug 2106026: Require force flag to purge an OSD if data may be lost

cluster/examples/kubernetes/ceph/osd-purge.yaml, cmd/rook/ceph/osd.go, pkg/daemon/ceph/client/crash.go, pkg/daemon/ceph/client/osd.go, pkg/daemon/ceph/osd/remove.go
If multiple removal jobs are fired in parallel, there is a risk of losing data since we will forcefully remove the OSD. It's also simply true if a single OSD is not safe to destroy, there is also a risk of data loss.
So now, we check if the OSD is safe-to-destroy first and then proceed. The code waits forever and retries every minute unless the --force-osd-removal flag is passed.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2027396
**Checklist:**
=> Bug 2027396: Require force flag to purge an OSD if data may be lost

cluster/examples/kubernetes/ceph/osd-purge.yaml, cmd/rook/ceph/osd.go, pkg/daemon/ceph/client/crash.go, pkg/daemon/ceph/client/osd.go, pkg/daemon/ceph/osd/remove.go
If multiple removal jobs are fired in parallel, there is a risk of losing data since we will forcefully remove the OSD. It's also simply true if a single OSD is not safe to destroy, there is also a risk of data loss.
So now, we check if the OSD is safe-to-destroy first and then proceed. The code waits forever and retries every minute unless the --force-osd-removal flag is passed.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2106025
**Checklist:**
=> Bug 2106025: Require force flag to purge an OSD if data may be lost

.github/workflows/codespell.yaml, deploy/charts/rook-ceph-cluster/values.yaml, deploy/examples/cluster.yaml, deploy/examples/operator-openshift.yaml, pkg/operator/ceph/cluster/mon/health.go, pkg/operator/ceph/cluster/mon/health_test.go, pkg/operator/ceph/cluster/mon/mon.go, tests/framework/utils/exec_utils.go
Mon failover reliability is improved in two scenarios with these changes.
First, if the failover is aborted because of failing to start the new mon
and wait for it to join quorum, the new mon will be fully removed and
the failover rolled back. Previously, the operator would leave the new
mon pod running even if it never joined quorum. Now the timeout for the failover
is increased to wait longer for the new mon, but if it times out, there
are no leftovers from the cancelled failover.
Second, if the operator is failed in the middle of a failover
before the old mon is removed, the operator needs to remove an extra
mon. The operator was only selecting a random mon for removal instead
of honoring the stretch cluster topology or looking for mons
on the same node …
=> Bug 2120598: mon: Improve mon failover reliability [4.11]

.github/workflows/codespell.yaml, deploy/charts/rook-ceph-cluster/values.yaml, deploy/examples/cluster.yaml, deploy/examples/operator-openshift.yaml, pkg/operator/ceph/cluster/mon/health.go, pkg/operator/ceph/cluster/mon/health_test.go, pkg/operator/ceph/cluster/mon/mon.go, tests/framework/utils/exec_utils.go
Mon failover reliability is improved in two scenarios with these changes.
First, if the failover is aborted because of failing to start the new mon
and wait for it to join quorum, the new mon will be fully removed and
the failover rolled back. Previously, the operator would leave the new
mon pod running even if it never joined quorum. Now the timeout for the failover
is increased to wait longer for the new mon, but if it times out, there
are no leftovers from the cancelled failover.
Second, if the operator is failed in the middle of a failover
before the old mon is removed, the operator needs to remove an extra
mon. The operator was only selecting a random mon for removal instead
of honoring the stretch cluster topology or looking for mons
on the same node that could be removed to restore …
=> Bug 2120601: mon: Improve mon failover reliability [4.10]

pkg/operator/ceph/csi/spec.go, pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-holder.yaml, pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-holder.yaml
Currently daemonset template.metadata.name is empty, and the way we are setting it is not correct use the daemonset name as the template.metadata.name
Add missing serviceAccountName to the holder pod.
backport of https://github.com/rook/rook/pull/10875
Resolves #
**Checklist:**
=> BUG 2123626:  fix holder pod creation in openshift multus cluster

deploy/examples/create-external-cluster-resources.py
The rgw ip validation feature was needing to update the rgw user cap to add info=read permission, but this permission is only backported till ceph pacific, so we added a check that only add this cap when ceph version support it,
But this cap was also adding with the other caps, so removed it from there Now it will only add this cap if ceph version support it
(cherry picked from commit 54425803b6cb6fa1e0896cc1e81850631b02e15b) (cherry picked from commit 32e4160971b0b152ce9235b2fd2532d7381f7bdf)
Resolves #
**Checklist:**
=> Bug 2130110: external: do not add info=read cap if ceph version doesn't support it

pkg/daemon/ceph/osd/kms/kmip.go
This commit changes cryptographic length for keys created
for kmip kms to 256 from 128, since it is more secure.
(cherry picked from commit https://github.com/red-hat-storage/rook/commit/9d0d93472ff601a0150371b8b62aeb8747348a55)
(cherry picked from commit https://github.com/red-hat-storage/rook/commit/0cf3af7a376bf09d1357275c33625e993e5d64a1)
=> Bug 2130497: osd: use 256 as cryptographicLength for keys using kmip kms

pkg/operator/ceph/object/spec.go, pkg/operator/ceph/object/spec_test.go
The Client_ID generated by operator was
different from the log rotate file created
The Clinet_ID= rgwceph.client.rook.ceph.rgw.my.store.a and log file name= ceph-client.rgw.my.store.a.log
So changed the CLient_ID to ceph-client.rgw.my.store.a for correct working and this follow the patterns how other modules Client_ID is generated
Closes: https://github.com/rook/rook/issues/8692
(cherry picked from commit fc7905a7bd37529c7e3e1be5e96bc3b2a507b543)
Resolves #
**Checklist:**
=> Bug 2130279: ceph: fixing ClientID of log-collector for RGW instance

pkg/operator/ceph/controller/spec.go
Stability issues have been observed with 1s. Socket latency is expected whenever CPUs are under minor pressure. Increasing value to 5s should cover most small-medium scale envs.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2126566
**Checklist:**
=> Bug 2126566: Increase liveness probe timeout to 5s

pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
The omap generator sidecar is the one who sets the pvc name and clustername in the metadata if the pv is re-attached to a new pvc or if the clustername changes, for that reason we need to set these flags on the omap generator sidecar also.
(cherry picked from commit ffdfeb5becb1181ab6c6401d117fa0ef478d2dbd)
Resolves #
**Checklist:**
=> BUG 2135830: csi: add setmetadata and clustername flag to omap

deploy/examples/create-external-cluster-resources.py
The validate rgw endpoint tls cert returns the certificate instead of returning whether it exist or not,
So updatd the flow how to use it
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2134769
**Checklist:**
=> Bug 2134769: external: fix endpoint_dial check for rgw endpoint

pkg/operator/ceph/csi/peermap/config.go, pkg/operator/ceph/csi/peermap/config_test.go
When mirror logs are enabled, `ceph osd pool get <poolname> all` command returns peer pool info along with the debug logs. This causes error while parsing the logs for json data. Using --out-file flag saves the json data in the file which can be parsed easily while logging will still be written to stdout/stderr.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2143899
**Checklist:**
=> Bug 2143899: core: Parse peer pool ouput with --out-file flag

pkg/daemon/ceph/osd/encryption.go, pkg/daemon/ceph/osd/volume.go, pkg/operator/ceph/cluster/osd/config.go, pkg/operator/ceph/cluster/osd/config_test.go, pkg/operator/ceph/cluster/osd/spec.go, pkg/util/exec/exec.go, pkg/util/exec/exec_test.go, pkg/util/exec/test/mockexec.go, pkg/util/exec/translate_exec.go
This commit implements this corner case during osd-prepare job.
```
The encrypted block is not opened, this is an extreme corner case
The OSD deployment has been removed manually AND the node rebooted
So we need to re-open the block to re-hydrate the OSDInfo.
Handling this case would mean, writing the encryption key on a
temporary file, then call luksOpen to open the encrypted block and
then call ceph-volume to list against the opened encrypted block.
We don't implement this, yet and return an error.
```
When underlying PVC for osd are CSI provisioned, the encrypted device is closed when PVC is unmounted due to osd pod being deleted. Therefore, this may occur more frequently and needs to be handled. This commit implements the fix for the same. …
=> BUG 2142780: osd: re-open encrypted disk during osd-prepare-job if closed

pkg/operator/ceph/test/containers.go, pkg/operator/k8sutil/pod.go
Ceph will use a random nonce for the msgr daemons as long as they are running as PID 1 or have the environment variable CEPH_USE_RANDOM_NONCE set to indicate running in a containerized environment. While the Ceph daemons in Rook are expected to run in PID 1, there are some environments where the container runtime may choose to run something else such as `/usr/bin/pod` as PID 1. The side effect then is that ceph uses the pid as the nonce and causes problems when the daemons restart with the same PID.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2139103
**Checklist:**
=> Bug 2139103: core: Set env var for ceph msgr to use random nonce

cmd/rook/ceph/osd.go, pkg/operator/ceph/cluster/mgr/spec.go, pkg/operator/ceph/cluster/mon/env.go, pkg/operator/ceph/cluster/osd/envs.go, pkg/operator/ceph/cluster/osd/provision_spec.go, pkg/operator/ceph/cluster/osd/spec.go
The fsid, username, and user secrets were from legacy and no longer needed on the osd daemon or mon pods. This removes the unnecessary env vars from the pod specs.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2144067
**Checklist:**
=> Bug 2144067: core: Remove unnecessary env vars from pod specs

pkg/operator/ceph/test/containers.go, pkg/operator/k8sutil/pod.go
Ceph will use a random nonce for the msgr daemons as long as they are running as PID 1 or have the environment variable CEPH_USE_RANDOM_NONCE set to indicate running in a containerized environment. While the Ceph daemons in Rook are expected to run in PID 1, there are some environments where the container runtime may choose to run something else such as /usr/bin/pod as PID 1. The side effect then is that ceph uses the pid as the nonce and causes problems when the daemons restart with the same PID.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2150410
**Checklist:**
=> Bug 2150410: core: Set env var for ceph msgr to use random nonce

pkg/daemon/ceph/osd/encryption.go, pkg/daemon/ceph/osd/volume.go
During osd-prepare-job,
The encrypted device is found to be closed in some cases when the OSD deployment has been removed manually accompanied by any of following cases:
- node reboot
- csi managed PVC being unmounted etc
while re-opening the block to re-hydrate the OSDInfo, the dm device `<pvc-name>-block-dmcrypt` clashes with the one used by OSD pod which is stale by now.
This commit adds cmd to remove this stale dm device. Error with output "No such device" is ignored.
(cherry picked from commit 24fa9ed935b3287acaf2867c58d015f5addd1b43)
Resolves #
**Checklist:**
=> BUG 2142780: osd: remove stale dm device during osd-prepare-job

pkg/daemon/ceph/osd/daemon.go, pkg/operator/ceph/cluster/osd/deviceSet.go, pkg/operator/ceph/cluster/osd/deviceset_test.go
Multipath devices may have an FSTYPE=mpath_member even though a valid device for creating an OSD. The device will be allowed in this case when creating the OSD on a PV since it is a device specifically provisioned for the OSD. Allow a `.` in the storageClassDeviceSet name to avoid failing the creation of the OSD prepare job.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2148567
**Checklist:**
=> Bug 2148567: osd: Allow mpath_member filesystem for mpath disks

pkg/operator/ceph/test/containers.go, pkg/operator/k8sutil/pod.go
Ceph will use a random nonce for the msgr daemons as long as they are running as PID 1 or have the environment variable CEPH_USE_RANDOM_NONCE set to indicate running in a containerized environment. While the Ceph daemons in Rook are expected to run in PID 1, there are some environments where the container runtime may choose to run something else such as /usr/bin/pod as PID 1. The side effect then is that ceph uses the pid as the nonce and causes problems when the daemons restart with the same PID.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2150411
**Checklist:**
=> Bug 2150411: core: Set env var for ceph msgr to use random nonce

.github/workflows/canary-test-config/action.yaml, .github/workflows/integration-test-config-latest-k8s/action.yaml, cmd/rook/ceph/ceph.go, cmd/rook/ceph/mgr.go, cmd/rook/ceph/osd.go, cmd/rook/ceph/osd_test.go, deploy/charts/rook-ceph-cluster/templates/deployment.yaml, deploy/examples/direct-mount.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox.yaml, design/ceph/ceph-nfs-ganesha.md, images/ceph/toolbox.sh, pkg/operator/ceph/cluster/mgr/spec.go, pkg/operator/ceph/cluster/mon/config.go, pkg/operator/ceph/cluster/mon/env.go, pkg/operator/ceph/cluster/osd/envs.go, pkg/operator/ceph/cluster/osd/provision_spec.go
Environment variables are not recommended for secrets in pods since they can be easily leaked if the environemnt variables are logged. By mounting the mon secret as a file, the mgr and osd prepare pods can read the mon secret from a file for better security.
This in addition to https://github.com/rook/rook/pull/11331 should mean rook is compliant with not using the secrets.
The one exception to this is that the CSI driver and many of the Ceph pods mount the rook-ceph-config secret, but it does not contain confidential information. The secret only contains the mon endpoints, which is necessary to save as a secret for the csi driver.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2144067
**Checklist:**
=> Bug 2144067: core: Read mon secret from file instead of env var

pkg/daemon/ceph/osd/encryption.go, pkg/daemon/ceph/osd/volume.go, pkg/operator/ceph/cluster/osd/config.go, pkg/operator/ceph/cluster/osd/config_test.go, pkg/operator/ceph/cluster/osd/spec.go, pkg/util/exec/exec.go, pkg/util/exec/exec_test.go, pkg/util/exec/test/mockexec.go, pkg/util/exec/translate_exec.go
[osd: re-open encrypted disk during osd-prepare-job if closed](https://github.com/red-hat-storage/rook/commit/f4e3838f812b429a71fd5b789ff48e1cde2aeccb) 
This commit implements this corner case during osd-prepare job.
```
The encrypted block is not opened, this is an extreme corner case
The OSD deployment has been removed manually AND the node rebooted
So we need to re-open the block to re-hydrate the OSDInfo.
Handling this case would mean, writing the encryption key on a
temporary file, then call luksOpen to open the encrypted block and
then call ceph-volume to list against the opened encrypted block.
We don't implement this, yet and return an error.
```
When underlying PVC for osd are CSI provisioned, the encrypted device
is closed when PVC is unmounted …
=> BUG 2153675: osd: Fix osd-prepare-job for encrypted cluster

pkg/daemon/ceph/osd/encryption.go, pkg/daemon/ceph/osd/volume.go, pkg/operator/ceph/cluster/osd/config.go, pkg/operator/ceph/cluster/osd/config_test.go, pkg/operator/ceph/cluster/osd/spec.go, pkg/util/exec/exec.go, pkg/util/exec/exec_test.go, pkg/util/exec/test/mockexec.go, pkg/util/exec/translate_exec.go
[osd: re-open encrypted disk during osd-prepare-job if closed](https://github.com/red-hat-storage/rook/commit/f4e3838f812b429a71fd5b789ff48e1cde2aeccb) 
This commit implements this corner case during osd-prepare job.
```
The encrypted block is not opened, this is an extreme corner case
The OSD deployment has been removed manually AND the node rebooted
So we need to re-open the block to re-hydrate the OSDInfo.
Handling this case would mean, writing the encryption key on a
temporary file, then call luksOpen to open the encrypted block and
then call ceph-volume to list against the opened encrypted block.
We don't implement this, yet and return an error.
```
When underlying PVC for osd are CSI provisioned, the encrypted device
is closed when PVC is unmounted …
=> BUG 2153695: osd: Fix osd-prepare-job for encrypted cluster

deploy/examples/operator-openshift.yaml, pkg/operator/ceph/controller.go, pkg/operator/ceph/webhook-config.go, pkg/operator/ceph/webhook.go
operator: disable webhook by default
disable webhook in the downstream cluster.
operator: adding logs for debugging
adding more logs for debugging
Resolves #
**Checklist:**
=> Bug 2154163: operator: disable webhook by default

pkg/operator/ceph/cluster/cluster.go
Remove checking the version of ceph when using multi cluster api
Resolves #
**Checklist:**
=> core: remove ceph version check for mcs api

.github/workflows/canary-integration-test.yml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/integration-tests-on-release.yaml
(cherry picked from commit 41f36ff9dff7dfb92e447f685d28442d58ac5dbf)
backport of https://github.com/red-hat-storage/rook/pull/462
Resolves #
**Checklist:**
=> ci: stop running ci concurrently when pr is fresh

cmd/rook/ceph/ceph.go, cmd/rook/ceph/mgr.go, cmd/rook/ceph/osd.go, cmd/rook/ceph/osd_test.go, deploy/charts/rook-ceph-cluster/templates/deployment.yaml, deploy/examples/direct-mount.yaml, deploy/examples/osd-purge.yaml, deploy/examples/toolbox-job.yaml, deploy/examples/toolbox.yaml, images/ceph/toolbox.sh, pkg/operator/ceph/cluster/mgr/spec.go, pkg/operator/ceph/cluster/mon/config.go, pkg/operator/ceph/cluster/mon/env.go, pkg/operator/ceph/cluster/osd/envs.go, pkg/operator/ceph/cluster/osd/provision_spec.go, pkg/operator/ceph/cluster/osd/spec.go
This is a backport of #436 and #441. 
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2171963
**Checklist:**
=> [release-4.10] Bug 2171963: core: Remove unnecessary env vars from pod specs

.github/workflows/canary-integration-test.yml, deploy/examples/create-external-cluster-resources.py
if the rge endint is not reachable don't block the creation of rbd and cephfs sc, just print the error instead of raising exception
(cherry picked from commit e44df846871fe048eab6599a5895912ba69f9856)
Resolves #
**Checklist:**
=> Bug 2139451: external: make rgw call separate from cephfs and rbd

pkg/operator/ceph/nfs/spec.go
NFS-Ganesha (as of V5-dev.2 [1]) supports Prometheus monitoring from within the NFS server itself. It provides metrics for both connected clients and active exports, via TCP port 9587. Expose those metrics via existing nfs k8s-service.
[1] https://github.com/nfs-ganesha/nfs-ganesha/commit/b6c59df5a0b8a3ae5b2a87446f8906cb321ee026
Resolves #
**Checklist:**
=> nfs: add support for nfs-ganesha metrics monitoring

.docs/macros/includes/main.py, pkg/operator/ceph/cluster/crash/crash.go, pkg/operator/ceph/cluster/crash/crash_test.go, pkg/operator/ceph/controller/spec.go
The crash collector does not have the command line arguments to run as ceph user id 167, so we set the security context to run as the ceph user in the main crash collector container.
(cherry picked from commit df6d7af355440eab3fae7eea970f9196b5de125f)
Resolves #
**Checklist:**
=> Bug 2167304: security: run the crash collector as ceph user

pkg/operator/ceph/cluster/crash/crash.go, pkg/operator/ceph/cluster/crash/crash_test.go, pkg/operator/ceph/controller/spec.go
The crash collector does not have the command line arguments to run as ceph user id 167, so we set the security context to run as the ceph user in the main crash collector container.
(cherry picked from commit df6d7af355440eab3fae7eea970f9196b5de125f)
Resolves #
**Checklist:**
=> Bug 2180732: security: run the crash collector as ceph user

Documentation/CRDs/Cluster/external-cluster.md, deploy/examples/create-external-cluster-resources.py
if restricted permission was on the . was appended to k8s secret and failed to create the secret so added a alias name is user wan't to suuport pool with . in name
(cherry picked from commit 6c3dabcf5fe9fc131a736072da725727b9108914)
Resolves #
**Checklist:**
=> Bug  2177106: external: add alias rbd pool name to support . pools name

Documentation/CRDs/Cluster/external-cluster.md, deploy/examples/create-external-cluster-resources.py
if restricted permission was on the . was appended to k8s secret and failed to create the secret so added a alias name is user wan't to suuport pool with . in name
(cherry picked from commit 6c3dabcf5fe9fc131a736072da725727b9108914) (cherry picked from commit e98644bee8374b503beb66334f5333733d8ee1be)
Resolves #
**Checklist:**
=> external: add alias rbd pool name to support . pools name

pkg/operator/ceph/object/bucket/controller.go, pkg/operator/ceph/object/controller.go, pkg/operator/ceph/object/notification/controller.go
Skip running Object Bucket and Object bucket notification controllers based on env variable.
(cherry picked from commit e87338fbc48ca564929feb5dc3097fdaf8f69e34) (cherry picked from commit 6cb4dab7d22ad5ecb5f164499e9b174d9248250b)
Resolves #
**Checklist:**
=> Bug 2187765: [4.12 backport] skip OBC and Notification controllers

deploy/examples/create-external-cluster-resources.py
While adding the support for dot and special rbd pools the check for pool and cluster name check was removed, Adding it back as it is needed
https://github.com/rook/rook/pull/12056
(cherry picked from commit f7f88be0821ea649064fc1b5e6988e65676dc876)
Resolves #
**Checklist:**
=> Bug 2177106: external: check for pool and cluster name is provided

pkg/operator/ceph/object/bucket/controller.go, pkg/operator/ceph/object/controller.go, pkg/operator/ceph/object/notification/controller.go
Skip running Object Bucket and Object bucket notification controllers based on env variable.
(cherry picked from commit e87338fbc48ca564929feb5dc3097fdaf8f69e34) (cherry picked from commit 6cb4dab7d22ad5ecb5f164499e9b174d9248250b)
Resolves #
**Checklist:**
=> Bug: 2183266: core: skip OBC and Notification controllers

deploy/examples/create-external-cluster-resources.py
if restricted permission was on the . was appended to k8s secret and failed to create the secret so added a alias name is user wan't to suuport pool with . in name
(cherry picked from commit 6c3dabcf5fe9fc131a736072da725727b9108914) (cherry picked from commit 44c44d637ec7dd0c3991210a82df8dd39ea42e46)
Resolves #
**Checklist:**
=> Bug 2188381: external: add alias rbd pool name to support . pools name

deploy/examples/create-external-cluster-resources.py
1) external: fixed validate_rgw_endpoint pool validation
The function pool_exists seems to only accept a string, but not a List, as it is given in validate_rgw_endpoint.
The change iterates calling pool_exists one by one over the list of pools given in validate_rgw_endpoint. This change made it possible to us to connect our RGW to OCP via Rook.
2) Add missing usage of realm, zone and zonegroup while retrieving user info and adding user capabilities.
Resolves #
**Checklist:**
=> Bug 2192824:  external: fixed validate_rgw_endpoint pool validation

deploy/examples/create-external-cluster-resources.py, pkg/operator/ceph/object/bucket/controller.go, pkg/operator/ceph/object/controller.go, pkg/operator/ceph/object/notification/controller.go
1) external: fixed validate_rgw_endpoint pool validation
The function pool_exists seems to only accept a string, but not a List, as it is given in validate_rgw_endpoint.
The change iterates calling pool_exists one by one over the list of pools given in validate_rgw_endpoint. This change made it possible to us to connect our RGW to OCP via Rook.
2) Add missing usage of realm, zone and zonegroup while retrieving user info and adding user capabilities.
Signed-off-by: Sergio Pérez Fernández <sergioperez794@gmail.com>
(cherry picked from commit a1e604ddd22c15282ea5bdef2f9fff5b3fb781bb)
Resolves #
**Checklist:**
=> Bug 2192821: external: fixed validate_rgw_endpoint pool validation

.github/workflows/canary-integration-test.yml, deploy/examples/create-external-cluster-resources.py
Signed-off-by: Sergio Pérez Fernández <sergioperez794@gmail.com>
(cherry picked from commit a1e604ddd22c15282ea5bdef2f9fff5b3fb781bb)
Resolves #
**Checklist:**
=> Bug 2192823: rgw: fixed validate_rgw_endpoint pool validation

deploy/examples/create-external-cluster-resources.py
if there is no multisite config pass, it will still checks for the zones and zones group and not able to query anything
(cherry picked from commit ec2681f82b0d9767283140113a73b79ce7740a13)
Resolves #
**Checklist:**
=> Bug 2192821: external: fix rgw check if no multisite flag is passed

deploy/examples/create-external-cluster-resources.py
if there is no multisite config pass, it will still checks for the zones and zones group and not able to query anything
(cherry picked from commit ec2681f82b0d9767283140113a73b79ce7740a13)
Resolves #
**Checklist:**
=> Bug 2192823: external: fix rgw check if no multisite flag is passed

deploy/examples/create-external-cluster-resources.py
if there is no multisite config pass, it will still checks for the zones and zones group and not able to query anything
(cherry picked from commit ec2681f82b0d9767283140113a73b79ce7740a13)
Resolves #
**Checklist:**
=> Bug 2192824: external: fix rgw check if no multisite flag is passed

pkg/operator/ceph/cluster/rbd/controller.go
The rbd mirror reconcile was not re-queuing the reconcile if the cephcluster was not initialized. All other controllers waiting for the initialization are requeuing the event, just not the rbd mirror controller.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2208079
**Checklist:**
=> Bug 2208079: rbdmirror: Retry reconcile if cluster not initialized

pkg/operator/ceph/object/admin.go, pkg/operator/ceph/object/admin_test.go, pkg/operator/ceph/object/bucket/provisioner.go, pkg/operator/ceph/object/bucket/util.go, pkg/operator/ceph/object/controller.go, pkg/operator/ceph/object/notification/provisioner.go, pkg/operator/ceph/object/topic/provisioner.go, pkg/operator/ceph/object/user/controller.go
The radosgw-admin command uses the network spec from ceph cluster spec in object context but it is not filled properly in the object package. But with PR 10898, network spec is available in clusterinfo which can be used directly. Also removed cluserspec from object context.
Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>
(cherry picked from commit 1f45cfa581efe79dd6d3ebf589864a4504b8c8de) 
(cherry picked from commit 8fd527cac0dc00f3f97e132cf1e3b5da43dd8c89)
Resolves #
**Checklist:**
=> Bug 2209643: object: use networkspec from clusterinfo spec while running radosgw-admin

pkg/operator/ceph/cluster/osd/provision_spec.go, pkg/operator/ceph/cluster/osd/spec.go, pkg/operator/ceph/controller/spec.go, pkg/operator/ceph/controller/spec_test.go
Signed-off-by: avanthakkar <avanjohn@gmail.com>
Volume "ceph-daemons-sock-dir" is coming empty in case if dataDirHostPath, which is the case for osd onPVC. Fix the volume creation by using the ceph cluster spec dataDirHostPath, which allows to run socket commands on osd containers.
(cherry picked from commit 541d091f9c71f17c59ff3c9a998ff3016c7ec7b2)
Resolves #
**Checklist:**
=> Bug 2203795: core: empty ceph-daemons-sock-dir for osd onPVC

pkg/operator/ceph/cluster/nodedaemon/exporter.go, pkg/operator/ceph/cluster/nodedaemon/exporter_test.go, pkg/operator/ceph/cluster/nodedaemon/reconcile.go
Signed-off-by: avanthakkar <avanjohn@gmail.com>
All regression for ceph-exporter are fixed in downstream Ceph v6.1z2, so enabling the exporter again.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2221488
**Checklist:**
=> Bug 2221488: monitoring: enable exporter for downstream 4.14

pkg/operator/ceph/csi/spec.go
Currently the holder daemonset is never updated which will leaves the images the daemonset also not updated. we should update the daemonset template but not restart the csi holder pods which causes the CSI volume access problem, set the updateStrategy to OnDelete (already set in yaml files) which allow us to update the holder daemonset but not restart/update the pods, when a pod is deleted or node is rebooted the new changes will take effect.
(cherry picked from commit 1ba3aa4d1972c6ecbc9ab3c9ae7ce1a5fbe0e8dc)
Resolves #
**Checklist:**
=> BUG 2222600: csi: update csi holder daemonset template

pkg/operator/ceph/cluster/cephstatus.go, pkg/operator/ceph/cluster/cephstatus_test.go
Force delete rook-ceph-exporter pod that is stuck in terminating state due to unavailability of node.
(cherry picked from commit dd90ef5db24bdea0654ebf04fbf6044ab070fd78)
Resolves #
**Checklist:**
=> Bug 2227161: core: force delete rook-ceph-exporter pod

pkg/operator/ceph/cluster/watcher.go, pkg/operator/ceph/cluster/watcher_test.go
we need to return a valid CIDR IP
to get it fenced properly, the previously
returned one was like `10.63.0.5:0/32` which
is not a valid CIDR, removing `:0` to look like
proper IP CIDR.
(cherry picked from commit eb304a50739cd4aeec5c4fc11f0e10910cac310d)
Resolves #
**Checklist:**
=>  Bug 2235395: core: return valid CIDR ip

pkg/apis/ceph.rook.io/v1/labels.go, pkg/operator/ceph/cluster/mon/health.go, pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/cluster/osd/osd.go, pkg/operator/ceph/cluster/osd/update.go, pkg/operator/ceph/cluster/osd/update_test.go, pkg/operator/ceph/disruption/clusterdisruption/osd.go
During certain maintenance tasks the admin will own running operations on the ceph mons and osds, and the operator should not interfere with those operations. If the operator sees any mon in debug mode, every reconcile and mon health check will be skipped. Thus, mons will not be updated while any one of them is in maintenance. During OSD reconcile, individual OSD deployment updates will only be skipped for OSDs that are actively being debugged.
The debug mode for osd and mon deployments is signaled by creating the ceph.rook.io/do-not-reconcile label.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2233615
**Checklist:**
=> Bug 2233615: core: Operator skips reconcile of mons and osds in debug

pkg/operator/ceph/cluster/mgr/mgr.go, pkg/operator/ceph/cluster/nodedaemon/exporter.go, pkg/operator/ceph/cluster/nodedaemon/reconcile.go, pkg/operator/k8sutil/prometheus.go, pkg/operator/k8sutil/prometheus_test.go
This commit makes the port name configurable to set the port name of the service monitor.
=> Bug 2236444: monitoring: set port for servicemonitor for ceph-exporter

pkg/apis/ceph.rook.io/v1/labels.go, pkg/operator/ceph/cluster/mon/health.go, pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/cluster/osd/osd.go, pkg/operator/ceph/cluster/osd/update.go, pkg/operator/ceph/cluster/osd/update_test.go, pkg/operator/ceph/disruption/clusterdisruption/osd.go
During certain maintenance tasks the admin will own running operations on the ceph mons and osds, and the operator should not interfere with those operations. If the operator sees any mon in debug mode, every reconcile and mon health check will be skipped. Thus, mons will not be updated while any one of them is in maintenance. During OSD reconcile, individual OSD deployment updates will only be skipped for OSDs that are actively being debugged.
The debug mode for osd and mon deployments is signaled by creating the ceph.rook.io/do-not-reconcile label.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2233674
**Checklist:**
=> Bug 2233674: core: operator skips reconcile of mons and osds in debug

pkg/operator/ceph/object/bucket/provisioner.go, pkg/operator/ceph/object/bucket/rgw-handlers.go
If bucket exists for Provision(), then check whether user in the OBC and owner of bucket are same.
Signed-off-by: Jiffin Tony Thottan <thottanjiffin@gmail.com>
(cherry picked from commit b39e813290ab6ed79c27aa14e80f31b4e8730ae9)
Resolves #
**Checklist:**
=> Bug 2228785: object: avoid creating same bucket for two different OBC

pkg/operator/ceph/cluster/nodedaemon/exporter.go, pkg/operator/ceph/cluster/nodedaemon/exporter_test.go, pkg/operator/ceph/cluster/nodedaemon/reconcile.go, pkg/operator/k8sutil/prometheus.go
The crashing of exporter daemons during upgrade from 4.13->4.14 is because in 4.13 we don't have fix required (Ceph upstream fix) which was recelty delivered to 4.14. Thus disabling exporter in 4.13 will resolve this.
Resolves #
**Checklist:**
=> Bug 2237861: Disable exporter 4.13

.github/workflows/canary-integration-test.yml, .github/workflows/canary-test-config/action.yaml, .github/workflows/integration-test-config-latest-k8s/action.yaml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/integration-tests-on-release.yaml, Documentation/CRDs/Cluster/external-cluster.md, deploy/examples/create-external-cluster-resources-tests.py, deploy/examples/create-external-cluster-resources.py, tests/scripts/github-action-helper.sh
when creating networkFence CR, it requires IP's to block which we get from running `rbd status ...` command. But, the client.healthchecker user didn't had the right caps to run hence it was giving error. Now, adding the required caps `profile rbd-read-only` to osd so that rbd command can be executed.
(cherry picked from commit c78bd1cbc61b885ae4a2385ec6432b121dd21f1c) (cherry picked from commit 9ac3442847f2c31bb71ff842c1636dcc25687eb5)
Resolves #
**Checklist:**
=> Bug 2239802: external: update healthchecker caps for rbd command

Documentation/CRDs/Object-Storage/ceph-object-store-crd.md, Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md, deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, deploy/examples/create-external-cluster-resources.py, deploy/examples/object-external.yaml, pkg/apis/ceph.rook.io/v1/types.go
1) donot change rgw fqdn to ip if provided,
As now the bucket class supports the
entry of fqdn
2) update crds with new description in EndpointAddress
(cherry picked from commit f66de7b9df94bdf02b6d38b1a9cb1e4e63fdda81)
Resolves #
**Checklist:**
=> Bug 2189727: external: fqdn should be persisted

Documentation/CRDs/Object-Storage/ceph-object-store-crd.md, Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md, deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, deploy/examples/create-external-cluster-resources-tests.py, deploy/examples/create-external-cluster-resources.py, deploy/examples/object-external.yaml, pkg/apis/ceph.rook.io/v1/types.go
1) donot change rgw fqdn to ip if provided,
As now the bucket class supports the
entry of fqdn
2) update crds with new description in EndpointAddress
(cherry picked from commit f66de7b9df94bdf02b6d38b1a9cb1e4e63fdda81)
Resolves #
**Checklist:**
=> Bug 2229646: external: fqdn should be persisted

pkg/operator/ceph/cluster/watcher.go, pkg/operator/ceph/cluster/watcher_test.go
when creating networkFence, rbd command was loading admin config and hence running rbd command use client.admin in case of external cluster also. With this commit instead of client.admin user it will use what is being passed to config.
(cherry picked from commit ef4dd76df1b8aa64415cef7c45d3d6aaaf8a38a1)
Resolves #
**Checklist:**
=> Bug 2239802: pool: rbd cmd shouldn't use admin in external mode

.github/workflows/helm-lint.yaml, build/csv/csv-gen.sh, build/release/requirements_docs.txt, mkdocs.yml, pkg/operator/ceph/controller/network.go
Use the Rook image (defined by the operator pod) to detect the Multus network address ranges. It is reasonable for users to want to have a minimal Ceph image that does not have the `ip` utility installed, which is used for detecting the address ranges of multus interfaces. Instead, use the Rook image, which Rook can ensure has the `ip` tool if Ceph ever removes it from their image.
Signed-off-by: Blaine Gardner <blaine.gardner@ibm.com>
(cherry picked from commit 8aec30aa5a22a4051db01b4b182fa67a9e2c3960)
Resolves #
**Checklist:**
=> Bug 2245978: multus: use rook image for ip range detection

.github/workflows/canary-integration-test.yml, .github/workflows/daily-nightly-jobs.yml, .github/workflows/encryption-pvc-kms-ibm-kp/action.yml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/integration-tests-on-release.yaml, .github/workflows/rgw-multisite-test/action.yml, pkg/operator/ceph/controller/network.go, pkg/operator/ceph/controller/network_test.go, tests/framework/utils/k8s_helper.go, tests/integration/ceph_base_object_test.go, tests/scripts/github-action-helper.sh
Fix an issue in the network address detection job where placement was only retreived from osd and not merged with all.
Signed-off-by: Blaine Gardner <blaine.gardner@ibm.com>
(cherry picked from commit 0a538bfc37f1c6e5e5dfa6936d9297b37553201a) (cherry picked from commit d829f8c0b16b7c38ca90ca7f3d3b6785424c26f5)
Resolves #
**Checklist:**
=> Bug 2249735: fix multus net detect job all placement

pkg/operator/ceph/cluster/cluster.go, pkg/operator/ceph/cluster/nodedaemon/exporter.go, pkg/operator/ceph/cluster/nodedaemon/keyring.go, pkg/operator/ceph/cluster/nodedaemon/keyring_test.go, pkg/operator/ceph/config/keyring/admin.go, pkg/operator/ceph/config/keyring/volume.go
Similar to the ceph crash collector daemon that generates a keyring with more restrictive privileges, the exporter should also generate and use a more limited keyring.
Signed-off-by: avanthakkar <avanjohn@gmail.com>
(cherry picked from commit 8fa561484a134c396763b359507d997490986389)
Resolves #
**Checklist:**
=> Bug 2248850: exporter: run exporter with specific keyring

pkg/operator/ceph/cluster/nodedaemon/exporter.go
Restarting the exporter using RollingRelease causes a race condition, that results in exporter crashing and the ceph health to show a warning.
This commit, changes the deployment strategy to Recreate. So that we wait for the exporter pods to completely terminate before we create a new one.
=> Bug 2248850: exporter: change deployment strategy to Recreate

pkg/operator/ceph/cluster/nodedaemon/exporter.go, pkg/operator/ceph/cluster/nodedaemon/exporter_test.go, pkg/operator/ceph/cluster/nodedaemon/reconcile.go
All regression for ceph-exporter are fixed in downstream Ceph v6.1z2, so enabling the exporter again.
(cherry picked from commit c5e35cdb110afbe3066a471238c819ee12946208)
Resolves #
**Checklist:**
=> Bug 2255328: Update minimum ceph version required for ceph-exporter daemon

cmd/rook/ceph/osd.go, pkg/daemon/ceph/osd/daemon.go
create the ceph config and keyring file in the osd prepare pod before starting the OSD migration. These files are needed to run any ceph command.
(cherry picked from commit 94953f3f7b81f678ee18c7d793d566f886bc978f)
Resolves #
**Checklist:**
=> Bug 2241268: osd: create config before migration osd

pkg/operator/ceph/nfs/spec.go
In downstream, the RPC liveness probe is available in quincy (17.2.6) which is earlier than its availability upstream (18.2.1). Make a d/s-only patch to reflect this.
This is a similar tactic to what we used here: https://github.com/red-hat-storage/rook/pull/551
**Checklist:**
=> Bug 2257296: nfs: enable the rpc liveness probe in d/s 4.15

pkg/operator/ceph/cluster/osd/osd.go
If migration of the OSDs is enabled, operator should wait for the pgs to be clean after the all the OSDs have reconciled. This will help add the exponential backoff for the operator restarts when OSD migration is needed but PGs are still rebalancing the data after last OSD migration.
(cherry picked from commit 43d3bf147aee36720098e1d653276b0ecbdcfcc1)
Resolves #
**Checklist:**
=> Bug 2259187: osd: wait for the pgs to be clean

pkg/operator/ceph/object/objectstore.go, pkg/operator/ceph/object/objectstore_test.go, tests/framework/clients/object.go, tests/integration/ceph_base_object_test.go
here is the https://go.dev/play/p/SS9Q-dAiIx3 example which says the error handling was wrongly implemented
(cherry picked from commit 46c241433d8722c911bff953dbe8c6c302240a95)
Resolves #
**Checklist:**
=> Bug 2254547: object: improve the error handling for multisite objs

deploy/examples/create-external-cluster-resources.py, pkg/operator/ceph/cluster/nodedaemon/reconcile.go, tests/scripts/pythonwebserver/server.py
The exporter service and service monitor should not be deleted if an individual daemon is being removed from a node. As long as the exporter is enabled with v18 and newer, the exporter service and service monitor should exist. Clusters were seeing their metrics stop collection when the exporter service and service monitor would disappear, especially when multiple clusters are configured.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2258861
**Checklist:**
=> Bug 2258861: exporter: Don't delete exporter service on daemon deletion

.github/workflows/canary-integration-test.yml, .github/workflows/daily-nightly-jobs.yml, .github/workflows/encryption-pvc-kms-ibm-kp/action.yml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/integration-tests-on-release.yaml, .github/workflows/rgw-multisite-test/action.yml, tests/framework/installer/ceph_manifests.go, tests/scripts/github-action-helper.sh
The CI was broken upstream and downstream due to changes in the extra disk used by OSDs. These fixes are needed so we can stabilize the CI and even allow for merging any downstream PRs. 
**Checklist:**
=> ci: fix detection of GH actions extra disk

deploy/examples/create-external-cluster-resources.py
external: include 255 as a valid ip range
external script was checking ip range up to 254
which is incorrect, the valid range is 0-255
and if someone passes 255 it will through error like
```
Out of range IP addresses
```
so including 255 as a valid range.
**Checklist:**
=> Bug 2257371: external: include 255 as a valid ip range

pkg/operator/ceph/cluster/watcher.go, pkg/operator/ceph/cluster/watcher_test.go
this commit updates the name of network fence CR to node name + driver name, which will allow the creation of multiple network fence per drivers on the same node, and modifies the unit test and deletion procedure for the same.
Signed-off-by: Riya Singhal <rsinghal@redhat.com>
(cherry picked from commit c2e3cf367c330fb8714c878eda8b3ae68ecc650a)
core: remove ownerRef from networkFence
since networkFence is a cluster-based resource so that we don't need
the namespace and ownerReferences as it cause garbage-collector errors.
(cherry picked from commit https://github.com/red-hat-storage/rook/commit/2ac418a3b2ba689a53b9ec65596dbe225c0dce89)
(cherry picked from commit https://github.com/red-hat-storage/rook/commit/0113cc85c53564dcd5adb818a53b05a47aa7614 …
=> Bug 2259668: csi: update network fence CR name

.github/workflows/canary-integration-test.yml, deploy/examples/create-external-cluster-resources.py
we have changed the --cluster-name flag to --k8s-cluster-name but to support automation while upgrade we should support the legacy flag
(cherry picked from commit 8e4ec01cbb1c64ef3cbc5e4822a9e2e34adf9c5f)
Resolves #
**Checklist:**
=> Bug 2244609: external: honour support of cluster-name legacy flag

deploy/charts/rook-ceph/templates/clusterrole.yaml, deploy/examples/common.yaml, pkg/operator/ceph/cluster/controller.go, pkg/operator/ceph/cluster/controller_test.go, pkg/operator/ceph/cluster/watcher.go, pkg/operator/ceph/cluster/watcher_test.go, pkg/operator/ceph/csi/csi.go
since networkFence is a cluster-based resource so that we don't need the namespace and ownerReferences as it cause garbage-collector errors. Also, now we create the networkFence with clusteUID label so when doing cleanup we match the cephCluster uid and networkFence label clusterUID.
(cherry picked from commit 5bff860380f34d1aa1ee9dceb9bcb2ed5d64da58)
**Checklist:**
=> Bug 2262070: core: remove namespace/ownerRef from networkFence

pkg/operator/ceph/cluster/watcher.go, pkg/operator/ceph/cluster/watcher_test.go
The cephfs PVC might exist on the kubernetes node object but due to some timing issues the ip might not be visible on the ceph cluster or the client might have already been evicted or disconnected from the ceph cluster. In this case, we will not be able to get IP details for the subvolume and we don't have any check for empty ip's in the code rook tries to create NetworkFence CR with an empty Ip's, and the NetworkFence will get moved to the Failed state. This PR adds the necessary checks and logging to prevent this one.
Backport of https://github.com/rook/rook/pull/13768
=> BUG 2259668: core: Continue processing PVs for network fencing when no node IPs found

go.mod, go.sum, pkg/apis/go.mod, pkg/apis/go.sum, pkg/operator/ceph/cluster/watcher.go, pkg/operator/ceph/cluster/watcher_test.go
Please check individual commits.
**Checklist:**
=> Bug 2265124: csi: remove cephFs networkFence code temporarily

images/ceph/Dockerfile, pkg/operator/ceph/csi/cluster_config.go, pkg/operator/ceph/csi/cluster_config_test.go
During cluster creation, csi config map was first filled with mon ips and without CSIDriverOptions.
This commit makes sure CSIDriverOptions are added at the begining when the entry is first created.
(cherry picked from commit 330f604cca1384b763bce629626b75fce6f73bd4)
**Checklist:**
=> BUG 2265514: csi: update CSIDriverOption params during saving cluster config

pkg/operator/ceph/cluster/nodedaemon/reconcile.go
The exporter service and service monitor should not be deleted if an individual daemon is being removed from a node. As long as the exporter is enabled with v18 and newer, the exporter service and service monitor should exist. Clusters were seeing their metrics stop collection when the exporter service and service monitor would disappear, especially when multiple clusters are configured.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2262307
**Checklist:**
=> Bug 2253429: exporter: Don't delete exporter service on daemon deletion

.github/workflows/build.yml, Makefile, build/csv/ceph/ceph.rook.io_cephblockpoolradosnamespaces.yaml, build/csv/ceph/ceph.rook.io_cephblockpools.yaml, build/csv/ceph/ceph.rook.io_cephbucketnotifications.yaml, build/csv/ceph/ceph.rook.io_cephbuckettopics.yaml, build/csv/ceph/ceph.rook.io_cephclients.yaml, build/csv/ceph/ceph.rook.io_cephclusters.yaml, build/csv/ceph/ceph.rook.io_cephcosidrivers.yaml, build/csv/ceph/ceph.rook.io_cephfilesystemmirrors.yaml, build/csv/ceph/ceph.rook.io_cephfilesystems.yaml, build/csv/ceph/ceph.rook.io_cephfilesystemsubvolumegroups.yaml, build/csv/ceph/ceph.rook.io_cephnfses.yaml, build/csv/ceph/ceph.rook.io_cephobjectrealms.yaml, build/csv/ceph/ceph.rook.io_cephobjectstores.yaml, build/csv/ceph/ceph.rook.io_cephobjectstoreusers.yaml, build/csv/ceph/ceph.rook.io_cephobjectzonegroups.yaml, build/csv/ceph/ceph.rook.io_cephobjectzones.yaml, build/csv/ceph/ceph.rook.io_cephrbdmirrors.yaml, build/csv/ceph/objectstorage-provisioner-role-binding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, build/csv/ceph/objectstorage-provisioner-role_rbac.authorization.k8s.io_v1_clusterrole.yaml, build/csv/ceph/objectstorage-provisioner_v1_serviceaccount.yaml, build/csv/rook-ceph.clusterserviceversion.yaml, deploy/examples/operator-openshift.yaml, deploy/olm/assemble/metadata-common.yaml, deploy/olm/assemble/metadata-ocp.yaml, images/ceph/Dockerfile, images/ceph/Makefile, tests/scripts/validate_modified_files.sh
build: add gen-csv files in downstream repo
This commit add the csv related changes to downstream and
later will be removed from upstream also renaming make 'csv'
to 'gen-csv' and also adds validation check in ci to verify
right files are modified.
build: add csv envs to rook deploy envs
moving all the default envs which were part of
ocs-op rook csv to operator deployment.
build: these are auto-generated files
This commit contains auto-generated files
that are added/modified by running 'make gen-csv'.
**Checklist:**
=> build: add gen-csv files in downstream repo

Dockerfile.bundle, Makefile, build/bundle/annotations.yaml, build/bundle/gen-bundle.sh, build/common.sh, build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml, build/csv/csv-gen.sh, deploy/olm/assemble/metadata-common.yaml
- Added Dockerfile to create rook-ceph-operator-bundle under the rook repo.
- Updated the Makefile to have the 'bundle' command, that reference the 'gen-bundle.sh' script under `build/bundle`.
- Moved the rook csv under build/csv/ceph directory to keep all the manifests at one location for bundle creation
**Checklist:**
=> Added new rook bundle creation script

build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml, deploy/examples/operator-openshift.yaml
Added the new stanza to `deploy/examples/operator-openshift.yaml` and ran `make gen-csv`
We are going to update the configmap from ocs-operator to disable the CSI during runtime and these values are required for rook to realize the update.
=> build: add new env value ref for operator

build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml, build/csv/csv-gen.sh, deploy/examples/operator-openshift.yaml, deploy/olm/assemble/metadata-common.yaml
build: add all the csi image version in csv
add all the csi related images version in csv which
ocs-operator csv merger tool was changing.
build: These are auto-generated csv changes
these are auto-generated csv changes when run
`make gen-csv`.
**Checklist:**
=> Add all the csi env

Documentation/Helm-Charts/operator-chart.md, build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml, deploy/charts/rook-ceph/templates/configmap.yaml, deploy/charts/rook-ceph/values.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, pkg/operator/ceph/csi/controller.go
added a new flag ROOK_CSI_DISABLE_DRIVER
to disable csi controller.
(cherry picked from commit a72e02945978a2a115207d6ea40e14223d8af4a6)
**Checklist:**
=> csi: add a new flag to disable csi driver

.commitlintrc.json, build/common.sh, build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml
=> csv: update csv version to 4.16

.github/workflows/push-build-downstream.yaml, tests/scripts/build-release-downstream.sh
we have some changes related to downstream
so we need to have a separate downstream image
so the ocs operator ci can make use of it
**Checklist:**
=> ci: push downstream image to ocs/dev

pkg/operator/ceph/cluster/mon/drain.go, pkg/operator/ceph/cluster/mon/drain_test.go
If the spec.mon.count is 5 or more, then create
mon pdbs with maxUnavailable count as 2. We can
afford to have more than 1 mons down while
draining the nodes in this case.
(cherry picked from commit a4866b4b066ec87c26cee0ba930338e8b5c467a4)
**Checklist:**
=> Bug 2264553: mon: set mon pdb max unavailable as 2 in case of 5 or more mons

Documentation/CRDs/specification.md, build/csv/ceph/ceph.rook.io_cephblockpoolradosnamespaces.yaml, build/csv/ceph/ceph.rook.io_cephfilesystemsubvolumegroups.yaml, deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, pkg/apis/ceph.rook.io/v1/resources.go, pkg/apis/ceph.rook.io/v1/types.go, pkg/client/informers/externalversions/factory.go, pkg/daemon/ceph/client/subvolumegroup.go, pkg/daemon/ceph/osd/kms/kmip.go, pkg/daemon/util/cmdreporter_test.go, pkg/operator/ceph/controller/cluster_info.go, pkg/operator/ceph/controller/cluster_info_test.go, pkg/operator/ceph/file/subvolumegroup/controller.go, pkg/operator/ceph/file/subvolumegroup/controller_test.go, pkg/operator/ceph/predicate.go
PR containing the latest commits from upstream master branch
=> Syncing latest changes from upstream master for rook

pkg/operator/ceph/cluster/cluster_external.go, pkg/operator/ceph/controller/cluster_info.go, pkg/operator/ceph/controller/cluster_info_test.go, pkg/operator/ceph/csi/cluster_config.go, pkg/operator/ceph/csi/cluster_config_test.go, pkg/operator/ceph/csi/controller.go, pkg/operator/k8sutil/resources.go
This backport comprises 3 commits that address the BZ on multiple fronts.
Commit 2 (below) is the root cause fix. This fix was developed upon noticing that the bug was expressed when non-CSI controllers attempted to update the `rook-ceph-csi-config` configmap before it was created/initialized. On top of that, those non-CSI controllers were using an incorrect OwnerReference to init the configmap. With this change, the `rook-ceph-csi-config` configmap is only created by the main CSI controller, which does so with the correct owner reference. All other controllers will now wait for the configmap to exist before continuing. 
Commit 1 (below) is a fix that ensures any existing, brownfield ODF clusters are not affected by the "incorrect OwnerReference" issue mentioned above. This commit edits …
=> BUG 2275886: Fix OwnerReferences on CSI config map

pkg/operator/ceph/csi/cluster_config.go, pkg/operator/ceph/csi/controller.go
Creating a cluster never succeeds if CSI driver is disabled So to fix that we need to always create the csi configmap
closes: https://github.com/rook/rook/issues/14123
(cherry picked from commit 47ed6a863268940f90e3701de6a77535a2a60147) (cherry picked from commit 91292df78b5a419365101265bf53ac32709cd7c4)
**Checklist:**
=> Bug 2276591: csi: create csi configmap if csi controller is disabled

pkg/operator/ceph/cluster/cluster_external.go, pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/csi/cluster_config.go, pkg/operator/ceph/csi/cluster_config_test.go, pkg/operator/ceph/csi/spec.go, pkg/operator/ceph/file/subvolumegroup/controller.go, pkg/operator/ceph/pool/radosnamespace/controller.go
csi: fix missing namespace bug in csi cluster config map
Someone testing the Multus holder pod removal feature encountered an
issue where the migration process failed to lead to a system state where
PVCs could be created successfully.
The root cause was found to be a ceph csi config map wherein the primary
CephCluster entry was lacking a value for the "namespace" field.
I observed this once in my development on the holder pod removal
feature, but I was unable to reproduce and assumed it was my own error.
Since this has been seen in a user environment, it must be that the
error is a race condition, and I am unable to determine the exact source
of the bug.
I do not believe this bug would be present if the code that updates the
CSI configmap were properly idempotent, but it has many …
=> BUG 2278606: csi: fix missing namespace bug in csi cluster config map

.github/workflows/golangci-lint.yaml, build/csv/ceph/ceph.rook.io_cephclusters.yaml, deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, pkg/apis/ceph.rook.io/v1/types.go, pkg/operator/ceph/cluster/osd/deviceSet.go, pkg/operator/ceph/cluster/osd/deviceset_test.go
there are some cases where storageClassDeviceSets length are more 63 chars and osd provisioned failed due to this. with error
```
failed to run osd provisioning job for PVC "ocs-deviceset-*-local-volume-storageclass-0-data-*": Job.batch "rook-ceph-osd-prepare-*" is invalid: [spec.template.spec.volumes[10].name: Invalid value: "ocs-deviceset-*-local-volume-storageclass-0-data-*": must be no more than 63 characters, spec.template.spec.containers[0].volumeMounts[9].name: Not found: "ocs-deviceset-*-local-volume-storageclass-0-data-*",
```
Using x-validator to limit the maxLength to the deviceClassSet.Name to 40 chars and adding code check that overall pvc name should be less than 63 chars. …
=> Bug 2269099: osd: limit storageClassDeviceSets to 63 chars

Documentation/Helm-Charts/operator-chart.md, deploy/charts/rook-ceph/templates/configmap.yaml, deploy/charts/rook-ceph/values.yaml, deploy/examples/operator-openshift.yaml, deploy/examples/operator.yaml, pkg/operator/ceph/csi/controller.go
added a new flag ROOK_CSI_DISABLE_DRIVER
to disable csi controller.
(cherry picked from commit a72e02945978a2a115207d6ea40e14223d8af4a6)
**Checklist:**
=> Bug 2279992: csi: add a new flag to disable csi driver

Documentation/CRDs/specification.md, build/csv/ceph/ceph.rook.io_cephclusters.yaml, deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, pkg/apis/ceph.rook.io/v1/types.go, pkg/operator/ceph/cluster/osd/osd.go, pkg/operator/ceph/cluster/osd/spec.go
LVM-based OSDs on PVCs are legacy and are not well tested. Therefore, we add status to the cephcluster CR that at least gives a clue that the OSDs should be replaced.
(cherry picked from commit 3628e83892a631dc56f6c42e877e03b0a71d8628) (cherry picked from commit 5a34cd9f9e7fa2aa07dc5ab5f23078ee1968b73f)
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2274757
**Checklist:**
=> Bug 2274757: osd: Add cephcluster status for legacy osds to replace

pkg/operator/ceph/controller/cleanup.go
Removed owner reference from Radosnamespace and
subVolumeGroup cleanup resources.
(cherry picked from commit c98fc8691881a9af1a077df923ef6544c7c5de3d)
**Checklist:**
=> Bug 2280946: core: remove owner refs in resource cleanup jobs

pkg/operator/ceph/file/subvolumegroup/controller.go
SVG cleanup job uses the cephSubvolumeGroup env name from spec.Name. But sometimes it can be empty. In that case rook should use the CR name.
(cherry picked from commit 33ce8f0c8e31ba7f5acf24c7854465ff32eca437)
**Checklist:**
=> Bug 2281580: core: fix missing env in svg cleanup job

pkg/operator/ceph/cluster/mon/spec.go, pkg/operator/ceph/cluster/mon/spec_test.go
When IPv6-only network mode is enabled and when mons are configured to listen only on msgrV2 port, Rook has to add the port to the mon --public-bind-addr in order to force mons to stop listening on the msgrV1 port. This can cause problems for IPv6 clusters where adding ':<port>' to the end of an IP addr looks like a valid IPv6 address.
In IPv6 mode, Rook needs to set this to '[<ip>]:<port>' with the brackets to be a non-ambiguous IPv6 address.
In IPv4 mode, Rook needs to keep its existing behavior. IPv4 mode should also continue to be the defualt assumption if the network config isn't specified.
If 'dualStack: true' is specified, Rook is informed that the environment is dual stack, but Rook doesn't know which IP family to expect from the pod IP. In this scenario, it is safest for Rook not …
=> BUG 2282254: mon: fix bind addr when IPv6 and msgr2 are enabled

build/csv/ceph/ceph.rook.io_cephclusters.yaml, deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, images/ceph/Dockerfile, pkg/apis/ceph.rook.io/v1/types.go, pkg/operator/ceph/cluster/osd/deviceSet.go, pkg/operator/ceph/cluster/osd/deviceset_test.go
This commits reverts changes done to limit the storageClassDeviceSets Name for 4.16 due to upgrade issues.
There is another commit added in this pr `build: remove iproute build dependency on centos repo` so that most of the build and e2e CI is green
**Checklist:**
=> Bug 2293881: osd: revert limit storageClassDeviceSets to 63 chars

pkg/daemon/ceph/osd/encryption.go
While adding a new encryption key to slot 1
if there exists a key in slot 1 which is not
equal to the one we want to update it with,
we kill the slot and then add the new key to it.
While killing the slot, the existing code uses
the new key, which is not valid in such cases.
This patch modifies the code to use the key in
slot 0 (the one that we know works) to kill the slot.
=> BUG 2293621: osd: use old passphrase to kill the luks slot

pkg/daemon/ceph/client/pool.go, pkg/daemon/ceph/client/pool_test.go
Pools in stretch clusters must all specify the same CRUSH rule. No pools can use a different rule. When there is a change in the device class, we do not even expect to update the crush rules in a stretch cluster. Different device classes are not supported in stretch clusters, and it's expected to be a homogenous environment. Therefore, skip all crush rule updates in stretch clusters.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2296991
**Checklist:**
=> Bug 2296991: pool: Skip updating crush rules for stretch clusters

deploy/examples/create-external-cluster-resources.py
currently we created a new config file or user creation, Which was have the user config.
We were also appending the script deafult values to the config file With that all the boolean values were appended to the config.ini file
v2-port-enable = False
....
But the config.ini treat all the bolean values as true, irrespective of they are set to, it is  because the boolean cli flag doesnt accept the argument
So now removed all the false values from the config.ini
(cherry picked from commit d2f8ce4c476cbf69dc9fea6515ff535049192050) (cherry picked from commit 388975cfa4d0bd5aed0be9a18545d5153a326220)
**Checklist:**
=> Bug 2306577: external: remove the false bool values from config file

pkg/operator/ceph/cluster/osd/osd.go
This flag is turned on specially for downstream for 4.16
**Checklist:**
=> Bug 2295778: osd: allow the AllowOsdCrushWeightUpdate flag always true

pkg/operator/ceph/cluster/nodedaemon/exporter.go, pkg/operator/ceph/cluster/nodedaemon/exporter_test.go
Previously ceph-exporter would only bind to IPv4 interfaces. Now if the CephCluster is configured with `dualStack: true` and/or `ipFamily: IPv6` an additional flag (`--addrs ::`) will be added to the ceph-exporter container to make it listen both IPv6 and IPv4 interfaces.
Signed-off-by: Matthew Penner <me@matthewp.io>
(cherry picked from commit d09a43df3789652d7932933d1fadf2597342d7f5) (cherry picked from commit 9744c97227af25b4ca4320428d204938c31f435f)
**Checklist:**
=> Bug 2297285: exporter: bind to all interfaces if IPv6 is enabled

.github/workflows/canary-integration-test.yml, Documentation/CRDs/Cluster/external-cluster.md, deploy/examples/create-external-cluster-resources-tests.py, deploy/examples/create-external-cluster-resources.py
it was confusing if we are calling a ceph cluster name or k8s cluster name, so re-named
(cherry picked from commit 98c4567219198e8d13f35ed4c75b6ff000c3d12e)
Resolves #
**Checklist:**
=>  Bug 2268174: external: change cluster_name to k8s_cluster_name

pkg/operator/ceph/cluster/mon/health.go, pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/cluster/mon/mon_test.go
When removing a mon from quorum, there is a race condition that can result in mon quorum going being lost at least temporarily. The mon pod was being deleted first, and then the mon removed from quorum. If any other mon went down between the time the pod of the bad mon was deleted and when the mon was removed from quorum, there may not be sufficient quorum to complete the action of removing the mon from quorum and the operator would be stuck.
For example, there could be 4 mons temporarily due to timing of upgrading K8s nodes where mons may be taken down for some number of minutes. Say a new mon is started while the down mon also comes back up. Now the operator sees it can remove the 4th mon from quorum, so it starts to remove it. Now say another mon goes down on another node that is being …
=> Bug 2292435: mon: Remove extra mon from quorum before taking down pod

deploy/examples/create-external-cluster-resources.py
there is a hardcoded value of "client.healthchecker" which needs to be replaced by self.run_as_user
(cherry picked from commit 8d89faf615d9437ff2b66e8f12aec70c1958b14f)
Resolves #
**Checklist:**
=> Bug 2254345: [release-4.14] external - fix the run as a user flag

pkg/operator/ceph/file/filesystem.go, pkg/operator/ceph/file/filesystem_test.go
Only single pool will get created if there are multiple data pool entries with same name. This PR just adds a check to fail if duplicate pools are present.
(cherry picked from commit 8fa8612201a153b7979a71ac42bdca6337bdb416)
**Checklist:**
=> Bug 2297454: core: check for duplicate ceph fs pool names

pkg/operator/ceph/csi/controller.go
ROOK_CSI_DISABLE_DRIVER was not working accurate
from https://github.com/rook/rook/pull/14489
The csi driver was installed even if its not
expected
(cherry picked from commit 166e4f35b2364121403b1c5a2d55e02e06482056)
**Checklist:**
=>  Bug 2313736: csi: fix the disable driver flag in the csi driver reconcile

pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-holder.yaml, pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml, pkg/operator/ceph/csi/template/csi-logrotate-sidecar.yaml, pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-holder.yaml, pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-provisioner-dep.yaml, pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-holder.yaml, pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
deployments on openshift where we need csi container pods
to be run on privileged, the logrotate sidecar container was missing the
privileged permission letting, side car to not run properly
**Checklist:**
=> Bug 2315733: csi: add sc privileged to logrotate sidecar container

pkg/daemon/ceph/client/pool.go, pkg/operator/ceph/file/filesystem.go, pkg/operator/ceph/object/objectstore.go, pkg/operator/ceph/pool/controller.go, pkg/operator/ceph/pool/controller_test.go
Default application name is updated inside the `CreatePool` method. Send pool spec as address in order to preserve this change.
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2310332
**Checklist:**
=> Bug 2310332: core: Preserve pool application name change

pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/cluster/mon/mon_test.go, pkg/operator/ceph/file/mds/livenessprobe.go, pkg/operator/ceph/file/mds/livenessprobe.sh
1) When the MDS liveness probe times out, it should not fail the probe. If
the cluster has a network partition or other issue that causes the Ceph
mon cluster to become unstable, `ceph ...` commands can hang and cause
a timeout. In this case, the MDS should not be restarted so as to not
cause cascading cluster disruption.
2) If the mon failover is in progress, ensure the removal
of an extra mon deployment is skipped since that code
path only has one mon in the list for the mon that was
just newly started. The extra mon was erroneously removing
a random mon in that case, followed immediately by the mon
failover completing and removing the expected failed mon,
and potentially causing mon quroum loss.
**Checklist:**
=> Bug 2315624: Fix mds liveness probe and mon failover

deploy/examples/create-external-cluster-resources.py
for 4.18 we will use the default v2 settings from the cluster CR So ask python script to fetch only v2 port
**Checklist:**
=> external: enable the v2 port by default in downstream

Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md, Documentation/Troubleshooting/ceph-csi-common-issues.md, pkg/operator/ceph/cluster/watcher.go
Disabling the RBD and CephFS fencing
in Rook for now as its having bugs where
Rook is blocklisting wrong IP address
due to timing issues.
(cherry picked from commit 1d1ed5e9629b3c7acccfd63627aaa839b1b2fefa) (cherry picked from commit 34f81ec820e1b6794d664bddf628754e1c99ccce)
Resolves #https://bugzilla.redhat.com/show_bug.cgi?id=2315666
**Checklist:**
=> Bug 2315666: csi: Disable fencing in Rook

pkg/daemon/ceph/client/mirror.go
in downstream ceph min version supported is 19.2.0 for rbd mirroring for rados namesapce
**Checklist:**
=> core: change ceph min version for rbd mirroring

pkg/operator/ceph/cluster/osd/osd.go
MustDelete DeleteOption was set to `true` when deleting osd-repalce-config configMap.  This cm won't existing after all the OSDs get migrated. So deletion of the non-existent cm will result in error. This PR removes `mustDelete: true` from the DeletionOption when deleting osd-replace-config configmap
(cherry picked from commit 8dd237b460b589315f198e7885611e4926842750)
**Checklist:**
=> Bug 2319102:  core: fix deletion of the osd-replace-config cm

build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml, deploy/examples/operator-openshift.yaml
Removed CSI_DISABLE_HOLDER_PODS from the operator deployment files.
**Checklist:**
=> multus: remove csi holder pods key

pkg/operator/ceph/object/s3-handlers.go, pkg/operator/ceph/object/s3-handlers_test.go
**Backport of https://github.com/rook/rook/pull/14911 (https://github.com/rook/rook/pull/14835) to release-4.17**
When generating the HTTP client used for RGW admin ops, use both system certs as well as the user-given cert.
As a real world example, admins may use ACME to rotate Letsencrypt certs every 2 months. For an external CephObjectStore, the cert used by Rook and RGW may not be rotated at the same time. This can cause the Rook operator to fail CephObjectStore reconciliation until both certs agree.
When Rook also relies on system certs in the container, Rook's reconciliation will not have reconciliation failures because Letsencrypt's well-known and trusted root certificates can be loaded from the system to validate the RGW's newly-rotated cert.
Signed-off-by: Blaine Gardner …
=> DFBUGS-825: object: also use system certs for validating RGW cert

pkg/operator/ceph/object/s3-handlers.go, pkg/operator/ceph/object/s3-handlers_test.go, tests/scripts/github-action-helper.sh
**Backport of https://github.com/rook/rook/pull/14911 (https://github.com/rook/rook/pull/14835) to release-4.16**
When generating the HTTP client used for RGW admin ops, use both system certs as well as the user-given cert.
As a real world example, admins may use ACME to rotate Letsencrypt certs every 2 months. For an external CephObjectStore, the cert used by Rook and RGW may not be rotated at the same time. This can cause the Rook operator to fail CephObjectStore reconciliation until both certs agree.
When Rook also relies on system certs in the container, Rook's reconciliation will not have reconciliation failures because Letsencrypt's well-known and trusted root certificates can be loaded from the system to validate the RGW's newly-rotated cert.
Signed-off-by: Blaine Gardner …
=> DFBUGS-342: object: also use system certs for validating RGW cert

.github/workflows/codespell.yaml, design/ceph/osd-migration.md, pkg/operator/ceph/cluster/osd/osd_test.go, pkg/operator/ceph/pool/controller_test.go
the unit test ws failing, as in 4.16
we were setting the osd resize manually true,
So the re-weight was called twice once from the
device class update and another from osd reweight
**Checklist:**
=> DFBUGS-901: ci: fix ci issue downstream

Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md, Documentation/Troubleshooting/ceph-csi-common-issues.md, pkg/operator/ceph/cluster/watcher.go
Disabling the RBD and CephFS fencing
in Rook for now as its having bugs where
Rook is blocklisting wrong IP address
due to timing issues.
(cherry picked from commit 1d1ed5e9629b3c7acccfd63627aaa839b1b2fefa) (cherry picked from commit 34f81ec820e1b6794d664bddf628754e1c99ccce) (cherry picked from commit fc94e11155569d4aa4f721320c8cfb965fe7a9ad)
**Checklist:**
=> DFBUGS-978: csi: disable fencing in Rook

build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml, deploy/examples/operator-openshift.yaml
use the value from ocs operator config by
using the calue from operator env ROOK_CSI_ENABLE_CEPHFS
refer: https://github.com/red-hat-storage/ocs-operator/pull/2970
**Checklist:**
=> csv: use ROOK_CSI_ENABLE_CEPHFS in rook operator env

build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml, pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/controller/controller_utils.go, pkg/operator/ceph/controller/controller_utils_test.go, pkg/operator/ceph/file/controller_test.go, pkg/operator/ceph/object/objectstore.go, tests/scripts/multus/host-cfg-ds.yaml
There is a race condition in ceph v19 at startup of a stretch cluster where if the .mgr pool is created by the mgr pod after stretch mode is entered, the devicehealth mgr module will crash and cause a ceph HEALTH_ERR. The error then causes rook reconcile of all CRs to be skipped because Rook is assuming admin intervention is needed to continue. The fix is to wait until the .mgr pool is created by the mgr pod before entering stretch mode.
At the same time, we suppress mgr module health errors during reconcile. Some ceph health errors should not block the reconcile of the cluster. Mgr modules do not have cause to block the reconcile, as the cluster can usually work even if a module is failing.
**Checklist:**
=> DFBUGS-1696: mgr: Wait for builtin mgr pool to exist before enabling stretch

pkg/operator/ceph/cluster/cluster_external.go, pkg/operator/ceph/file/subvolumegroup/controller.go, pkg/operator/ceph/pool/radosnamespace/controller.go
In downstream external mode, we'll only create required csi-operator resources like ceph connection and client profile CR's.
**Checklist:**
=> csi: create only required resource in external mode

pkg/operator/ceph/csi/controller.go, pkg/operator/ceph/csi/csi.go, pkg/operator/ceph/csi/spec.go
in upgrade case, if there is csi driver already created by other owners and disableCSI is changed `true` and EnableUseCSIOperator and is `false`. Rook was deleting the CSI driver object. So, with my code changes, the csi driver object will be deleted where it is required and not all the time when we are deleting the older csi resources.
**Checklist:**
=> csi: let's not delete csi driver object

build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml, deploy/charts/rook-ceph/templates/clusterrole.yaml, deploy/examples/common.yaml
a newly dynamic dns resolution code
was added by https://github.com/rook/rook/pull/15522
Fixing rbac of it, as current rbac needs
a sub resource `restricted`
**Checklist:**
=> mon: fix mon rbac for endpoint slice

pkg/operator/ceph/object/spec.go, pkg/operator/ceph/object/spec_test.go
rgw ReadAffinity is also supported for v.19 in ceph downstream. This PR removes the ceph version requirement 4.19 ODF
**Checklist:**
=> rgw: remove v20 check for rgw-readaffinity

pkg/daemon/ceph/client/mirror.go
implicit mirroring is enable from 19.2.1 and we had wrong check with ceph tentacle 20.0.0
**Checklist:**
=> rbdmirror: relax ceph version for implict mirroring

pkg/daemon/ceph/client/status.go, pkg/daemon/ceph/client/status_test.go
Ceph uses uint64 (unsigned long) type for CephFS GID. Rook was using int, which was causing failures when the GID overflowed Rook's type. Update Rook's type to match Ceph's.
Signed-off-by: Blaine Gardner <blaine.gardner@ibm.com>
(cherry picked from commit 5b27189ac44200320144cc7193abaceddb645a34) (cherry picked from commit 1a670a26adeeffac3189c061e8053a7e198b52c4)
**Checklist:**
=> core: update cephstatus fsmap gid type to uint64

go.mod, go.sum
jwt-go allows excessive memory allocation during header parsing
https://bugzilla.redhat.com/show_bug.cgi?id=2354195
golang-jwt is a Go implementation of JSON Web Tokens. Prior to
5.2.2 and 4.5.2, the function parse.ParseUnverified splits (via a call to strings.Split) its argument (which is untrusted data) on periods. As a result, in the face of a malicious request whose Authorization header consists of Bearer followed by many period characters, a call to that function incurs allocations to the tune of O bytes (where n stands for the length of the function's argument), with a constant factor of about 16. This issue is fixed in 5.2.2 and 4.5.2.
**Checklist:**
=> DFBUGS-1912: [release 4.18] core: CVE-2025-30204: rook-ceph-operator-container: jwt-go allows excessive memory allocation during header parsing

go.mod, go.sum
jwt-go allows excessive memory allocation during header parsing
https://bugzilla.redhat.com/show_bug.cgi?id=2354195
golang-jwt is a Go implementation of JSON Web Tokens. Prior to
5.2.2 and 4.5.2, the function parse.ParseUnverified splits (via a call to strings.Split) its argument (which is untrusted data) on periods. As a result, in the face of a malicious request whose Authorization header consists of Bearer followed by many period characters, a call to that function incurs allocations to the tune of O bytes (where n stands for the length of the function's argument), with a constant factor of about 16. This issue is fixed in 5.2.2 and 4.5.2.
(cherry picked from commit ef88e12f457d0d0af31d0bf6027bcb5a0451be71)
**Checklist:**
=> DFBUGS-1909: [release 4.16] core: cve 2025 30204 rook-ceph-operator-container: jwt-go allows excessive memory allocation during header parsing

pkg/daemon/ceph/client/mirror_health.go
there was very edge case,a nd that result in nil
point exception
During osd upgrades if mirror health check is called the mirror status cmd doesnt respond
So its important to check if the value exist
before getting its summary
(cherry picked from commit 0c5d3ee3a56573904d56ad4a7080c7fe2128e428)
**Checklist:**
=> DFBUGS-2089: rbdmirror: fix the rados namespace health checkup

.github/workflows/build.yml, .github/workflows/canary-integration-test.yml, .github/workflows/codegen.yml, .github/workflows/codespell.yaml, .github/workflows/commitlint.yml, .github/workflows/crds-gen.yml, .github/workflows/create-tag.yaml, .github/workflows/daily-nightly-jobs.yml, .github/workflows/docs-check.yml, .github/workflows/integration-test-helm-suite.yaml, .github/workflows/integration-test-mgr-suite.yaml, .github/workflows/integration-test-multi-cluster-suite.yaml, .github/workflows/integration-test-object-suite.yaml, .github/workflows/integration-test-smoke-suite.yaml, .github/workflows/integration-test-upgrade-suite.yaml, .github/workflows/integration-tests-on-release.yaml, .github/workflows/mod-check.yml, .github/workflows/push-build.yaml, .github/workflows/rbac-gen.yaml, .github/workflows/stale.yaml, .github/workflows/unit-test.yml, cmd/rook/ceph/cleanup.go
Cleanup job cli was not reading the flags correctly. As a result, dataDirHostPath was never cleaned up.
(cherry picked from commit a44a22216ff4d0550f116a3a969a5c7e3a657681)
**Checklist:**
=> DFBUGS-714: core: fix reading flags in cleanup job cmd

Documentation/CRDs/specification.md, build/csv/ceph/ceph.rook.io_cephblockpoolradosnamespaces.yaml, deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, pkg/apis/ceph.rook.io/v1/namespace.go, pkg/apis/ceph.rook.io/v1/pool.go, pkg/apis/ceph.rook.io/v1/types.go, pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go, pkg/daemon/ceph/client/mirror.go, pkg/daemon/ceph/client/pool.go, pkg/daemon/ceph/client/radosnamespace.go, pkg/operator/ceph/pool/controller.go, pkg/operator/ceph/pool/controller_test.go, pkg/operator/ceph/pool/dependents.go, pkg/operator/ceph/pool/radosnamespace/controller.go, pkg/operator/ceph/pool/radosnamespace/controller_test.go, pkg/operator/ceph/reporting/reporting.go, pkg/operator/ceph/reporting/status.go, pkg/operator/ceph/reporting/status_test.go, pkg/util/dependents/dependents.go
1. BlockPool CR: Add condition for deletion blocked with images. When the blockpool is deleted and there are images or
snapshots in the pool, the deletion is blocked by the finalizer until they are all removed. The condition added to the cephblockpool status previously only indicated if there were radosnamespace dependencies. A new condition is now added to describe if there are images or snapshots in any rados namespace of the pool.
2. RadosNamespace CR: Add condition describing blocking deletion for the rados namespace. When a rados namespace is deleted, it cannot be purged until its images and snapshots are deleted. Now a condition is being added to the rados namespace CR status so the user does not need to read the operator log to discover the cause.
Now the OCS operator can evaluate …
=> DFBUGS-2415: Add more deletion conditions to blockpool and radosnamespace status

pkg/operator/ceph/cluster/mon/mon.go, pkg/operator/ceph/cluster/osd/deviceSet.go, pkg/operator/ceph/cluster/osd/deviceset_test.go, pkg/operator/k8sutil/pvc.go, pkg/operator/k8sutil/pvc_test.go
With a osd resize operation, currently pvc and pv may takes more time then expected.
And so the osd dont get resized and need manual re-start as currently we don't have a watch on osd's
controller that watches pv and get it resized.
add a wait time till pvc is not resized
(cherry picked from commit 94450c0db7a228ad83f282853ba1b49ca05fe19a) (cherry picked from commit 88067c4aab7f7371f3f4dc3ba99e271f43d12ed5)
**Checklist:**
=> DFBUGS-965: osd: osd should watch for pvc resize

Documentation/CRDs/specification.md, build/csv/ceph/ceph.rook.io_cephblockpoolradosnamespaces.yaml, build/csv/ceph/ceph.rook.io_cephblockpools.yaml, deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, pkg/apis/ceph.rook.io/v1/types.go, pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go, pkg/daemon/ceph/client/mirror.go
there is a change  from ceph on how the status
of the mirroring will look like,
Adopting with new fields so the status is correctly synced, And other components might rely on the status too
(cherry picked from commit aa326a941987224406dad2ee5283b4fabcb50849) (cherry picked from commit b9e24171ab68ff4a6fc30fca4c7c405dbefbfc3a)
**Checklist:**
=> DFBUGS-2460: rbdmirror: fix mirroring status on pool and rn

pkg/operator/ceph/nfs/config.go, pkg/operator/ceph/nfs/config_test.go, pkg/operator/ceph/nfs/nfs.go, pkg/operator/ceph/nfs/spec.go
the nfs config flie has a breaking change
to use nodeid as int,
currently nodeid was used as string
updated the code so nodeid can be used as string
(cherry picked from commit 7f465cb320cdbb200dad3e45679be28b067099f9)
**Checklist:**
=> DFBUGS-2586: nfs: fix nfs config file 4.18

pkg/operator/ceph/nfs/nfs.go
In ODF 4.17 we had a server as ocs-storagecluster-cephnfs.a Upgrades from ODF 4.17 to ODF 4.18.3/,
Rook would have added a server which would be
`node.ocs-storagecluster-cephnfs.a`
So that means we have two server in the dump,
Now if we upgrade to ODF 4.18.5 from odf 4.18.3/4, We also need to remove the
`node.ocs-storagecluster-cephnfs.a`
**Checklist:**
=> DFBUGS-2645: nfs: remove the nodeid from the server thats not used

pkg/daemon/ceph/cleanup/radosnamespace.go, pkg/daemon/ceph/cleanup/radosnamespace_test.go, pkg/daemon/ceph/client/image.go, pkg/daemon/ceph/client/image_test.go, pkg/daemon/ceph/client/osd.go
When force-deletion annotation is added to CephRadosNamespace CR, then blocklist any watchers on the Namespace images in order to remove the image from the trash
(cherry picked from commit 98475e847ed94cda2804b20116ccf95858206c5b)
**Checklist:**
=> DFBUGS-2744: pool: blocklist rns image watchers

Documentation/CRDs/specification.md, build/csv/ceph/ceph.rook.io_cephclients.yaml, build/csv/ceph/ceph.rook.io_cephclusters.yaml, deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/crds.yaml, pkg/apis/ceph.rook.io/v1/types.go, pkg/operator/ceph/client/controller.go, pkg/operator/ceph/client/controller_test.go, pkg/operator/ceph/csi/secrets.go, pkg/operator/ceph/csi/secrets_test.go, pkg/operator/k8sutil/secret.go, pkg/operator/k8sutil/secret_test.go
This is the backport of necessary changes to support management of the CSI cephx users with the CephClient CR, including enabling them to be flexible to retain the same K8s secret, as well as be compatible with the upcoming key rotation. 
Resolves https://issues.redhat.com/browse/DFBUGS-2880
**Checklist:**
=> DFBUGS-2880: Provide option to skip csi user and have option in cephClient to provide the secret name

Documentation/CRDs/Cluster/ceph-cluster-crd.md, Documentation/CRDs/specification.md, deploy/charts/rook-ceph-cluster/values.yaml, deploy/charts/rook-ceph/templates/resources.yaml, deploy/examples/cluster-on-local-pvc.yaml, deploy/examples/cluster-on-pvc-minikube.yaml, deploy/examples/cluster-on-pvc.yaml, deploy/examples/cluster.yaml, deploy/examples/crds.yaml, design/ceph/ceph-managed-disruptionbudgets.md, pkg/apis/ceph.rook.io/v1/types.go, pkg/daemon/ceph/client/osd.go, pkg/operator/ceph/cluster/osd/osd.go, pkg/operator/ceph/cluster/osd/update.go, pkg/operator/ceph/disruption/clusterdisruption/add.go, pkg/operator/ceph/disruption/clusterdisruption/osd.go, pkg/operator/ceph/disruption/clusterdisruption/osd_test.go, pkg/operator/ceph/disruption/clusterdisruption/reconcile.go, tests/framework/installer/ceph_manifests.go
This backport PR allows one healthy OSD to go down during node drain event. 
Two commits are being cherry-picked here.  
https://github.com/rook/rook/pull/15408
https://github.com/rook/rook/pull/15634
More details about the fix can be found the respective PR descriptions. 
**Checklist:**
=> DFBUGS-1501: [4.17]Allow one healthy OSD to be drained. 

build/csv/ceph/rook-ceph-operator.clusterserviceversion.yaml, deploy/examples/operator-openshift.yaml
Add memory, cpu request and limit values to operator deployment.
The values ranged as below:
- Memory: 70Mi - 215Mi
- CPU: 110m - 670m (this high value was recorded only once, and was not consistent and mostly ranged at ~120, with one instance of 250)
Ref: https://issues.redhat.com/browse/RHSTOR-6329
=> operator: add memory, cpu request and limit values

pkg/operator/ceph/object/admin.go, pkg/operator/ceph/object/user/controller.go
When Rook discovers that the RGW admin ops user is experiencing the InvalidAccessKeyId error, experimentation showed that the delete can fail. Logs suggested that radosgw-admin may be more likely to respond normally after ~30 second cooldowns.
In order to attempt to make the workaround more robust, retry the delete with a 35 second cooldown.
**Checklist:**
=> DFBUGS-2929: object: retry rgw admin ops InvalidAccessKeyId workaround

pkg/apis/ceph.rook.io/v1/scc.go
In some cluster, while we transitioned from from `default` scc to `rook-ceph-default` scc mons is not getting transitioned and still using older `default` service account. This fix will help in mon transition.
**Checklist:**
=> DFBUGS-265: mon: add 'default' service account to scc

pkg/operator/ceph/cluster/mon/health.go
shouldFailoverMonImmediately has a nil pointer exception with mons on PVC. Rook-ceph-mon-endpoint does not store node information of the mons on PVC. So `mapping.Hostname` throws nill pointer
(cherry picked from commit d399615bdc6fadcd191feff3a5ec10fb9c31ecca)
**Checklist:**
=> DFBUGS-4101: mon: fix mon health nil pointer exception

pkg/operator/ceph/controller/spec.go, pkg/operator/ceph/controller/spec_test.go
currently the extraction ipv6 was not correct
used the net package to extract the host ip from
the ipadress
(cherry picked from commit e1873cb2e74feb36b65db45fac2c189c02456b98)
**Checklist:**
=> DFBUGS-4060: external: fix ipv6 monitoring endpoint reconcile
